
INSERT INTO public.ls_mps_master (sr_no, state, mp_name, constituency, allocated_amount, slug, email, mp_id)
VALUES
(201, 'West Bengal', 'Jagannath Sarkar', 'RANAGHAT(SC)', 147000000, 'ranaghat', 'mp.ranaghat@mplads-demo.local', 'ls_ranaghat'),
(202, 'Uttar Pradesh', 'Jagdambika Pal', 'DOMARIYAGANJ', 160643957.11, 'domariyaganj', 'mp.domariyaganj@mplads-demo.local', 'ls_domariyaganj'),
(203, 'Haryana', 'JAI PARKASH', 'HISAR', 147000000, 'hisar', 'mp.hisar@mplads-demo.local', 'ls_hisar'),
(204, 'Uttar Pradesh', 'Jai Prakash', 'HARDOI (SC)', 147000000, 'hardoi', 'mp.hardoi@mplads-demo.local', 'ls_hardoi'),
(205, 'Madhya Pradesh', 'Janardan Mishra', 'REWA', 147000000, 'rewa', 'mp.rewa@mplads-demo.local', 'ls_rewa'),
(206, 'Gujarat', 'JASHUBHAI BHILUBHAI RATHVA', 'CHHOTA UDAIPUR(ST)', 147000000, 'chhota_udaipur', 'mp.chhota_udaipur@mplads-demo.local', 'ls_chhota_udaipur'),
(207, 'Gujarat', 'Jaswantsinh Sumanbhai Bhabhor', 'DAHOD(ST)', 147000000, 'dahod', 'mp.dahod@mplads-demo.local', 'ls_dahod'),
(208, 'Bihar', 'JITAN RAM MANJHI', 'GAYA (SC)', 147000000, 'gaya', 'mp.gaya@mplads-demo.local', 'ls_gaya'),
(209, 'Uttar Pradesh', 'JITENDRA KUMAR DOHARE', 'ETAWAH(SC)', 188747306.26, 'etawah', 'mp.etawah@mplads-demo.local', 'ls_etawah'),
(210, 'Jammu And Kashmir', 'Jitendra Singh', 'UDHAMPUR', 147000000, 'udhampur', 'mp.udhampur@mplads-demo.local', 'ls_udhampur'),
(211, 'Uttar Pradesh', 'JITIN PRASADA', 'PILIBHIT', 147000000, 'pilibhit', 'mp.pilibhit@mplads-demo.local', 'ls_pilibhit'),
(212, 'Jharkhand', 'JOBA MAJHI', 'SINGHBHUM(ST)', 147000000, 'singhbhum', 'mp.singhbhum@mplads-demo.local', 'ls_singhbhum'),
(213, 'Assam', 'JOYANTA BASUMATARY', 'KOKRAJHAR (ST)', 147000000, 'kokrajhar', 'mp.kokrajhar@mplads-demo.local', 'ls_kokrajhar'),
(214, 'West Bengal', 'JUNE MALIAH', 'MEDINIPUR', 147000000, 'medinipur', 'mp.medinipur@mplads-demo.local', 'ls_medinipur'),
(215, 'Madhya Pradesh', 'JYOTIRADITYA M. SCINDIA', 'GUNA', 147000000, 'guna', 'mp.guna@mplads-demo.local', 'ls_guna'),
(216, 'Chhattisgarh', 'Jyotsna Charandas Mahant', 'KORBA', 155153738.11, 'korba', 'mp.korba@mplads-demo.local', 'ls_korba'),
(217, 'Tamil Nadu', 'K E PRAKASH', 'ERODE', 147000000, 'erode', 'mp.erode@mplads-demo.local', 'ls_erode'),
(218, 'Kerala', 'K RADHAKRISHNAN', 'ALATHUR(SC)', 147000000, 'alathur', 'mp.alathur@mplads-demo.local', 'ls_alathur'),
(219, 'Tamil Nadu', 'K Subbarayan', 'TIRUPPUR', 147000000, 'tiruppur', 'mp.tiruppur@mplads-demo.local', 'ls_tiruppur'),
(220, 'Kerala', 'K. C VENUGOPAL', 'ALAPPUZHA', 147000000, 'alappuzha', 'mp.alappuzha@mplads-demo.local', 'ls_alappuzha'),
(221, 'Karnataka', 'K. RAJASHEKAR BASAVARAJ HITNAL', 'KOPPAL', 147000000, 'koppal', 'mp.koppal@mplads-demo.local', 'ls_koppal'),
(222, 'Telangana', 'KADIYAM KAVYA', 'WARANGEL(SC)', 147000000, 'warangel', 'mp.warangel@mplads-demo.local', 'ls_warangel'),
(223, 'West Bengal', 'Kakoli Ghosh Dastidar', 'BARASAT', 147000000, 'barasat', 'mp.barasat@mplads-demo.local', 'ls_barasat'),
(224, 'The Dadra And Nagar Haveli And Daman And Diu', 'Kalaben Mohanbhai Delkar', 'DADRA & NAGAR HAVELI (ST)', 269500000, 'dadra_and_nagar_haveli', 'mp.dadra_and_nagar_haveli@mplads-demo.local', 'ls_dadra_and_nagar_haveli'),
(225, 'Tamil Nadu', 'Kalanidhi Veeraswamy', 'CHENNAI NORTH', 171500000, 'chennai_north', 'mp.chennai_north@mplads-demo.local', 'ls_chennai_north'),
(226, 'Jharkhand', 'KALI CHARAN MUNDA', 'KHUNTI(ST)', 147000000, 'khunti', 'mp.khunti@mplads-demo.local', 'ls_khunti'),
(227, 'Jharkhand', 'KALI CHARAN SINGH', 'CHATRA', 147000000, 'chatra', 'mp.chatra@mplads-demo.local', 'ls_chatra'),
(228, 'West Bengal', 'KALIPADA SAREN', 'JHARGRAM(ST)', 147000000, 'jhargram', 'mp.jhargram@mplads-demo.local', 'ls_jhargram'),
(229, 'West Bengal', 'Kalyan Banerjee', 'SREERAMPUR', 147000000, 'sreerampur', 'mp.sreerampur@mplads-demo.local', 'ls_sreerampur'),
(230, 'Maharashtra', 'KALYAN VAIJINATHRAO KALE', 'JALNA', 147000000, 'jalna', 'mp.jalna@mplads-demo.local', 'ls_jalna'),
(231, 'Assam', 'KAMAKHYA PRASAD TASA', 'Kaziranga', 147000000, 'kaziranga', 'mp.kaziranga@mplads-demo.local', 'ls_kaziranga'),
(232, 'Delhi', 'Kamaljeet Sehrawat', 'WEST DELHI', 147000000, 'west_delhi', 'mp.west_delhi@mplads-demo.local', 'ls_west_delhi'),
(233, 'Chhattisgarh', 'KAMLESH JANGDE', 'JANJGIR CHAMPA(SC)', 150384382.11, 'janjgir_champa', 'mp.janjgir_champa@mplads-demo.local', 'ls_janjgir_champa'),
(234, 'Uttar Pradesh', 'Kamlesh Paswan', 'BANSGAON(SC)', 147000000, 'bansgaon', 'mp.bansgaon@mplads-demo.local', 'ls_bansgaon'),
(235, 'Himachal Pradesh', 'Kangana Ranaut', 'MANDI', 147000000, 'mandi', 'mp.mandi@mplads-demo.local', 'ls_mandi'),
(236, 'Tamil Nadu', 'Kani K Navas', 'RAMANATHAPURAM', 147000000, 'ramanathapuram', 'mp.ramanathapuram@mplads-demo.local', 'ls_ramanathapuram'),
(237, 'Tamil Nadu', 'Kanimozhi Karunanidhi', 'THOOTHUKKUDI', 147000000, 'thoothukkudi', 'mp.thoothukkudi@mplads-demo.local', 'ls_thoothukkudi'),
(238, 'Uttar Pradesh', 'KANWAR SINGH TANWAR', 'AMROHA', 147000000, 'amroha', 'mp.amroha@mplads-demo.local', 'ls_amroha'),
(239, 'Uttar Pradesh', 'KARAN BHUSHAN SINGH', 'KAISERGANJ', 147000000, 'kaiserganj', 'mp.kaiserganj@mplads-demo.local', 'ls_kaiserganj'),
(240, 'West Bengal', 'KARTICK CHANDRA PAUL', 'RAIGANJ', 202677986.56, 'raiganj', 'mp.raiganj@mplads-demo.local', 'ls_raiganj'),
(241, 'Bihar', 'Kaushalendra Kumar', 'NALANDA', 147000000, 'nalanda', 'mp.nalanda@mplads-demo.local', 'ls_nalanda'),
(242, 'West Bengal', 'Khagen Murmu', 'MALDAHA UTTAR', 147000000, 'maldaha_uttar', 'mp.maldaha_uttar@mplads-demo.local', 'ls_maldaha_uttar'),
(243, 'West Bengal', 'Khalilur Rahaman', 'JANGIPUR', 147000000, 'jangipur', 'mp.jangipur@mplads-demo.local', 'ls_jangipur'),
(244, 'Andhra Pradesh', 'Kinjarapu Ram Mohan Naidu', 'SRIKAKULAM', 171200630.11, 'srikakulam', 'mp.srikakulam@mplads-demo.local', 'ls_srikakulam'),
(245, 'Arunachal Pradesh', 'Kiren Rijiju', 'ARUNACHAL WEST', 147000000, 'arunachal_west', 'mp.arunachal_west@mplads-demo.local', 'ls_arunachal_west'),
(246, 'Uttar Pradesh', 'Kirti Vardhan Singh', 'GONDA', 147000000, 'gonda', 'mp.gonda@mplads-demo.local', 'ls_gonda'),
(247, 'Telangana', 'Kishan Reddy Gangapuram', 'SECUNDERABAD', 147000000, 'secunderabad', 'mp.secunderabad@mplads-demo.local', 'ls_secunderabad'),
(248, 'Uttar Pradesh', 'KISHORI LAL', 'AMETHI', 171500000, 'amethi', 'mp.amethi@mplads-demo.local', 'ls_amethi'),
(249, 'Telangana', 'KONDA VISHWESHWAR REDDY', 'CHELVELLA', 233721420.96, 'chelvella', 'mp.chelvella@mplads-demo.local', 'ls_chelvella'),
(250, 'Karnataka', 'KOTA SRINIVAS POOJARY', 'UDUPI CHIKMAGALUR', 147000000, 'udupi_chikmagalur', 'mp.udupi_chikmagalur@mplads-demo.local', 'ls_udupi_chikmagalur'),
(251, 'Assam', 'Kripanath Mallah', 'KARIMGANJ (SC)', 147000000, 'karimganj', 'mp.karimganj@mplads-demo.local', 'ls_karimganj'),
(252, 'Haryana', 'Krishan Pal Gurjar', 'FARIDABAD', 147000000, 'faridabad', 'mp.faridabad@mplads-demo.local', 'ls_faridabad'),
(253, 'Uttar Pradesh', 'KRISHNA DEVI SHIVSHANKER PATEL', 'BANDA', 147000000, 'banda', 'mp.banda@mplads-demo.local', 'ls_banda'),
(254, 'Andhra Pradesh', 'Krishna Prasad Tenneti', 'BAPATLA', 167796849.11, 'bapatla', 'mp.bapatla@mplads-demo.local', 'ls_bapatla'),
(255, 'Tripura', 'KRITI DEVI DEBBARMAN', 'TRIPURA EAST(ST)', 147000000, 'tripura_east', 'mp.tripura_east@mplads-demo.local', 'ls_tripura_east'),
(256, 'Rajasthan', 'KULDEEP INDORA', 'GANGANAGAR(SC)', 147000000, 'ganganagar', 'mp.ganganagar@mplads-demo.local', 'ls_ganganagar'),
(257, 'Telangana', 'KUNDURU RAGHUVEER', 'NALGONDA', 162952022, 'nalgonda', 'mp.nalgonda@mplads-demo.local', 'ls_nalgonda'),
(258, 'Uttar Pradesh', 'LALJI VERMA', 'AMBEDKAR NAGAR', 147000000, 'ambedkar_nagar', 'mp.ambedkar_nagar@mplads-demo.local', 'ls_ambedkar_nagar'),
(259, 'Andhra Pradesh', 'Lavu Sri Krishna Devarayalu', 'NARASARAOPET', 174009663.11, 'narasaraopet', 'mp.narasaraopet@mplads-demo.local', 'ls_narasaraopet'),
(260, 'Uttar Pradesh', 'LAXMIKANT PAPPU NISHAD', 'SANT KABIR NAGAR', 147000000, 'sant_kabir_nagar', 'mp.sant_kabir_nagar@mplads-demo.local', 'ls_sant_kabir_nagar'),
(261, 'Bihar', 'LOVELY ANAND', 'SHEOHAR', 147000000, 'sheohar', 'mp.sheohar@mplads-demo.local', 'ls_sheohar'),
(262, 'Rajasthan', 'LUMBARAM', 'JALORE', 147000000, 'jalore', 'mp.jalore@mplads-demo.local', 'ls_jalore'),
(263, 'Karnataka', 'M. MALLESH BABU', 'KOLAR(SC)', 147065957.11, 'kolar', 'mp.kolar@mplads-demo.local', 'ls_kolar'),
(264, 'Tamil Nadu', 'M.K. VISHNUPRASAD', 'CUDDALORE', 147000000, 'cuddalore', 'mp.cuddalore@mplads-demo.local', 'ls_cuddalore'),
(265, 'Andhra Pradesh', 'Maddila Gurumoorthy', 'TIRUPATI(SC)', 180399007, 'tirupati', 'mp.tirupati@mplads-demo.local', 'ls_tirupati'),
(266, 'Telangana', 'MADHAVANENI RAGHUNANDAN RAO', 'MEDAK', 147000000, 'medak', 'mp.medak@mplads-demo.local', 'ls_medak'),
(267, 'Andhra Pradesh', 'Magunta Sreenivasulu Reddy', 'ONGOLE', 147000000, 'ongole', 'mp.ongole@mplads-demo.local', 'ls_ongole'),
(268, 'Madhya Pradesh', 'Mahendra Singh Solanky', 'DEWAS(SC)', 147000000, 'dewas', 'mp.dewas@mplads-demo.local', 'ls_dewas'),
(269, 'Chhattisgarh', 'MAHESH KASHYAP', 'BASTAR(ST)', 147000000, 'bastar', 'mp.bastar@mplads-demo.local', 'ls_bastar'),
(270, 'Uttar Pradesh', 'Mahesh Sharma', 'GAUTAM BUDDHA NAGAR', 148816284.11, 'gautam_buddha_nagar', 'mp.gautam_buddha_nagar@mplads-demo.local', 'ls_gautam_buddha_nagar'),
(271, 'Rajasthan', 'MAHIMA KUMARI MEWAR', 'RAJSAMAND', 183892143, 'rajsamand', 'mp.rajsamand@mplads-demo.local', 'ls_rajsamand'),
(272, 'Uttarakhand', 'Mala Rajya Laxmi Shah', 'TEHRI GARHWAL', 147000000, 'tehri_garhwal', 'mp.tehri_garhwal@mplads-demo.local', 'ls_tehri_garhwal'),
(273, 'West Bengal', 'Mala Roy', 'KOLKATA DAKSHIN', 147000000, 'kolkata_dakshin', 'mp.kolkata_dakshin@mplads-demo.local', 'ls_kolkata_dakshin'),
(274, 'Tamil Nadu', 'MALAIYARASAN D', 'KALLAKURICHI', 201599593, 'kallakurichi', 'mp.kallakurichi@mplads-demo.local', 'ls_kallakurichi'),
(275, 'Odisha', 'MALVIKA DEVI', 'KALAHANDI', 147000000, 'kalahandi', 'mp.kalahandi@mplads-demo.local', 'ls_kalahandi'),
(276, 'Punjab', 'MALVINDER SINGH KANG', 'ANANDPUR SAHIB', 147000000, 'anandpur_sahib', 'mp.anandpur_sahib@mplads-demo.local', 'ls_anandpur_sahib'),
(277, 'Tamil Nadu', 'MANI. A.', 'DHARAMAPURI', 164515071.11, 'dharamapuri', 'mp.dharamapuri@mplads-demo.local', 'ls_dharamapuri'),
(278, 'Tamil Nadu', 'Manickam Tagore B', 'VIRUDHUNAGAR', 147000000, 'virudhunagar', 'mp.virudhunagar@mplads-demo.local', 'ls_virudhunagar'),
(279, 'Jharkhand', 'MANISH JAISWAL', 'HAZARIBAGH', 147000000, 'hazaribagh', 'mp.hazaribagh@mplads-demo.local', 'ls_hazaribagh'),
(280, 'Chandigarh', 'MANISH TEWARI', 'CHANDIGARH', 178351443.75, 'chandigarh', 'mp.chandigarh@mplads-demo.local', 'ls_chandigarh'),
(281, 'Rajasthan', 'MANJU SHARMA', 'JAIPUR', 167082901.11, 'jaipur', 'mp.jaipur@mplads-demo.local', 'ls_jaipur'),
(282, 'Rajasthan', 'MANNA LAL RAWAT', 'UDAIPUR(ST)', 147000000, 'udaipur', 'mp.udaipur@mplads-demo.local', 'ls_udaipur'),
(283, 'Haryana', 'MANOHAR LAL', 'KARNAL', 147000000, 'karnal', 'mp.karnal@mplads-demo.local', 'ls_karnal'),
(284, 'Bihar', 'MANOJ KUMAR', 'SASARAM(SC)', 147000000, 'sasaram', 'mp.sasaram@mplads-demo.local', 'ls_sasaram'),
(285, 'West Bengal', 'MANOJ TIGGA', 'ALIPURDUARS(ST)', 147000000, 'alipurduars', 'mp.alipurduars@mplads-demo.local', 'ls_alipurduars'),
(286, 'Delhi', 'Manoj Tiwari', 'NORTH EAST DELHI', 225843858, 'north_east_delhi', 'mp.north_east_delhi@mplads-demo.local', 'ls_north_east_delhi'),
(287, 'Gujarat', 'Mansukhbhai Dhanjibhai Vasava', 'BHARUCH', 147000000, 'bharuch', 'mp.bharuch@mplads-demo.local', 'ls_bharuch'),
(288, 'Jammu And Kashmir', 'MIAN ALTAF AHMAD', 'ANANTNAG', 147000000, 'anantnag', 'mp.anantnag@mplads-demo.local', 'ls_anantnag'),
(289, 'Andhra Pradesh', 'Midhun Reddy', 'RAJAMPET', 178951477.11, 'rajampet', 'mp.rajampet@mplads-demo.local', 'ls_rajampet'),
(290, 'Bihar', 'MISHA BHARTI', 'PATALIPUTRA', 147000000, 'pataliputra', 'mp.pataliputra@mplads-demo.local', 'ls_pataliputra'),
(291, 'Gujarat', 'Mitesh Rameshbhai Bakabhai Patel', 'ANAND', 147000000, 'anand', 'mp.anand@mplads-demo.local', 'ls_anand'),
(292, 'Ladakh', 'Mohamed Haneefa', 'LADAKH', 161114542, 'ladakh', 'mp.ladakh@mplads-demo.local', 'ls_ladakh'),
(293, 'Uttar Pradesh', 'MOHIBBULLAH', 'RAMPUR', 147000000, 'rampur', 'mp.rampur@mplads-demo.local', 'ls_rampur'),
(294, 'Maharashtra', 'MOHITE PATIL DHAIRYASHEEL RAJSINH', 'MADHA', 195613601.7, 'madha', 'mp.madha@mplads-demo.local', 'ls_madha'),
(295, 'Bihar', 'Mr Gopal Jee Thakur', 'DARBHANGA', 147000000, 'darbhanga', 'mp.darbhanga@mplads-demo.local', 'ls_darbhanga'),
(296, 'West Bengal', 'Ms Mahua Moitra', 'KRISHNANAGAR', 159865046, 'krishnanagar', 'mp.krishnanagar@mplads-demo.local', 'ls_krishnanagar'),
(297, 'Lakshadweep', 'MUHAMMED HAMDULLAH SAYEED', 'LAKSHADWEEP(ST)', 153942460.41, 'lakshadweep', 'mp.lakshadweep@mplads-demo.local', 'ls_lakshadweep'),
(298, 'Uttar Pradesh', 'Mukesh Rajput', 'FARRUKHABAD', 147000000, 'farrukhabad', 'mp.farrukhabad@mplads-demo.local', 'ls_farrukhabad'),
(299, 'Gujarat', 'MUKESHKUMAR CHANDRAKAANT DALAL', 'SURAT', 147000000, 'surat', 'mp.surat@mplads-demo.local', 'ls_surat'),
(300, 'Rajasthan', 'MURARI LAL MEENA', 'DAUSA(ST)', 147000000, 'dausa', 'mp.dausa@mplads-demo.local', 'ls_dausa')
ON CONFLICT (sr_no) DO UPDATE SET
  state = EXCLUDED.state,
  mp_name = EXCLUDED.mp_name,
  constituency = EXCLUDED.constituency,
  allocated_amount = EXCLUDED.allocated_amount,
  slug = EXCLUDED.slug,
  email = EXCLUDED.email,
  mp_id = EXCLUDED.mp_id;
