
INSERT INTO public.ls_mps_master (sr_no, state, mp_name, constituency, allocated_amount, slug, email, mp_id)
VALUES
(101, 'Goa', 'CAPTAIN VIRIATO FERNANDES', 'SOUTH GOA', 147000000, 'south_goa', 'mp.south_goa@mplads-demo.local', 'ls_south_goa'),
(102, 'Telangana', 'CHAMALA KIRAN KUMAR REDDY', 'BHONGIR', 147000000, 'bhongir', 'mp.bhongir@mplads-demo.local', 'ls_bhongir'),
(103, 'Uttar Pradesh', 'CHANDAN CHAUHAN', 'BIJNOR', 147000000, 'bijnor', 'mp.bijnor@mplads-demo.local', 'ls_bijnor'),
(104, 'Rajasthan', 'Chandra Prakash Joshi', 'CHITTORGARH', 147000000, 'chittorgarh', 'mp.chittorgarh@mplads-demo.local', 'ls_chittorgarh'),
(105, 'Uttar Pradesh', 'CHANDRA SHEKHAR', 'NAGINA(SC)', 147000000, 'nagina', 'mp.nagina@mplads-demo.local', 'ls_nagina'),
(106, 'Gujarat', 'CHANDUBHAI CHHAGANBHAI SHIHORA', 'SURENDRANAGAR', 147000000, 'surendranagar', 'mp.surendranagar@mplads-demo.local', 'ls_surendranagar'),
(107, 'Punjab', 'CHARANJIT SINGH CHANNI', 'JALANDHAR(SC)', 147000000, 'jalandhar', 'mp.jalandhar@mplads-demo.local', 'ls_jalandhar'),
(108, 'Maharashtra', 'CHAVAN VASANTRAO BALWANTRAO', 'NANDED', 0, 'nanded', 'mp.nanded@mplads-demo.local', 'ls_nanded'),
(109, 'Uttar Pradesh', 'CHHATRA PAL SINGH GANGWAR', 'BAREILLY', 147000000, 'bareilly', 'mp.bareilly@mplads-demo.local', 'ls_bareilly'),
(110, 'Maharashtra', 'CHHATRAPATI SHAHU SHAHAJI', 'KOLHAPUR', 147000000, 'kolhapur', 'mp.kolhapur@mplads-demo.local', 'ls_kolhapur'),
(111, 'Uttar Pradesh', 'CHHOTELAL', 'ROBERTSGANJ(SC)', 147000000, 'robertsganj', 'mp.robertsganj@mplads-demo.local', 'ls_robertsganj'),
(112, 'Chhattisgarh', 'CHINTAMANI MAHARAJ', 'SARGUJA(ST)', 147000000, 'sarguja', 'mp.sarguja@mplads-demo.local', 'ls_sarguja'),
(113, 'Bihar', 'CHIRAG PASWAN', 'HAJIPUR(SC)', 147000000, 'hajipur', 'mp.hajipur@mplads-demo.local', 'ls_hajipur'),
(114, 'Tamil Nadu', 'CN Annadurai', 'TIRUVANNAMALAI', 148579509.11, 'tiruvannamalai', 'mp.tiruvannamalai@mplads-demo.local', 'ls_tiruvannamalai'),
(115, 'Tamil Nadu', 'D M Kathir Anand', 'VELLORE', 160196941.11, 'vellore', 'mp.vellore@mplads-demo.local', 'ls_vellore'),
(116, 'Tamil Nadu', 'D Ravikumar', 'VILUPPURAM(SC)', 197598306.11, 'viluppuram', 'mp.viluppuram@mplads-demo.local', 'ls_viluppuram'),
(117, 'Andhra Pradesh', 'Daggubati Purandeshwari', 'RAJAHMUNDRY', 147000000, 'rajahmundry', 'mp.rajahmundry@mplads-demo.local', 'ls_rajahmundry'),
(118, 'Andhra Pradesh', 'DAGGUMALLA PRASADA RAO', 'CHITTOOR', 147000000, 'chittoor', 'mp.chittoor@mplads-demo.local', 'ls_chittoor'),
(119, 'Rajasthan', 'DAMODAR AGARWAL', 'BHILWARA', 147000000, 'bhilwara', 'mp.bhilwara@mplads-demo.local', 'ls_bhilwara'),
(120, 'Uttar Pradesh', 'DAROGA PRASAD SAROJ', 'LALGANJ (SC)', 147000000, 'lalganj', 'mp.lalganj@mplads-demo.local', 'ls_lalganj'),
(121, 'Madhya Pradesh', 'DARSHAN SINGH CHOUDHARY', 'HOSHANGABAD', 147000000, 'hoshangabad', 'mp.hoshangabad@mplads-demo.local', 'ls_hoshangabad'),
(122, 'Haryana', 'DEEPENDER SINGH HOODA', 'ROHTAK', 147000000, 'rohtak', 'mp.rohtak@mplads-demo.local', 'ls_rohtak'),
(123, 'Uttar Pradesh', 'Devendra Alias Bhole Singh', 'AKBARPUR', 147000000, 'akbarpur', 'mp.akbarpur@mplads-demo.local', 'ls_akbarpur'),
(124, 'Bihar', 'DEVESH CHANDRA THAKUR', 'SITAMARHI', 163809205.11, 'sitamarhi', 'mp.sitamarhi@mplads-demo.local', 'ls_sitamarhi'),
(125, 'Uttar Pradesh', 'DEVESH SHAKYA', 'ETAH', 147000000, 'etah', 'mp.etah@mplads-demo.local', 'ls_etah'),
(126, 'Gujarat', 'Devusinh Jesingbhai Chauhan', 'KHEDA', 147000000, 'kheda', 'mp.kheda@mplads-demo.local', 'ls_kheda'),
(127, 'Maharashtra', 'Dhairyasheel Sambhajirao Mane', 'HATKANANGLE', 147000000, 'hatkanangle', 'mp.hatkanangle@mplads-demo.local', 'ls_hatkanangle'),
(128, 'Maharashtra', 'DHANORKAR PRATIBHA SURESH ALIAS BALUBHAU', 'CHANDRAPUR', 147000000, 'chandrapur', 'mp.chandrapur@mplads-demo.local', 'ls_chandrapur'),
(129, 'Odisha', 'DHARMENDRA PRADHAN', 'SAMBALPUR', 147000000, 'sambalpur', 'mp.sambalpur@mplads-demo.local', 'ls_sambalpur'),
(130, 'Uttar Pradesh', 'DHARMENDRA YADAV', 'AZAMGARH', 147000000, 'azamgarh', 'mp.azamgarh@mplads-demo.local', 'ls_azamgarh'),
(131, 'Gujarat', 'DHAVAL LAXMANBHAI PATEL', 'VALSAD(ST)', 147000000, 'valsad', 'mp.valsad@mplads-demo.local', 'ls_valsad'),
(132, 'Bihar', 'Dileshwar Kamait', 'SUPAUL', 150450930.89, 'supaul', 'mp.supaul@mplads-demo.local', 'ls_supaul'),
(133, 'Assam', 'Dilip Saikia', 'Darrang-Udalguri', 147000000, 'darrang_udalguri', 'mp.darrang_udalguri@mplads-demo.local', 'ls_darrang_udalguri'),
(134, 'Bihar', 'Dinesh Chandra Yadav', 'MADHEPURA', 150070866.11, 'madhepura', 'mp.madhepura@mplads-demo.local', 'ls_madhepura'),
(135, 'Gujarat', 'DINESHBHAI MAKWANA', 'AHMEDABAD WEST(SC)', 160434965.11, 'ahmedabad_west', 'mp.ahmedabad_west@mplads-demo.local', 'ls_ahmedabad_west'),
(136, 'Andhra Pradesh', 'DR BYREDDY SHABARI', 'NANDYAL', 150675889.11, 'nandyal', 'mp.nandyal@mplads-demo.local', 'ls_nandyal'),
(137, 'Karnataka', 'DR C N MANJUNATH', 'BANGALORE RURAL', 147000000, 'bangalore_rural', 'mp.bangalore_rural@mplads-demo.local', 'ls_bangalore_rural'),
(138, 'Andhra Pradesh', 'Dr Chandra Sekhar Pemmasani', 'GUNTUR', 159774113.11, 'guntur', 'mp.guntur@mplads-demo.local', 'ls_guntur'),
(139, 'Punjab', 'DR DHARAMVIRA GANDHI', 'PATIALA', 147000000, 'patiala', 'mp.patiala@mplads-demo.local', 'ls_patiala'),
(140, 'West Bengal', 'Dr Jayanta Kumar Roy', 'JALPAIGURI(SC)', 147000000, 'jalpaiguri', 'mp.jalpaiguri@mplads-demo.local', 'ls_jalpaiguri'),
(141, 'Maharashtra', 'DR KALGE SHIVAJI BANDAPPA', 'LATUR(SC)', 147000000, 'latur', 'mp.latur@mplads-demo.local', 'ls_latur'),
(142, 'Bihar', 'Dr Mohammad Jawed', 'KISHANGANJ', 148669229.11, 'kishanganj', 'mp.kishanganj@mplads-demo.local', 'ls_kishanganj'),
(143, 'Uttar Pradesh', 'DR RAJKUMAR SANGWAN', 'BAGHPAT', 147000000, 'baghpat', 'mp.baghpat@mplads-demo.local', 'ls_baghpat'),
(144, 'Tamil Nadu', 'DR RANI SRI KUMAR', 'TENKASI(SC)', 153060922.82, 'tenkasi', 'mp.tenkasi@mplads-demo.local', 'ls_tenkasi'),
(145, 'Kerala', 'Dr Shashi Tharoor', 'THIRUVANANTHAPURAM', 147000000, 'thiruvananthapuram', 'mp.thiruvananthapuram@mplads-demo.local', 'ls_thiruvananthapuram'),
(146, 'West Bengal', 'Dr Sukanta Majumdar', 'BALURGHAT', 157085364.9, 'balurghat', 'mp.balurghat@mplads-demo.local', 'ls_balurghat'),
(147, 'Gujarat', 'DR. HEMANG JOSHI', 'VADODARA', 147000000, 'vadodara', 'mp.vadodara@mplads-demo.local', 'ls_vadodara'),
(148, 'Maharashtra', 'DR. HEMANT VISHNU SAVARA', 'PALGHAR(ST)', 147000000, 'palghar', 'mp.palghar@mplads-demo.local', 'ls_palghar'),
(149, 'Maharashtra', 'DR. KIRSAN NAMDEO', 'GADCHIROLI-CHIMUR(ST)', 147000000, 'gadchiroli_chimur', 'mp.gadchiroli_chimur@mplads-demo.local', 'ls_gadchiroli_chimur'),
(150, 'Madhya Pradesh', 'DR. LATA WANKHEDE', 'SAGAR', 147000000, 'sagar', 'mp.sagar@mplads-demo.local', 'ls_sagar'),
(151, 'Kerala', 'DR. M.P ABDUSSAMAD SAMADANI', 'PONNANI', 170434031.11, 'ponnani', 'mp.ponnani@mplads-demo.local', 'ls_ponnani'),
(152, 'Gujarat', 'DR. MANSUKH MANDAVIYA', 'PORBANDAR', 147000000, 'porbandar', 'mp.porbandar@mplads-demo.local', 'ls_porbandar'),
(153, 'Karnataka', 'DR. PRABHA MALLIKARJUN', 'DAVANAGERE', 147000000, 'davanagere', 'mp.davanagere@mplads-demo.local', 'ls_davanagere'),
(154, 'Odisha', 'DR. PRADEEP KUMAR PANIGRAHY', 'BERHAMPUR', 147000000, 'berhampur', 'mp.berhampur@mplads-demo.local', 'ls_berhampur'),
(155, 'Maharashtra', 'DR. PRASHANT YADAORAO PADOLE', 'BHANDARA-GONDIYA', 159680283.39, 'bhandara_gondiya', 'mp.bhandara_gondiya@mplads-demo.local', 'ls_bhandara_gondiya'),
(156, 'Punjab', 'DR. RAJ KUMAR CHABBEWAL', 'HOSHIARPUR(SC)', 147000000, 'hoshiarpur', 'mp.hoshiarpur@mplads-demo.local', 'ls_hoshiarpur'),
(157, 'Madhya Pradesh', 'DR. RAJESH MISHRA', 'SIDHI', 262724510.35, 'sidhi', 'mp.sidhi@mplads-demo.local', 'ls_sidhi'),
(158, 'Uttar Pradesh', 'DR. S P SINGH', 'PRATAPGARH', 147000000, 'pratapgarh', 'mp.pratapgarh@mplads-demo.local', 'ls_pratapgarh'),
(159, 'West Bengal', 'DR. SHARMILA SARKAR', 'BARDHAMAN PURBA(SC)', 147000000, 'bardhaman_purba', 'mp.bardhaman_purba@mplads-demo.local', 'ls_bardhaman_purba'),
(160, 'Karnataka', 'DR.K.SUDHAKAR', 'CHIKBALLAPUR', 147000000, 'chikballapur', 'mp.chikballapur@mplads-demo.local', 'ls_chikballapur'),
(161, 'Telangana', 'DR.MALLU RAVI', 'NAGARKURNOOL(SC)', 147000000, 'nagarkurnool', 'mp.nagarkurnool@mplads-demo.local', 'ls_nagarkurnool'),
(162, 'Jharkhand', 'DULU MAHATO', 'DHANBAD', 147000000, 'dhanbad', 'mp.dhanbad@mplads-demo.local', 'ls_dhanbad'),
(163, 'Tamil Nadu', 'DURAI VAIKO', 'TIRUCHIRAPPALLI', 147000000, 'tiruchirappalli', 'mp.tiruchirappalli@mplads-demo.local', 'ls_tiruchirappalli'),
(164, 'Madhya Pradesh', 'Durga Das Uikey', 'BETUL(ST)', 151569502.91, 'betul', 'mp.betul@mplads-demo.local', 'ls_betul'),
(165, 'Rajasthan', 'Dushyant Singh', 'JHALAWAR-BARAN', 147000000, 'jhalawar_baran', 'mp.jhalawar_baran@mplads-demo.local', 'ls_jhalawar_baran'),
(166, 'Karnataka', 'E. TUKARAM', 'BELLARY(ST)', 147000000, 'bellary', 'mp.bellary@mplads-demo.local', 'ls_bellary'),
(167, 'Kerala', 'E.T. MOHAMMED BASHEER', 'MALAPPURAM', 163895872.11, 'malappuram', 'mp.malappuram@mplads-demo.local', 'ls_malappuram'),
(168, 'Telangana', 'EATALA RAJENDER', 'MALKAJGIRI', 327477390.86, 'malkajgiri', 'mp.malkajgiri@mplads-demo.local', 'ls_malkajgiri'),
(169, 'Tamil Nadu', 'ESWARASAMY K', 'POLLACHI', 162315106.11, 'pollachi', 'mp.pollachi@mplads-demo.local', 'ls_pollachi'),
(170, 'Madhya Pradesh', 'Faggan Singh Kulaste', 'MANDLA(ST)', 151861648.41, 'mandla', 'mp.mandla@mplads-demo.local', 'ls_mandla'),
(171, 'Karnataka', 'G. KUMAR NAIK', 'RAICHUR(ST)', 147000000, 'raichur', 'mp.raichur@mplads-demo.local', 'ls_raichur'),
(172, 'Maharashtra', 'GAIKWAD VARSHA EKNATH', 'MUMBAI NORTH-CENTRAL', 147000000, 'mumbai_north_central', 'mp.mumbai_north_central@mplads-demo.local', 'ls_mumbai_north_central'),
(173, 'Madhya Pradesh', 'Gajendra Singh Patel', 'KHARGONE(ST)', 147000000, 'khargone', 'mp.khargone@mplads-demo.local', 'ls_khargone'),
(174, 'Rajasthan', 'Gajendra Singh Shekhawat', 'JODHPUR', 147000000, 'jodhpur', 'mp.jodhpur@mplads-demo.local', 'ls_jodhpur'),
(175, 'Tamil Nadu', 'GANAPATHY RAJKUMAR P', 'COIMBATORE', 147370490.11, 'coimbatore', 'mp.coimbatore@mplads-demo.local', 'ls_coimbatore'),
(176, 'Tamil Nadu', 'Ganesan Selvam', 'KANCHEEPURAM(SC)', 186508749.11, 'kancheepuram', 'mp.kancheepuram@mplads-demo.local', 'ls_kancheepuram'),
(177, 'Madhya Pradesh', 'Ganesh Singh', 'SATNA', 147000000, 'satna', 'mp.satna@mplads-demo.local', 'ls_satna'),
(178, 'Assam', 'GAURAV GOGOI', 'JORHAT', 147000000, 'jorhat', 'mp.jorhat@mplads-demo.local', 'ls_jorhat'),
(179, 'Gujarat', 'GENIBEN NAGAJI THAKOR', 'BANASKANTHA', 147000000, 'banaskantha', 'mp.banaskantha@mplads-demo.local', 'ls_banaskantha'),
(180, 'Bihar', 'Giridhari Yadav', 'BANKA', 147000000, 'banka', 'mp.banka@mplads-demo.local', 'ls_banka'),
(181, 'Bihar', 'Giriraj Singh', 'BEGUSARAI', 147000000, 'begusarai', 'mp.begusarai@mplads-demo.local', 'ls_begusarai'),
(182, 'Andhra Pradesh', 'GM Harish Balayogi', 'AMALAPURAM(SC)', 147000000, 'amalapuram', 'mp.amalapuram@mplads-demo.local', 'ls_amalapuram'),
(183, 'Telangana', 'GODAM NAGESH', 'ADILABAD(ST)', 147000000, 'adilabad', 'mp.adilabad@mplads-demo.local', 'ls_adilabad'),
(184, 'Tamil Nadu', 'GOPINATH K', 'KRISHNAGIRI', 147000000, 'krishnagiri', 'mp.krishnagiri@mplads-demo.local', 'ls_krishnagiri'),
(185, 'Karnataka', 'GOVIND MAKTHAPPA KARJOL', 'CHITRADURGA(SC)', 147000000, 'chitradurga', 'mp.chitradurga@mplads-demo.local', 'ls_chitradurga'),
(186, 'Andhra Pradesh', 'Gumma Thanuja Rani', 'ARAKU(ST)', 149458905.11, 'araku', 'mp.araku@mplads-demo.local', 'ls_araku'),
(187, 'Punjab', 'GURMEET SINGH MEET HAYER', 'SANGRUR', 147000000, 'sangrur', 'mp.sangrur@mplads-demo.local', 'ls_sangrur'),
(188, 'Madhya Pradesh', 'Gyaneshwar Patil', 'KHANDWA', 155690684.77, 'khandwa', 'mp.khandwa@mplads-demo.local', 'ls_khandwa'),
(189, 'Karnataka', 'H.D. KUMARASWAMY', 'MANDYA', 147000000, 'mandya', 'mp.mandya@mplads-demo.local', 'ls_mandya'),
(190, 'Uttar Pradesh', 'HARENDRA SINGH MALIK', 'MUZAFFARNAGAR', 147000000, 'muzaffarnagar', 'mp.muzaffarnagar@mplads-demo.local', 'ls_muzaffarnagar'),
(191, 'Gujarat', 'HARIBHAI PATEL', 'MAHESANA', 147000000, 'mahesana', 'mp.mahesana@mplads-demo.local', 'ls_mahesana'),
(192, 'Rajasthan', 'HARISH CHANDRA MEENA', 'TONK-SAWAI MADHOPUR', 147000000, 'tonk_sawai_madhopur', 'mp.tonk_sawai_madhopur@mplads-demo.local', 'ls_tonk_sawai_madhopur'),
(193, 'Delhi', 'Harsh Malhotra', 'EAST DELHI', 147134131, 'east_delhi', 'mp.east_delhi@mplads-demo.local', 'ls_east_delhi'),
(194, 'Gujarat', 'Hasmukh Bhai Soma Bhai Patel', 'AHMEDABAD EAST', 147000000, 'ahmedabad_east', 'mp.ahmedabad_east@mplads-demo.local', 'ls_ahmedabad_east'),
(195, 'Uttar Pradesh', 'IMRAN MASOOD', 'SAHARANPUR', 147000000, 'saharanpur', 'mp.saharanpur@mplads-demo.local', 'ls_saharanpur'),
(196, 'Sikkim', 'Indra Hang Subba', 'SIKKIM', 152003923.11, 'sikkim', 'mp.sikkim@mplads-demo.local', 'ls_sikkim'),
(197, 'Uttar Pradesh', 'IQRA CHOUDHARY', 'KAIRANA', 147000000, 'kairana', 'mp.kairana@mplads-demo.local', 'ls_kairana'),
(198, 'West Bengal', 'ISHA KHAN CHOUDHURY', 'MALDAHA DAKSHIN', 147000000, 'maldaha_dakshin', 'mp.maldaha_dakshin@mplads-demo.local', 'ls_maldaha_dakshin'),
(199, 'West Bengal', 'JAGADISH CHANDRA BARMA BASUNIA', 'COOCHBEHAR(SC)', 168604641.11, 'coochbehar', 'mp.coochbehar@mplads-demo.local', 'ls_coochbehar'),
(200, 'Karnataka', 'JAGADISH SHETTAR', 'BELGAUM', 147000000, 'belgaum', 'mp.belgaum@mplads-demo.local', 'ls_belgaum')
ON CONFLICT (sr_no) DO UPDATE SET
  state = EXCLUDED.state,
  mp_name = EXCLUDED.mp_name,
  constituency = EXCLUDED.constituency,
  allocated_amount = EXCLUDED.allocated_amount,
  slug = EXCLUDED.slug,
  email = EXCLUDED.email,
  mp_id = EXCLUDED.mp_id;
