
INSERT INTO public.ls_mps_master (sr_no, state, mp_name, constituency, allocated_amount, slug, email, mp_id)
VALUES
(501, 'Bihar', 'Sunil Kumar', 'VALMIKI NAGAR', 147000000, 'valmiki_nagar', 'mp.valmiki_nagar@mplads-demo.local', 'ls_valmiki_nagar'),
(502, 'Bihar', 'SURENDRA PRASAD YADAV', 'JAHANABAD', 155325714, 'jahanabad', 'mp.jahanabad@mplads-demo.local', 'ls_jahanabad'),
(503, 'Kerala', 'SURESH GOPI', 'THRISSUR', 147000000, 'thrissur', 'mp.thrissur@mplads-demo.local', 'ls_thrissur'),
(504, 'Himachal Pradesh', 'Suresh Kumar Kashyap', 'SHIMLA (SC)', 153563957.11, 'shimla', 'mp.shimla@mplads-demo.local', 'ls_shimla'),
(505, 'Telangana', 'SURESH KUMAR SHETKAR', 'ZAHIRABAD', 147000000, 'zahirabad', 'mp.zahirabad@mplads-demo.local', 'ls_zahirabad'),
(506, 'Uttar Pradesh', 'Swami Sachchidanandhari Sakshi ji Maharaj', 'UNNAO', 147000000, 'unnao', 'mp.unnao@mplads-demo.local', 'ls_unnao'),
(507, 'Tamil Nadu', 'T Sumathy (A) Thamizhachi Thangapandian', 'CHENNAI SOUTH', 147000000, 'chennai_south', 'mp.chennai_south@mplads-demo.local', 'ls_chennai_south'),
(508, 'Andhra Pradesh', 'TANGELLA UDAY SRINIVAS', 'KAKINADA', 199417886.76, 'kakinada', 'mp.kakinada@mplads-demo.local', 'ls_kakinada'),
(509, 'Uttar Pradesh', 'TANUJ PUNIA', 'BARABANKI(SC)', 148198170.11, 'barabanki', 'mp.barabanki@mplads-demo.local', 'ls_barabanki'),
(510, 'Bihar', 'TARIQ ANWAR', 'KATIHAR', 147000000, 'katihar', 'mp.katihar@mplads-demo.local', 'ls_katihar'),
(511, 'Tamil Nadu', 'Thalikkottai Rajuthevar Baalu', 'SRIPERUMBUDUR', 196905535.11, 'sriperumbudur', 'mp.sriperumbudur@mplads-demo.local', 'ls_sriperumbudur'),
(512, 'Tamil Nadu', 'THANGA TAMILSELVAN', 'THENI', 167755939.81, 'theni', 'mp.theni@mplads-demo.local', 'ls_theni'),
(513, 'Tamil Nadu', 'THARANIVENTHAN M S', 'ARANI', 168337124.35, 'arani', 'mp.arani@mplads-demo.local', 'ls_arani'),
(514, 'Tamil Nadu', 'Thiru Dayanidhi Maran', 'CHENNAI CENTRAL', 147000000, 'chennai_central', 'mp.chennai_central@mplads-demo.local', 'ls_chennai_central'),
(515, 'Tamil Nadu', 'Thirumaa Valavan Thol', 'CHIDAMBARAM(SC)', 147000000, 'chidambaram', 'mp.chidambaram@mplads-demo.local', 'ls_chidambaram'),
(516, 'Chhattisgarh', 'TOKHAN SAHU', 'BILASPUR', 147000000, 'bilaspur', 'mp.bilaspur@mplads-demo.local', 'ls_bilaspur'),
(517, 'Uttarakhand', 'TRIVENDRA SINGH RAWAT', 'HARDWAR', 147000000, 'hardwar', 'mp.hardwar@mplads-demo.local', 'ls_hardwar'),
(518, 'Uttar Pradesh', 'UJJWAL RAMAN SINGH', 'ALLAHABAD', 147000000, 'allahabad', 'mp.allahabad@mplads-demo.local', 'ls_allahabad'),
(519, 'Rajasthan', 'UMMEDA RAM BENIWAL', 'BARMER', 147000000, 'barmer', 'mp.barmer@mplads-demo.local', 'ls_barmer'),
(520, 'Uttar Pradesh', 'UTKARSH VERMA MADHUR', 'KHERI', 147000000, 'kheri', 'mp.kheri@mplads-demo.local', 'ls_kheri'),
(521, 'Tamil Nadu', 'V S Matheswaran', 'NAMAKKAL', 162539930.11, 'namakkal', 'mp.namakkal@mplads-demo.local', 'ls_namakkal'),
(522, 'Karnataka', 'V. SOMANNA', 'TUMKUR', 147000000, 'tumkur', 'mp.tumkur@mplads-demo.local', 'ls_tumkur'),
(523, 'Puducherry', 'Vaithilingam Ve', 'Puducherry', 209368972.11, 'puducherry', 'mp.puducherry@mplads-demo.local', 'ls_puducherry'),
(524, 'Telangana', 'VAMSI KRISHNA GADDAM', 'PEDDAPALLE', 148451721.11, 'peddapalle', 'mp.peddapalle@mplads-demo.local', 'ls_peddapalle'),
(525, 'Haryana', 'VARUN CHAUDHRY', 'AMBALA (SC)', 255454264, 'ambala', 'mp.ambala@mplads-demo.local', 'ls_ambala'),
(526, 'Kerala', 'Vellalath Kochukrishnan Nair Sreekandan', 'PALAKKAD', 167807990.11, 'palakkad', 'mp.palakkad@mplads-demo.local', 'ls_palakkad'),
(527, 'Chhattisgarh', 'Vijay Baghel', 'DURG', 147000000, 'durg', 'mp.durg@mplads-demo.local', 'ls_durg'),
(528, 'Uttar Pradesh', 'Vijay Kumar Dubey', 'KUSHI NAGAR', 148900000, 'kushi_nagar', 'mp.kushi_nagar@mplads-demo.local', 'ls_kushi_nagar'),
(529, 'Jharkhand', 'Vijay Kumar Hansdak', 'RAJMAHAL(ST)', 147223957.11, 'rajmahal', 'mp.rajmahal@mplads-demo.local', 'ls_rajmahal'),
(530, 'Bihar', 'VIJAYLAKSHMI DEVI', 'SIWAN', 147000000, 'siwan', 'mp.siwan@mplads-demo.local', 'ls_siwan'),
(531, 'Gujarat', 'Vinod Chavda', 'KACHCHH(SC)', 147000000, 'kachchh', 'mp.kachchh@mplads-demo.local', 'ls_kachchh'),
(532, 'Uttar Pradesh', 'VINOD KUMAR BIND', 'BHADOHI', 147000000, 'bhadohi', 'mp.bhadohi@mplads-demo.local', 'ls_bhadohi'),
(533, 'Madhya Pradesh', 'Virendra Kumar', 'TIKAMGARH(SC)', 147000000, 'tikamgarh', 'mp.tikamgarh@mplads-demo.local', 'ls_tikamgarh'),
(534, 'Uttar Pradesh', 'VIRENDRA SINGH', 'CHANDAULI', 147000000, 'chandauli', 'mp.chandauli@mplads-demo.local', 'ls_chandauli'),
(535, 'Maharashtra', 'VISHAL', 'SANGLI', 147000000, 'sangli', 'mp.sangli@mplads-demo.local', 'ls_sangli'),
(536, 'Jharkhand', 'Vishnu Dayal Ram', 'PALAMU(SC)', 158176083.11, 'palamu', 'mp.palamu@mplads-demo.local', 'ls_palamu'),
(537, 'Madhya Pradesh', 'Vishnu Dutt Sharma', 'KHAJURAHO', 147000000, 'khajuraho', 'mp.khajuraho@mplads-demo.local', 'ls_khajuraho'),
(538, 'Karnataka', 'VISHWESHWAR HEGDE KAGERI', 'UTTARA KANNADA', 147000000, 'uttara_kannada', 'mp.uttara_kannada@mplads-demo.local', 'ls_uttara_kannada'),
(539, 'Bihar', 'VIVEK THAKUR', 'NAWADA', 147000000, 'nawada', 'mp.nawada@mplads-demo.local', 'ls_nawada'),
(540, 'Andhra Pradesh', 'Y S Avinash Reddy', 'KADAPA', 156430260.11, 'kadapa', 'mp.kadapa@mplads-demo.local', 'ls_kadapa'),
(541, 'Karnataka', 'YADUVEER KRISHNADATTA CHAMARAJA WADIYAR', 'MYSORE', 147000000, 'mysore', 'mp.mysore@mplads-demo.local', 'ls_mysore'),
(542, 'Delhi', 'Yogendra Chandoliya', 'NORTH WEST DELHI(SC)', 147876307, 'north_west_delhi', 'mp.north_west_delhi@mplads-demo.local', 'ls_north_west_delhi'),
(543, 'Uttar Pradesh', 'ZIA UR REHMAN', 'SAMBHAL', 147000000, 'sambhal', 'mp.sambhal@mplads-demo.local', 'ls_sambhal')
ON CONFLICT (sr_no) DO UPDATE SET
  state = EXCLUDED.state,
  mp_name = EXCLUDED.mp_name,
  constituency = EXCLUDED.constituency,
  allocated_amount = EXCLUDED.allocated_amount,
  slug = EXCLUDED.slug,
  email = EXCLUDED.email,
  mp_id = EXCLUDED.mp_id;
