
INSERT INTO public.ls_mps_master (sr_no, state, mp_name, constituency, allocated_amount, slug, email, mp_id)
VALUES
(401, 'Karnataka', 'SAGAR ESHWAR KHANDRE', 'BIDAR', 147000000, 'bidar', 'mp.bidar@mplads-demo.local', 'ls_bidar'),
(402, 'Meghalaya', 'SALENG A SANGMA', 'TURA', 147000000, 'tura', 'mp.tura@mplads-demo.local', 'ls_tura'),
(403, 'Odisha', 'SAMBIT PATRA', 'PURI', 147000000, 'puri', 'mp.puri@mplads-demo.local', 'ls_puri'),
(404, 'Uttar Pradesh', 'SANATAN PANDEY', 'BALLIA', 180420041.4, 'ballia', 'mp.ballia@mplads-demo.local', 'ls_ballia'),
(405, 'Maharashtra', 'SANJAY DINA PATIL', 'MUMBAI NORTH EAST', 147000000, 'mumbai_north_east', 'mp.mumbai_north_east@mplads-demo.local', 'ls_mumbai_north_east'),
(406, 'Maharashtra', 'Sanjay Haribhau Jadhav', 'PARBHANI', 147000000, 'parbhani', 'mp.parbhani@mplads-demo.local', 'ls_parbhani'),
(407, 'Bihar', 'Sanjay Jaiswal', 'PASCHIM CHAMPARAN', 147000000, 'paschim_champaran', 'mp.paschim_champaran@mplads-demo.local', 'ls_paschim_champaran'),
(408, 'Telangana', 'Sanjay Kumar Bandi', 'KARIMNAGAR', 172775317.11, 'karimnagar', 'mp.karimnagar@mplads-demo.local', 'ls_karimnagar'),
(409, 'Jharkhand', 'Sanjay Seth', 'RANCHI', 147064357.11, 'ranchi', 'mp.ranchi@mplads-demo.local', 'ls_ranchi'),
(410, 'Maharashtra', 'Sanjay Uttamrao Deshmukh', 'YAVATMAL-WASHIM', 185640423, 'yavatmal_washim', 'mp.yavatmal_washim@mplads-demo.local', 'ls_yavatmal_washim'),
(411, 'Rajasthan', 'SANJNA JATAV', 'BHARATPUR(SC)', 147000000, 'bharatpur', 'mp.bharatpur@mplads-demo.local', 'ls_bharatpur'),
(412, 'Chhattisgarh', 'Santosh Pandey', 'RAJNANDGAON', 147000000, 'rajnandgaon', 'mp.rajnandgaon@mplads-demo.local', 'ls_rajnandgaon'),
(413, 'Odisha', 'Saptagiri Sankar Ulaka', 'KORAPUT(ST)', 269500000, 'koraput', 'mp.koraput@mplads-demo.local', 'ls_koraput'),
(414, 'Punjab', 'SARABJEET SINGH KHALSA', 'FARIDKOT(SC)', 150850348.15, 'faridkot', 'mp.faridkot@mplads-demo.local', 'ls_faridkot'),
(415, 'Tamil Nadu', 'Sasikanth Senthil', 'TIRUVALLUR(SC)', 171500000, 'tiruvallur', 'mp.tiruvallur@mplads-demo.local', 'ls_tiruvallur'),
(416, 'Haryana', 'SATPAL BRAHAMCHARI', 'SONEPAT', 147000000, 'sonepat', 'mp.sonepat@mplads-demo.local', 'ls_sonepat'),
(417, 'West Bengal', 'Saumitra khan', 'BISHNUPUR(SC)', 147000000, 'bishnupur', 'mp.bishnupur@mplads-demo.local', 'ls_bishnupur'),
(418, 'Madhya Pradesh', 'SAVITRI THAKUR', 'DHAR(ST)', 147000000, 'dhar', 'mp.dhar@mplads-demo.local', 'ls_dhar'),
(419, 'West Bengal', 'SAYANI GHOSH', 'JADAVPUR', 147000000, 'jadavpur', 'mp.jadavpur@mplads-demo.local', 'ls_jadavpur'),
(420, 'Haryana', 'SELJA', 'SIRSA(SC)', 147000000, 'sirsa', 'mp.sirsa@mplads-demo.local', 'ls_sirsa'),
(421, 'Tamil Nadu', 'SELVAGANAPATHI T M', 'SALEM', 147000000, 'salem', 'mp.salem@mplads-demo.local', 'ls_salem'),
(422, 'Tamil Nadu', 'SELVARAJ V', 'NAGAPATTINAM(SC)', 147000000, 'nagapattinam', 'mp.nagapattinam@mplads-demo.local', 'ls_nagapattinam'),
(423, 'Kerala', 'SHAFI PARAMBIL', 'VADAKARA', 147000000, 'vadakara', 'mp.vadakara@mplads-demo.local', 'ls_vadakara'),
(424, 'Bihar', 'SHAMBHAVI', 'SAMASTIPUR(SC)', 147000000, 'samastipur', 'mp.samastipur@mplads-demo.local', 'ls_samastipur'),
(425, 'Madhya Pradesh', 'Shankar Lalwani', 'INDORE', 147000000, 'indore', 'mp.indore@mplads-demo.local', 'ls_indore'),
(426, 'Uttar Pradesh', 'SHASHANK MANI', 'DEORIA', 147000000, 'deoria', 'mp.deoria@mplads-demo.local', 'ls_deoria'),
(427, 'West Bengal', 'Shatrughan Sinha', 'ASANSOL', 147000000, 'asansol', 'mp.asansol@mplads-demo.local', 'ls_asansol'),
(428, 'Punjab', 'SHER SINGH GHUBAYA', 'FIROZPUR', 147000000, 'firozpur', 'mp.firozpur@mplads-demo.local', 'ls_firozpur'),
(429, 'Madhya Pradesh', 'SHIVMANGAL SINGH TOMAR', 'MORENA', 147000000, 'morena', 'mp.morena@mplads-demo.local', 'ls_morena'),
(430, 'Madhya Pradesh', 'SHIVRAJ SINGH CHOUHAN', 'VIDISHA', 147000000, 'vidisha', 'mp.vidisha@mplads-demo.local', 'ls_vidisha'),
(431, 'Karnataka', 'SHOBHA KARANDLAJE', 'BANGALORE NORTH', 147000000, 'bangalore_north', 'mp.bangalore_north@mplads-demo.local', 'ls_bangalore_north'),
(432, 'Gujarat', 'SHOBHANABEN MAHENDRASINH BARAIYA', 'SABARKANTHA', 147000000, 'sabarkantha', 'mp.sabarkantha@mplads-demo.local', 'ls_sabarkantha'),
(433, 'Karnataka', 'SHREYAS. M. PATEL', 'HASSAN', 147000000, 'hassan', 'mp.hassan@mplads-demo.local', 'ls_hassan'),
(434, 'Haryana', 'Shri  Dharambir Singh', 'BHIWANI MAHENDRAGARH', 147000000, 'bhiwani_mahendragarh', 'mp.bhiwani_mahendragarh@mplads-demo.local', 'ls_bhiwani_mahendragarh'),
(435, 'West Bengal', 'Shri Abhishek Banerjee', 'DIAMOND HARBOUR', 147000000, 'diamond_harbour', 'mp.diamond_harbour@mplads-demo.local', 'ls_diamond_harbour'),
(436, 'Punjab', 'Shri Amar Singh', 'FATEHGARH SAHIB(SC)', 147000000, 'fatehgarh_sahib', 'mp.fatehgarh_sahib@mplads-demo.local', 'ls_fatehgarh_sahib'),
(437, 'Gujarat', 'Shri Amit Shah', 'GANDHINAGAR', 147000000, 'gandhinagar', 'mp.gandhinagar@mplads-demo.local', 'ls_gandhinagar'),
(438, 'Madhya Pradesh', 'Shri Anil Firojiya', 'UJJAIN(SC)', 147000000, 'ujjain', 'mp.ujjain@mplads-demo.local', 'ls_ujjain'),
(439, 'Rajasthan', 'Shri Arjun Ram Meghwal', 'BIKANER(SC)', 147000000, 'bikaner', 'mp.bikaner@mplads-demo.local', 'ls_bikaner'),
(440, 'Uttar Pradesh', 'Shri Arun Kumar Sagar', 'SHAHJAHANPUR(SC)', 147000000, 'shahjahanpur', 'mp.shahjahanpur@mplads-demo.local', 'ls_shahjahanpur'),
(441, 'Karnataka', 'Shri B Y Raghavendra', 'SHIMOGA', 147000000, 'shimoga', 'mp.shimoga@mplads-demo.local', 'ls_shimoga'),
(442, 'Kerala', 'Shri Benny Behanan', 'CHALAKUDY', 164674770.11, 'chalakudy', 'mp.chalakudy@mplads-demo.local', 'ls_chalakudy'),
(443, 'Odisha', 'Shri Bhartruhari Mahtab', 'CUTTACK', 147000000, 'cuttack', 'mp.cuttack@mplads-demo.local', 'ls_cuttack'),
(444, 'Jharkhand', 'Shri Chandra Prakash Choudhary', 'GIRIDIH', 147000000, 'giridih', 'mp.giridih@mplads-demo.local', 'ls_giridih'),
(445, 'West Bengal', 'Shri Deepak (Dev) Adhikari', 'GHATAL', 200747364, 'ghatal', 'mp.ghatal@mplads-demo.local', 'ls_ghatal'),
(446, 'Punjab', 'Shri Gurjeet Singh Aujla', 'AMRITSAR', 147000000, 'amritsar', 'mp.amritsar@mplads-demo.local', 'ls_amritsar'),
(447, 'Rajasthan', 'Shri Hanuman Beniwal', 'NAGAUR', 147000000, 'nagaur', 'mp.nagaur@mplads-demo.local', 'ls_nagaur'),
(448, 'Kerala', 'Shri Hibi Eden', 'ERNAKULAM', 162177260.11, 'ernakulam', 'mp.ernakulam@mplads-demo.local', 'ls_ernakulam'),
(449, 'Bihar', 'Shri Janardan Singh Sigriwal', 'MAHARAJGANJ_BR', 147000000, 'maharajganj_br', 'mp.maharajganj_br@mplads-demo.local', 'ls_maharajganj_br'),
(450, 'Odisha', 'Shri Jual Oram', 'SUNDARGARH (ST)', 173096756.91, 'sundargarh', 'mp.sundargarh@mplads-demo.local', 'ls_sundargarh'),
(451, 'Jammu And Kashmir', 'Shri Jugal Kishore Sharma', 'JAMMU', 147000000, 'jammu', 'mp.jammu@mplads-demo.local', 'ls_jammu'),
(452, 'West Bengal', 'Shri Jyotirmay Singh Mahato', 'PURULIA', 147000000, 'purulia', 'mp.purulia@mplads-demo.local', 'ls_purulia'),
(453, 'Tamil Nadu', 'Shri Karti P Chidambaram', 'SIVAGANGA', 159049284.11, 'sivaganga', 'mp.sivaganga@mplads-demo.local', 'ls_sivaganga'),
(454, 'Kerala', 'Shri Kumbakudi Sudhakaran', 'KANNUR', 147000000, 'kannur', 'mp.kannur@mplads-demo.local', 'ls_kannur'),
(455, 'Karnataka', 'Shri LS Tejasvi Surya', 'BANGALORE SOUTH', 147000000, 'bangalore_south', 'mp.bangalore_south@mplads-demo.local', 'ls_bangalore_south'),
(456, 'Kerala', 'Shri M K Raghavan', 'KOZHIKODE', 147000000, 'kozhikode', 'mp.kozhikode@mplads-demo.local', 'ls_kozhikode'),
(457, 'Uttar Pradesh', 'Shri Narendra Modi', 'VARANASI', 162070276.11, 'varanasi', 'mp.varanasi@mplads-demo.local', 'ls_varanasi'),
(458, 'Kerala', 'Shri NK Premachandran', 'KOLLAM', 171477994.11, 'kollam', 'mp.kollam@mplads-demo.local', 'ls_kollam'),
(459, 'Rajasthan', 'Shri PP Chaudhary', 'PALI', 147000000, 'pali', 'mp.pali@mplads-demo.local', 'ls_pali'),
(460, 'Kerala', 'Shri Rajmohan Unnithan', 'KASARAGOD', 156754633.11, 'kasaragod', 'mp.kasaragod@mplads-demo.local', 'ls_kasaragod'),
(461, 'Assam', 'Shri Sarbananda Sonowal (18LS)', 'DIBRUGARH', 147000000, 'dibrugarh', 'mp.dibrugarh@mplads-demo.local', 'ls_dibrugarh'),
(462, 'Uttar Pradesh', 'Shri Satish Kumar Gautam', 'ALIGARH', 147000000, 'aligarh', 'mp.aligarh@mplads-demo.local', 'ls_aligarh'),
(463, 'West Bengal', 'Shri Shantanu Thakur', 'BANGAON(SC)', 147000000, 'bangaon', 'mp.bangaon@mplads-demo.local', 'ls_bangaon'),
(464, 'Madhya Pradesh', 'Shri Sudheer Gupta', 'MANDSOUR', 148988014.83, 'mandsour', 'mp.mandsour@mplads-demo.local', 'ls_mandsour'),
(465, 'Kerala', 'Shri Suresh Kodikunnil', 'MAVELIKKARA(SC)', 172429519.11, 'mavelikkara', 'mp.mavelikkara@mplads-demo.local', 'ls_mavelikkara'),
(466, 'Arunachal Pradesh', 'Shri Tapir Gao', 'ARUNACHAL EAST', 147000000, 'arunachal_east', 'mp.arunachal_east@mplads-demo.local', 'ls_arunachal_east'),
(467, 'Tamil Nadu', 'Shri vijayakumar Vasanth', 'KANNIYAKUMARI', 171500000, 'kanniyakumari', 'mp.kanniyakumari@mplads-demo.local', 'ls_kanniyakumari'),
(468, 'Maharashtra', 'Shrikant Eknath Shinde', 'KALYAN', 147000000, 'kalyan', 'mp.kalyan@mplads-demo.local', 'ls_kalyan'),
(469, 'Maharashtra', 'SHRIMANT CHH UDAYANRAJE PRATAPSINHAMAHARAJ BHONSLE', 'SATARA', 147000000, 'satara', 'mp.satara@mplads-demo.local', 'ls_satara'),
(470, 'Goa', 'Shripad Yesso Naik', 'NORTH GOA', 147000000, 'north_goa', 'mp.north_goa@mplads-demo.local', 'ls_north_goa'),
(471, 'Maharashtra', 'Shrirang Appa Barne', 'MAVAL', 147000000, 'maval', 'mp.maval@mplads-demo.local', 'ls_maval'),
(472, 'Maharashtra', 'Shyamkumar', 'RAMTEK(SC)', 147000000, 'ramtek', 'mp.ramtek@mplads-demo.local', 'ls_ramtek'),
(473, 'Andhra Pradesh', 'Sivanath Kesineni', 'VIJAYAWADA', 159864032.49, 'vijayawada', 'mp.vijayawada@mplads-demo.local', 'ls_vijayawada'),
(474, 'West Bengal', 'SK NURUL ISLAM', 'BASIRHAT', 49000000, 'basirhat', 'mp.basirhat@mplads-demo.local', 'ls_basirhat'),
(475, 'Maharashtra', 'SMITA UDAY WAGH', 'JALGAON', 148107373.11, 'jalgaon', 'mp.jalgaon@mplads-demo.local', 'ls_jalgaon'),
(476, 'Uttar Pradesh', 'Smt Anupriya Patel', 'MIRZAPUR', 147000000, 'mirzapur', 'mp.mirzapur@mplads-demo.local', 'ls_mirzapur'),
(477, 'Odisha', 'Smt Aparajita Sarangi', 'BHUBANESWAR', 147420861.41, 'bhubaneswar', 'mp.bhubaneswar@mplads-demo.local', 'ls_bhubaneswar'),
(478, 'Uttar Pradesh', 'Smt Dimple Yadav', 'MAINPURI', 192042469.11, 'mainpuri', 'mp.mainpuri@mplads-demo.local', 'ls_mainpuri'),
(479, 'Punjab', 'Smt Harsimrat Kaur Badal', 'BHATINDA', 159775982.39, 'bhatinda', 'mp.bhatinda@mplads-demo.local', 'ls_bhatinda'),
(480, 'Uttar Pradesh', 'Smt Hema Malini', 'MATHURA', 147000000, 'mathura', 'mp.mathura@mplads-demo.local', 'ls_mathura'),
(481, 'Madhya Pradesh', 'Smt Himadri Singh', 'SHAHDOL (ST)', 150724861.11, 'shahdol', 'mp.shahdol@mplads-demo.local', 'ls_shahdol'),
(482, 'Gujarat', 'Smt Poonamben Hematbhai Maadam', 'JAMNAGAR', 147000000, 'jamnagar', 'mp.jamnagar@mplads-demo.local', 'ls_jamnagar'),
(483, 'Maharashtra', 'Smt Raksha Nikhil Khadse', 'RAVER', 153112586.11, 'raver', 'mp.raver@mplads-demo.local', 'ls_raver'),
(484, 'Tamil Nadu', 'Smt S Jothimani', 'KARUR', 147000000, 'karur', 'mp.karur@mplads-demo.local', 'ls_karur'),
(485, 'West Bengal', 'Smt Sajda Ahmed', 'ULUBERIA', 147000000, 'uluberia', 'mp.uluberia@mplads-demo.local', 'ls_uluberia'),
(486, 'Madhya Pradesh', 'Smt Sandhya Ray', 'BHIND(SC)', 147000000, 'bhind', 'mp.bhind@mplads-demo.local', 'ls_bhind'),
(487, 'Odisha', 'Smt Sangeeta Kumari Singh Deo', 'BOLANGIR', 147000000, 'bolangir', 'mp.bolangir@mplads-demo.local', 'ls_bolangir'),
(488, 'West Bengal', 'Smt Satabdi Roy (Banerjee)', 'BIRBHUM', 147000000, 'birbhum', 'mp.birbhum@mplads-demo.local', 'ls_birbhum'),
(489, 'Maharashtra', 'Smt Supriya Sadanand Sule', 'BARAMATI', 147000000, 'baramati', 'mp.baramati@mplads-demo.local', 'ls_baramati'),
(490, 'Bihar', 'Smt Veena Devi', 'VAISHALI', 147000000, 'vaishali', 'mp.vaishali@mplads-demo.local', 'ls_vaishali'),
(491, 'Andhra Pradesh', 'Sribharat MathuKumli', 'VISAKHAPATNAM', 164841922, 'visakhapatnam', 'mp.visakhapatnam@mplads-demo.local', 'ls_visakhapatnam'),
(492, 'Bihar', 'SUDAMA PRASAD', 'ARRAH', 147000000, 'arrah', 'mp.arrah@mplads-demo.local', 'ls_arrah'),
(493, 'Tamil Nadu', 'SUDHA R', 'MAYILADUTHURAI', 147332315.11, 'mayiladuthurai', 'mp.mayiladuthurai@mplads-demo.local', 'ls_mayiladuthurai'),
(494, 'Bihar', 'SUDHAKAR SINGH', 'BUXAR', 185211956.54, 'buxar', 'mp.buxar@mplads-demo.local', 'ls_buxar'),
(495, 'West Bengal', 'Sudip Bandyopadhyay', 'KOLKATA UTTAR', 147000000, 'kolkata_uttar', 'mp.kolkata_uttar@mplads-demo.local', 'ls_kolkata_uttar'),
(496, 'Odisha', 'SUKANTA KUMAR PANIGRAHI', 'KANDHAMAL', 190712424.11, 'kandhamal', 'mp.kandhamal@mplads-demo.local', 'ls_kandhamal'),
(497, 'Jharkhand', 'SUKHDEO BHAGAT', 'LOHARDAGA(ST)', 171821957.11, 'lohardaga', 'mp.lohardaga@mplads-demo.local', 'ls_lohardaga'),
(498, 'Punjab', 'SUKHJINDER SINGH RANDHAWA', 'GURDASPUR', 147000000, 'gurdaspur', 'mp.gurdaspur@mplads-demo.local', 'ls_gurdaspur'),
(499, 'Karnataka', 'SUNIL BOSE', 'CHAMARAJANAGAR(SC)', 147000000, 'chamarajanagar', 'mp.chamarajanagar@mplads-demo.local', 'ls_chamarajanagar'),
(500, 'Maharashtra', 'Sunil Dattatray Tatkare', 'RAIGAD', 147000000, 'raigad', 'mp.raigad@mplads-demo.local', 'ls_raigad')
ON CONFLICT (sr_no) DO UPDATE SET
  state = EXCLUDED.state,
  mp_name = EXCLUDED.mp_name,
  constituency = EXCLUDED.constituency,
  allocated_amount = EXCLUDED.allocated_amount,
  slug = EXCLUDED.slug,
  email = EXCLUDED.email,
  mp_id = EXCLUDED.mp_id;
