
INSERT INTO public.ls_mps_master (sr_no, state, mp_name, constituency, allocated_amount, slug, email, mp_id)
VALUES
(301, 'Tamil Nadu', 'MURASOLI S', 'THANJAVUR', 147000000, 'thanjavur', 'mp.thanjavur@mplads-demo.local', 'ls_thanjavur'),
(302, 'Maharashtra', 'MURLIDHAR MOHOL', 'PUNE', 147000000, 'pune', 'mp.pune@mplads-demo.local', 'ls_pune'),
(303, 'Odisha', 'NABA CHARAN MAJHI', 'MAYURBHANJ (ST)', 147563957.11, 'mayurbhanj', 'mp.mayurbhanj@mplads-demo.local', 'ls_mayurbhanj'),
(304, 'Jharkhand', 'NALIN SOREN', 'DUMKA(ST)', 147364097.11, 'dumka', 'mp.dumka@mplads-demo.local', 'ls_dumka'),
(305, 'Uttar Pradesh', 'NARAYAN DAS AHIRWAR', 'JALAUN(SC)', 147000000, 'jalaun', 'mp.jalaun@mplads-demo.local', 'ls_jalaun'),
(306, 'Maharashtra', 'NARAYAN TATU RANE', 'RATNAGIRI-SINDHUDURG', 147000000, 'ratnagiri_sindhudurg', 'mp.ratnagiri_sindhudurg@mplads-demo.local', 'ls_ratnagiri_sindhudurg'),
(307, 'Uttar Pradesh', 'NARESH CHANDRA UTTAM PATEL', 'FATEHPUR', 147000000, 'fatehpur', 'mp.fatehpur@mplads-demo.local', 'ls_fatehpur'),
(308, 'Maharashtra', 'NARESH GANPAT MHASKE', 'THANE', 147000000, 'thane', 'mp.thane@mplads-demo.local', 'ls_thane'),
(309, 'Haryana', 'NAVEEN JINDAL', 'KURUKSHETRA', 147000000, 'kurukshetra', 'mp.kurukshetra@mplads-demo.local', 'ls_kurukshetra'),
(310, 'Uttar Pradesh', 'NEERAJ MAURYA', 'AONLA', 147000000, 'aonla', 'mp.aonla@mplads-demo.local', 'ls_aonla'),
(311, 'Maharashtra', 'NILESH DNYANDEV LANKE', 'AHMEDNAGAR', 147000000, 'ahmednagar', 'mp.ahmednagar@mplads-demo.local', 'ls_ahmednagar'),
(312, 'Gujarat', 'NIMUBEN JAYANTIBHAI BAMBHANIYA', 'BHAVNAGAR', 147000000, 'bhavnagar', 'mp.bhavnagar@mplads-demo.local', 'ls_bhavnagar'),
(313, 'Jharkhand', 'Nishikant Dubey', 'GODDA', 147000000, 'godda', 'mp.godda@mplads-demo.local', 'ls_godda'),
(314, 'Maharashtra', 'Nitin Jairam Gadkari', 'NAGPUR', 168195086.11, 'nagpur', 'mp.nagpur@mplads-demo.local', 'ls_nagpur'),
(315, 'Bihar', 'Nityanand Rai', 'UJJARPUR', 147000000, 'ujjarpur', 'mp.ujjarpur@mplads-demo.local', 'ls_ujjarpur'),
(316, 'Rajasthan', 'Om Birla', 'KOTA', 163906956.6, 'kota', 'mp.kota@mplads-demo.local', 'ls_kota'),
(317, 'Maharashtra', 'Omprakash Bhupalsinh Alias Pawan Rajenimbalkar', 'OSMANABAD', 184758519.11, 'osmanabad', 'mp.osmanabad@mplads-demo.local', 'ls_osmanabad'),
(318, 'Karnataka', 'P C Mohan', 'BANGALORE CENTRAL', 159995711.11, 'bangalore_central', 'mp.bangalore_central@mplads-demo.local', 'ls_bangalore_central'),
(319, 'Uttar Pradesh', 'Pankaj Chowdhary', 'MAHARAJGANJ_UP', 147000000, 'maharajganj_up', 'mp.maharajganj_up@mplads-demo.local', 'ls_maharajganj_up'),
(320, 'Assam', 'PARIMAL SUKLABAIDYA', 'SILCHAR', 148300157.11, 'silchar', 'mp.silchar@mplads-demo.local', 'ls_silchar'),
(321, 'Gujarat', 'PARSHOTTAMBHAI RUPALA', 'RAJKOT', 147000000, 'rajkot', 'mp.rajkot@mplads-demo.local', 'ls_rajkot'),
(322, 'West Bengal', 'PARTHA BHOWMICK', 'BARRACKPUR', 147000000, 'barrackpur', 'mp.barrackpur@mplads-demo.local', 'ls_barrackpur'),
(323, 'Karnataka', 'Parvatagouda Chandanagouda Gaddigoudar', 'BAGALKOT', 167541747.11, 'bagalkot', 'mp.bagalkot@mplads-demo.local', 'ls_bagalkot'),
(324, 'The Dadra And Nagar Haveli And Daman And Diu', 'PATEL UMESHBHAI BABUBHAI', 'DAMAN and DIU', 245063957, 'daman_and_diu', 'mp.daman_and_diu@mplads-demo.local', 'ls_daman_and_diu'),
(325, 'West Bengal', 'PATHAN YUSUF', 'BAHARAMPUR', 147000000, 'baharampur', 'mp.baharampur@mplads-demo.local', 'ls_baharampur'),
(326, 'Assam', 'PHANI BHUSAN CHOUDHURY', 'BARPETA', 147000000, 'barpeta', 'mp.barpeta@mplads-demo.local', 'ls_barpeta'),
(327, 'Maharashtra', 'Piyush Vedprakash Goyal', 'MUMBAI NORTH', 147000000, 'mumbai_north', 'mp.mumbai_north@mplads-demo.local', 'ls_mumbai_north'),
(328, 'Andhra Pradesh', 'PRABHAKAR REDDY VEMIREDDY', 'NELLORE(SC)', 147000000, 'nellore', 'mp.nellore@mplads-demo.local', 'ls_nellore'),
(329, 'Gujarat', 'Prabhubhai Nagarbhai Vasava', 'BARDOLI(ST)', 147000000, 'bardoli', 'mp.bardoli@mplads-demo.local', 'ls_bardoli'),
(330, 'Assam', 'Pradan Baruah', 'LAKHIMPUR', 147000000, 'lakhimpur', 'mp.lakhimpur@mplads-demo.local', 'ls_lakhimpur'),
(331, 'Bihar', 'Pradeep Kumar Singh', 'ARARIA', 147000000, 'araria', 'mp.araria@mplads-demo.local', 'ls_araria'),
(332, 'Odisha', 'PRADEEP PUROHIT', 'BARGARH', 147000000, 'bargarh', 'mp.bargarh@mplads-demo.local', 'ls_bargarh'),
(333, 'Assam', 'Pradyut Bordoloi', 'NOWGONG', 98000000, 'nowgong', 'mp.nowgong@mplads-demo.local', 'ls_nowgong'),
(334, 'Karnataka', 'Pralhad Venkatesh Joshi', 'DHARWAD', 147000000, 'dharwad', 'mp.dharwad@mplads-demo.local', 'ls_dharwad'),
(335, 'Maharashtra', 'PRANITI SUSHILKUMAR SHINDE', 'SOLAPUR(SC)', 147000000, 'solapur', 'mp.solapur@mplads-demo.local', 'ls_solapur'),
(336, 'West Bengal', 'Prasun Banerjee', 'HOWRAH', 147000000, 'howrah', 'mp.howrah@mplads-demo.local', 'ls_howrah'),
(337, 'Odisha', 'Pratap Chandra Sarangi', 'BALASORE', 147064254.11, 'balasore', 'mp.balasore@mplads-demo.local', 'ls_balasore'),
(338, 'Maharashtra', 'Prataprao Jadhav', 'BULDHANA', 147000000, 'buldhana', 'mp.buldhana@mplads-demo.local', 'ls_buldhana'),
(339, 'West Bengal', 'Pratima Mondal', 'JOYNAGAR(SC)', 147000000, 'joynagar', 'mp.joynagar@mplads-demo.local', 'ls_joynagar'),
(340, 'Delhi', 'Praveen Khandelwal', 'CHANDINI CHOWK', 147470276, 'chandini_chowk', 'mp.chandini_chowk@mplads-demo.local', 'ls_chandini_chowk'),
(341, 'Uttar Pradesh', 'PRAVEEN PATEL', 'PHULPUR', 151559884.09, 'phulpur', 'mp.phulpur@mplads-demo.local', 'ls_phulpur'),
(342, 'Uttar Pradesh', 'PRIYA SAROJ', 'MACHHLISHAHR(SC)', 147000000, 'machhlishahr', 'mp.machhlishahr@mplads-demo.local', 'ls_machhlishahr'),
(343, 'Kerala', 'Priyanka Gandhi Vadra', 'WAYANAD', 122500000, 'wayanad', 'mp.wayanad@mplads-demo.local', 'ls_wayanad'),
(344, 'Karnataka', 'PRIYANKA SATISH JARKIHOLI', 'CHIKKODI', 147000000, 'chikkodi', 'mp.chikkodi@mplads-demo.local', 'ls_chikkodi'),
(345, 'West Bengal', 'Prof Sougata Ray', 'DUM DUM', 147000000, 'dum_dum', 'mp.dum_dum@mplads-demo.local', 'ls_dum_dum'),
(346, 'Uttar Pradesh', 'Prof SP Singh Baghel', 'AGRA(SC)', 147000000, 'agra', 'mp.agra@mplads-demo.local', 'ls_agra'),
(347, 'Uttar Pradesh', 'PUSHPENDRA SAROJ', 'KAUSHAMBI(SC)', 147000000, 'kaushambi', 'mp.kaushambi@mplads-demo.local', 'ls_kaushambi'),
(348, 'Andhra Pradesh', 'Putta Mahesh Kumar', 'ELURU', 147000000, 'eluru', 'mp.eluru@mplads-demo.local', 'ls_eluru'),
(349, 'Uttar Pradesh', 'R.K. CHAUDHARY', 'MOHANLALGANJ(SC)', 147000000, 'mohanlalganj', 'mp.mohanlalganj@mplads-demo.local', 'ls_mohanlalganj'),
(350, 'Odisha', 'RABINDRA NARAYAN BEHERA', 'JAJPUR(SC)', 147064617.11, 'jajpur', 'mp.jajpur@mplads-demo.local', 'ls_jajpur'),
(351, 'West Bengal', 'RACHNA BANERJEE', 'HOOGHLY', 147000000, 'hooghly', 'mp.hooghly@mplads-demo.local', 'ls_hooghly'),
(352, 'Bihar', 'Radha Mohan Singh', 'PURVI CHAMPARAN', 147000000, 'purvi_champaran', 'mp.purvi_champaran@mplads-demo.local', 'ls_purvi_champaran'),
(353, 'Karnataka', 'RADHAKRISHNA', 'GULBARGA(SC)', 147000000, 'gulbarga', 'mp.gulbarga@mplads-demo.local', 'ls_gulbarga'),
(354, 'Chhattisgarh', 'RADHE SHYAM RATHIYA', 'RAIGARH(ST)', 159706972.09, 'raigarh', 'mp.raigarh@mplads-demo.local', 'ls_raigarh'),
(355, 'Uttar Pradesh', 'RAHUL GANDHI', 'RAE BARELI', 147000000, 'rae_bareli', 'mp.rae_bareli@mplads-demo.local', 'ls_rae_bareli'),
(356, 'Rajasthan', 'Rahul Kaswan', 'CHURU', 147000000, 'churu', 'mp.churu@mplads-demo.local', 'ls_churu'),
(357, 'Madhya Pradesh', 'RAHUL SINGH LODHI', 'DAMOH', 163058785.37, 'damoh', 'mp.damoh@mplads-demo.local', 'ls_damoh'),
(358, 'Bihar', 'RAJ BHUSHAN CHOUDHARY', 'MUZAFFARPUR', 147000000, 'muzaffarpur', 'mp.muzaffarpur@mplads-demo.local', 'ls_muzaffarpur'),
(359, 'Rajasthan', 'RAJ KUMAR ROAT', 'BANSWARA(ST)', 147000000, 'banswara', 'mp.banswara@mplads-demo.local', 'ls_banswara'),
(360, 'Bihar', 'RAJA RAM SINGH', 'KARAKAT', 147000000, 'karakat', 'mp.karakat@mplads-demo.local', 'ls_karakat'),
(361, 'Maharashtra', 'RAJABHAU', 'NASHIK', 152878682.11, 'nashik', 'mp.nashik@mplads-demo.local', 'ls_nashik'),
(362, 'Himachal Pradesh', 'RAJEEV BHARDWAJ', 'KANGRA', 179388967.11, 'kangra', 'mp.kangra@mplads-demo.local', 'ls_kangra'),
(363, 'Uttar Pradesh', 'RAJEEV RAI', 'GHOSI', 147000000, 'ghosi', 'mp.ghosi@mplads-demo.local', 'ls_ghosi'),
(364, 'Bihar', 'RAJESH RANJAN ALIAS PAPPU YADAV', 'PURNEA', 147000000, 'purnea', 'mp.purnea@mplads-demo.local', 'ls_purnea'),
(365, 'Bihar', 'RAJESH VERMA', 'KHAGARIA', 147000000, 'khagaria', 'mp.khagaria@mplads-demo.local', 'ls_khagaria'),
(366, 'Gujarat', 'Rajeshbhai Naranbhai Chudasama', 'JUNAGADH', 147000000, 'junagadh', 'mp.junagadh@mplads-demo.local', 'ls_junagadh'),
(367, 'Bihar', 'Rajiv Pratap Rudy', 'SARAN', 147000000, 'saran', 'mp.saran@mplads-demo.local', 'ls_saran'),
(368, 'Bihar', 'Rajiv Ranjan (Lalan) Singh', 'MUNGER', 147000000, 'munger', 'mp.munger@mplads-demo.local', 'ls_munger'),
(369, 'Uttar Pradesh', 'Rajkumar Chahar', 'FATEHPUR SIKRI', 147000000, 'fatehpur_sikri', 'mp.fatehpur_sikri@mplads-demo.local', 'ls_fatehpur_sikri'),
(370, 'Uttar Pradesh', 'Rajnath Singh', 'LUCKNOW', 154808797.11, 'lucknow', 'mp.lucknow@mplads-demo.local', 'ls_lucknow'),
(371, 'Gujarat', 'RAJPALSINH MAHENDRASINH JADAV', 'PANCHMAHAL', 147000000, 'panchmahal', 'mp.panchmahal@mplads-demo.local', 'ls_panchmahal'),
(372, 'West Bengal', 'Raju Bista', 'DARJEELING', 147000000, 'darjeeling', 'mp.darjeeling@mplads-demo.local', 'ls_darjeeling'),
(373, 'Uttar Pradesh', 'RAKESH RATHOR', 'SITAPUR', 147000000, 'sitapur', 'mp.sitapur@mplads-demo.local', 'ls_sitapur'),
(374, 'Assam', 'RAKIBUL HUSSAIN', 'DHUBRI', 147000000, 'dhubri', 'mp.dhubri@mplads-demo.local', 'ls_dhubri'),
(375, 'Uttar Pradesh', 'RAM PRASAD CHAUDHARY', 'BASTI', 204176957.11, 'basti', 'mp.basti@mplads-demo.local', 'ls_basti'),
(376, 'Uttar Pradesh', 'Ram Shiromani', 'SHRAWASTI', 151746878.11, 'shrawasti', 'mp.shrawasti@mplads-demo.local', 'ls_shrawasti'),
(377, 'Telangana', 'RAMASAHAYAM RAGHURAM REDDY', 'KHAMMAM', 147000000, 'khammam', 'mp.khammam@mplads-demo.local', 'ls_khammam'),
(378, 'Uttar Pradesh', 'RAMASHANKAR RAJBHAR', 'SALEMPUR', 160056927.07, 'salempur', 'mp.salempur@mplads-demo.local', 'ls_salempur'),
(379, 'Uttar Pradesh', 'RAMBHUAL NISHAD', 'SULTANPUR', 151231957.11, 'sultanpur', 'mp.sultanpur@mplads-demo.local', 'ls_sultanpur'),
(380, 'Uttar Pradesh', 'RAMESH AWASTHI', 'KANPUR', 147000000, 'kanpur', 'mp.kanpur@mplads-demo.local', 'ls_kanpur'),
(381, 'Karnataka', 'Ramesh Chandappa Jigajinagi', 'BIJAPUR(SC)', 269500000, 'bijapur', 'mp.bijapur@mplads-demo.local', 'ls_bijapur'),
(382, 'Bihar', 'Ramprit Mandal', 'JHANJHARPUR', 147000000, 'jhanjharpur', 'mp.jhanjharpur@mplads-demo.local', 'ls_jhanjharpur'),
(383, 'Delhi', 'Ramvir Singh Bidhuri', 'SOUTH DELHI', 147559100, 'south_delhi', 'mp.south_delhi@mplads-demo.local', 'ls_south_delhi'),
(384, 'Assam', 'RANJIT DUTTA', 'Sonitpur', 147000000, 'sonitpur', 'mp.sonitpur@mplads-demo.local', 'ls_sonitpur'),
(385, 'Haryana', 'Rao Inderjit Singh', 'GURGAON', 147000000, 'gurgaon', 'mp.gurgaon@mplads-demo.local', 'ls_gurgaon'),
(386, 'Rajasthan', 'Rao Rajendra Singh', 'JAIPUR RURAL', 147000000, 'jaipur_rural', 'mp.jaipur_rural@mplads-demo.local', 'ls_jaipur_rural'),
(387, 'Bihar', 'Ravi Shankar Prasad', 'PATNA SAHIB', 147000000, 'patna_sahib', 'mp.patna_sahib@mplads-demo.local', 'ls_patna_sahib'),
(388, 'Maharashtra', 'RAVINDRA DATTARAM WAIKAR', 'MUMBAI NORTH WEST', 147000000, 'mumbai_north_west', 'mp.mumbai_north_west@mplads-demo.local', 'ls_mumbai_north_west'),
(389, 'Uttar Pradesh', 'Ravindra Shyamnarayan Alias Ravi Kishan Shukla', 'GORAKHPUR', 147000000, 'gorakhpur', 'mp.gorakhpur@mplads-demo.local', 'ls_gorakhpur'),
(390, 'Maharashtra', 'Ravindra Vasantrao Chavan', 'NANDED', 147000000, 'nanded_maharashtra', 'mp.nanded_maharashtra@mplads-demo.local', 'ls_nanded_maharashtra'),
(391, 'Mizoram', 'RICHARD VANLALHMANGAIHA', 'MIZORAM (ST)', 147000000, 'mizoram', 'mp.mizoram@mplads-demo.local', 'ls_mizoram'),
(392, 'Tamil Nadu', 'ROBERT BRUCE C', 'TIRUNELVELI', 147475440.11, 'tirunelveli', 'mp.tirunelveli@mplads-demo.local', 'ls_tirunelveli'),
(393, 'Madhya Pradesh', 'Rodmal Nagar', 'RAJGARH', 147000000, 'rajgarh', 'mp.rajgarh@mplads-demo.local', 'ls_rajgarh'),
(394, 'Chhattisgarh', 'ROOP KUMARI CHOUDHARY', 'MAHASAMUND', 153035414, 'mahasamund', 'mp.mahasamund@mplads-demo.local', 'ls_mahasamund'),
(395, 'Uttar Pradesh', 'RUCHI VIRA', 'MORADABAD', 147000000, 'moradabad', 'mp.moradabad@mplads-demo.local', 'ls_moradabad'),
(396, 'Odisha', 'RUDRA NARAYAN PANY', 'DHENKANAL', 155013957.11, 'dhenkanal', 'mp.dhenkanal@mplads-demo.local', 'ls_dhenkanal'),
(397, 'Nagaland', 'S SUPONGMEREN JAMIR', 'NAGALAND', 147000000, 'nagaland', 'mp.nagaland@mplads-demo.local', 'ls_nagaland'),
(398, 'Tamil Nadu', 'S Venkatesan', 'MADURAI', 147000000, 'madurai', 'mp.madurai@mplads-demo.local', 'ls_madurai'),
(399, 'Tamil Nadu', 'S. Jagathrakshakan', 'ARAKKONAM', 180589332.34, 'arakkonam', 'mp.arakkonam@mplads-demo.local', 'ls_arakkonam'),
(400, 'Tamil Nadu', 'SACHITHANANTHAM R', 'DINDIGUL', 147000000, 'dindigul', 'mp.dindigul@mplads-demo.local', 'ls_dindigul')
ON CONFLICT (sr_no) DO UPDATE SET
  state = EXCLUDED.state,
  mp_name = EXCLUDED.mp_name,
  constituency = EXCLUDED.constituency,
  allocated_amount = EXCLUDED.allocated_amount,
  slug = EXCLUDED.slug,
  email = EXCLUDED.email,
  mp_id = EXCLUDED.mp_id;
