
INSERT INTO public.ls_mps_master (sr_no, state, mp_name, constituency, allocated_amount, slug, email, mp_id)
VALUES
(1, 'Maharashtra', 'AASHTIKAR PATIL NAGESH BAPURAO', 'HINGOLI', 190289442, 'hingoli', 'mp.hingoli@mplads-demo.local', 'ls_hingoli'),
(2, 'Jammu And Kashmir', 'ABDUL RASHID SHEIKH', 'BARAMULLAH', 154773472.11, 'baramullah', 'mp.baramullah@mplads-demo.local', 'ls_baramullah'),
(3, 'Bihar', 'ABHAY KUMAR SINHA', 'AURANGABAD_BR', 147000000, 'aurangabad_br', 'mp.aurangabad_br@mplads-demo.local', 'ls_aurangabad_br'),
(4, 'West Bengal', 'ABHIJIT GANGOPADHYAY', 'TAMLUK', 147000000, 'tamluk', 'mp.tamluk@mplads-demo.local', 'ls_tamluk'),
(5, 'West Bengal', 'Abu Taher Khan', 'MURSHIDABAD', 147000000, 'murshidabad', 'mp.murshidabad@mplads-demo.local', 'ls_murshidabad'),
(6, 'West Bengal', 'ADHIKARI SOUMENDU', 'KANTHI', 147000000, 'kanthi', 'mp.kanthi@mplads-demo.local', 'ls_kanthi'),
(7, 'Uttar Pradesh', 'ADITYA YADAV', 'BADAUN', 147000000, 'badaun', 'mp.badaun@mplads-demo.local', 'ls_badaun'),
(8, 'Kerala', 'Adv Adoor Prakash', 'ATTINGAL', 147000000, 'attingal', 'mp.attingal@mplads-demo.local', 'ls_attingal'),
(9, 'Kerala', 'Adv Dean Kuriakose', 'IDUKKI', 147000000, 'idukki', 'mp.idukki@mplads-demo.local', 'ls_idukki'),
(10, 'Maharashtra', 'ADV GOWAAL KAGADA PADAVI', 'NANDURBAR(ST)', 147816309.11, 'nandurbar', 'mp.nandurbar@mplads-demo.local', 'ls_nandurbar'),
(11, 'Kerala', 'ADV K FRANCIS GEORGE', 'KOTTAYAM', 188722256.11, 'kottayam', 'mp.kottayam@mplads-demo.local', 'ls_kottayam'),
(12, 'Uttar Pradesh', 'AFZAL ANSARI', 'GHAZIPUR', 220500000, 'ghazipur', 'mp.ghazipur@mplads-demo.local', 'ls_ghazipur'),
(13, 'Jammu And Kashmir', 'AGA SYED RUHULLAH MEHDI', 'SRINAGAR', 147000000, 'srinagar', 'mp.srinagar@mplads-demo.local', 'ls_srinagar'),
(14, 'Uttarakhand', 'Ajay Bhatt', 'NAINITAL UDHAM SINGH NAG.', 147000000, 'nainital_udham_singh_nag', 'mp.nainital_udham_singh_nag@mplads-demo.local', 'ls_nainital_udham_singh_nag'),
(15, 'Bihar', 'Ajay Kumar Mandal', 'BHAGALPUR', 147000000, 'bhagalpur', 'mp.bhagalpur@mplads-demo.local', 'ls_bhagalpur'),
(16, 'Uttarakhand', 'Ajay Tamta', 'ALMORA(SC)', 147000000, 'almora', 'mp.almora@mplads-demo.local', 'ls_almora'),
(17, 'Uttar Pradesh', 'AJENDRA SINGH LODHI', 'HAMIRPUR_UP', 147000000, 'hamirpur_up', 'mp.hamirpur_up@mplads-demo.local', 'ls_hamirpur_up'),
(18, 'Uttar Pradesh', 'AKHILESH YADAV', 'KANNAUJ', 147000000, 'kannauj', 'mp.kannauj@mplads-demo.local', 'ls_kannauj'),
(19, 'Uttar Pradesh', 'AKSHAYA YADAV', 'FIROZABAD', 147000000, 'firozabad', 'mp.firozabad@mplads-demo.local', 'ls_firozabad'),
(20, 'Manipur', 'ALFRED KANNGAM S ARTHUR', 'OUTER MANIPUR(ST)', 147000000, 'outer_manipur', 'mp.outer_manipur@mplads-demo.local', 'ls_outer_manipur'),
(21, 'Bihar', 'Alok Kumar Suman', 'GOPALGANJ (SC)', 147000000, 'gopalganj', 'mp.gopalganj@mplads-demo.local', 'ls_gopalganj'),
(22, 'Madhya Pradesh', 'ALOK SHARMA', 'BHOPAL', 147000000, 'bhopal', 'mp.bhopal@mplads-demo.local', 'ls_bhopal'),
(23, 'Maharashtra', 'AMAR SHARADRAO KALE', 'WARDHA', 147000000, 'wardha', 'mp.wardha@mplads-demo.local', 'ls_wardha'),
(24, 'Assam', 'AMARSING TISSO', 'Diphu (ST)', 147000000, 'diphu', 'mp.diphu@mplads-demo.local', 'ls_diphu'),
(25, 'Andhra Pradesh', 'AMBICA G LAKSHMINARAYANA VALMIKI', 'ANANTAPUR', 201899064.11, 'anantapur', 'mp.anantapur@mplads-demo.local', 'ls_anantapur'),
(26, 'Maharashtra', 'Amol Ramsing Kolhe', 'SHIRUR', 147000000, 'shirur', 'mp.shirur@mplads-demo.local', 'ls_shirur'),
(27, 'Rajasthan', 'AMRARAM', 'SIKAR', 165691544.11, 'sikar', 'mp.sikar@mplads-demo.local', 'ls_sikar'),
(28, 'Punjab', 'AMRINDER SINGH RAJA WARRING', 'LUDHIANA', 147000000, 'ludhiana', 'mp.ludhiana@mplads-demo.local', 'ls_ludhiana'),
(29, 'Uttar Pradesh', 'ANAND BHADAURIYA', 'DHAURAHRA', 147000000, 'dhaurahra', 'mp.dhaurahra@mplads-demo.local', 'ls_dhaurahra'),
(30, 'Uttar Pradesh', 'ANAND KUMAR', 'BAHRAICH(SC)', 147000000, 'bahraich', 'mp.bahraich@mplads-demo.local', 'ls_bahraich'),
(31, 'Odisha', 'ANANTA NAYAK', 'KEONJHAR(ST)', 147000000, 'keonjhar', 'mp.keonjhar@mplads-demo.local', 'ls_keonjhar'),
(32, 'Tamil Nadu', 'Andimuthu Raja', 'NILGIRIS(SC)', 147000000, 'nilgiris', 'mp.nilgiris@mplads-demo.local', 'ls_nilgiris'),
(33, 'Meghalaya', 'ANDREW J. SYNGKON', 'SHILLONG', 98000000, 'shillong', 'mp.shillong@mplads-demo.local', 'ls_shillong'),
(34, 'Manipur', 'ANGOMCHA BIMOL AKOIJAM', 'INNER MANIPUR', 147000000, 'inner_manipur', 'mp.inner_manipur@mplads-demo.local', 'ls_inner_manipur'),
(35, 'Uttarakhand', 'ANIL BALUNI', 'GARHWAL', 147000000, 'garhwal', 'mp.garhwal@mplads-demo.local', 'ls_garhwal'),
(36, 'Maharashtra', 'ANIL YESHWANT DESAI', 'MUMBAI SOUTH CENTRAL', 147000000, 'mumbai_south_central', 'mp.mumbai_south_central@mplads-demo.local', 'ls_mumbai_south_central'),
(37, 'Madhya Pradesh', 'ANITA NAGARSINGH CHOUHAN', 'RATLAM(ST)', 147000000, 'ratlam', 'mp.ratlam@mplads-demo.local', 'ls_ratlam'),
(38, 'Odisha', 'ANITA SUBHADARSHINI', 'ASKA', 147000000, 'aska', 'mp.aska@mplads-demo.local', 'ls_aska'),
(39, 'Jharkhand', 'Annpurna Devi', 'KODARMA', 166665931.8, 'kodarma', 'mp.kodarma@mplads-demo.local', 'ls_kodarma'),
(40, 'Uttar Pradesh', 'ANOOP PRADHAN BALMIKI', 'HATHRAS (SC)', 147000000, 'hathras', 'mp.hathras@mplads-demo.local', 'ls_hathras'),
(41, 'Kerala', 'Anto Antony', 'PATHANAMTHITTA', 147000000, 'pathanamthitta', 'mp.pathanamthitta@mplads-demo.local', 'ls_pathanamthitta'),
(42, 'Maharashtra', 'ANUP SANJAY DHOTRE', 'AKOLA', 147000000, 'akola', 'mp.akola@mplads-demo.local', 'ls_akola'),
(43, 'Uttar Pradesh', 'Anurag Sharma', 'JHANSI', 147000000, 'jhansi', 'mp.jhansi@mplads-demo.local', 'ls_jhansi'),
(44, 'Himachal Pradesh', 'Anurag Singh Thakur', 'HAMIRPUR_HP', 149570117.11, 'hamirpur_hp', 'mp.hamirpur_hp@mplads-demo.local', 'ls_hamirpur_hp'),
(45, 'Andhra Pradesh', 'Appalanaidu Kalisetti', 'VIZIANAGARAM', 147000000, 'vizianagaram', 'mp.vizianagaram@mplads-demo.local', 'ls_vizianagaram'),
(46, 'Bihar', 'ARUN BHARTI', 'JAMUI(SC)', 194924621.11, 'jamui', 'mp.jamui@mplads-demo.local', 'ls_jamui'),
(47, 'Uttar Pradesh', 'ARUN GOVIL', 'MEERUT', 147000000, 'meerut', 'mp.meerut@mplads-demo.local', 'ls_meerut'),
(48, 'Tamil Nadu', 'ARUN NEHRU', 'PERAMBALUR', 147000000, 'perambalur', 'mp.perambalur@mplads-demo.local', 'ls_perambalur'),
(49, 'Telangana', 'ARUNA. D. K', 'MAHABUBNAGAR', 147000000, 'mahabubnagar', 'mp.mahabubnagar@mplads-demo.local', 'ls_mahabubnagar'),
(50, 'West Bengal', 'ARUP CHAKRABORTY', 'BANKURA', 147000000, 'bankura', 'mp.bankura@mplads-demo.local', 'ls_bankura'),
(51, 'Telangana', 'Arvind Dharmapuri', 'NIZAMABAD', 281396355.11, 'nizamabad', 'mp.nizamabad@mplads-demo.local', 'ls_nizamabad'),
(52, 'Maharashtra', 'Arvind Ganpat Sawant', 'MUMBAI SOUTH', 147000000, 'mumbai_south', 'mp.mumbai_south@mplads-demo.local', 'ls_mumbai_south'),
(53, 'Telangana', 'Asaduddin Owaisi', 'HYDERABAD', 147000000, 'hyderabad', 'mp.hyderabad@mplads-demo.local', 'ls_hyderabad'),
(54, 'Madhya Pradesh', 'ASHISH DUBEY', 'JABALPUR', 147000000, 'jabalpur', 'mp.jabalpur@mplads-demo.local', 'ls_jabalpur'),
(55, 'Uttar Pradesh', 'Ashok Kumar Rawat', 'MISRIKH(SC)', 147000000, 'misrikh', 'mp.misrikh@mplads-demo.local', 'ls_misrikh'),
(56, 'Bihar', 'Ashok Kumar Yadav', 'MADHUBANI', 147000000, 'madhubani', 'mp.madhubani@mplads-demo.local', 'ls_madhubani'),
(57, 'West Bengal', 'Asit Kumar Mal', 'BOLPUR(SC)', 275694456.74, 'bolpur', 'mp.bolpur@mplads-demo.local', 'ls_bolpur'),
(58, 'Uttar Pradesh', 'ATUL GARG', 'GHAZIABAD', 155336470, 'ghaziabad', 'mp.ghaziabad@mplads-demo.local', 'ls_ghaziabad'),
(59, 'Odisha', 'AVIMANYU SETHI', 'BHADRAK(SC)', 147000000, 'bhadrak', 'mp.bhadrak@mplads-demo.local', 'ls_bhadrak'),
(60, 'Uttar Pradesh', 'AWADHESH PRASAD', 'FAIZABAD', 147000000, 'faizabad', 'mp.faizabad@mplads-demo.local', 'ls_faizabad'),
(61, 'West Bengal', 'AZAD KIRTI JHA', 'BARDHAMAN-DURGAPUR', 179658399.98, 'bardhaman_durgapur', 'mp.bardhaman_durgapur@mplads-demo.local', 'ls_bardhaman_durgapur'),
(62, 'Andhra Pradesh', 'B K PARTHASARATHI', 'HINDUPUR', 160491894.11, 'hindupur', 'mp.hindupur@mplads-demo.local', 'ls_hindupur'),
(63, 'Uttar Pradesh', 'BABU SINGH KUSHWAHA', 'JAUNPUR', 147000000, 'jaunpur', 'mp.jaunpur@mplads-demo.local', 'ls_jaunpur'),
(64, 'Maharashtra', 'BACHHAV SHOBHA DINESH', 'DHULE', 147000000, 'dhule', 'mp.dhule@mplads-demo.local', 'ls_dhule'),
(65, 'West Bengal', 'BAG MITALI', 'ARAMBAG(SC)', 147000000, 'arambag', 'mp.arambag@mplads-demo.local', 'ls_arambag'),
(66, 'Odisha', 'BAIJAYANT PANDA', 'KENDRAPARA', 147000000, 'kendrapara', 'mp.kendrapara@mplads-demo.local', 'ls_kendrapara'),
(67, 'Maharashtra', 'BAJRANG MANOHAR SONWANE', 'BEED', 165899107.19, 'beed', 'mp.beed@mplads-demo.local', 'ls_beed'),
(68, 'Odisha', 'BALABHADRA MAJHI', 'NABARANGPUR(ST)', 147413962.11, 'nabarangpur', 'mp.nabarangpur@mplads-demo.local', 'ls_nabarangpur'),
(69, 'Andhra Pradesh', 'Balashowry Vallabbhaneni', 'MACHILIPATNAM', 147000000, 'machilipatnam', 'mp.machilipatnam@mplads-demo.local', 'ls_machilipatnam'),
(70, 'Telangana', 'BALRAM NAIK PORIKA', 'MAHABUBABAD', 147000000, 'mahabubabad', 'mp.mahabubabad@mplads-demo.local', 'ls_mahabubabad'),
(71, 'Maharashtra', 'BALWANT BASWANT WANKHADE', 'AMRAVATI(SC)', 198293678, 'amravati', 'mp.amravati@mplads-demo.local', 'ls_amravati'),
(72, 'Maharashtra', 'BALYA MAMA SURESH GOPINATH MHATRE', 'BHIWANDI', 147000000, 'bhiwandi', 'mp.bhiwandi@mplads-demo.local', 'ls_bhiwandi'),
(73, 'Delhi', 'Bansuri Swaraj', 'NEW DELHI', 154306950, 'new_delhi', 'mp.new_delhi@mplads-demo.local', 'ls_new_delhi'),
(74, 'West Bengal', 'BAPI HALDAR', 'MATHURAPUR(SC)', 147000000, 'mathurapur', 'mp.mathurapur@mplads-demo.local', 'ls_mathurapur'),
(75, 'Karnataka', 'BASAVARAJ BOMMAI', 'HAVERI', 147000000, 'haveri', 'mp.haveri@mplads-demo.local', 'ls_haveri'),
(76, 'Andhra Pradesh', 'BASTIPATI NAGARAJU PANCHALINGALA', 'KURNOOL', 159998515.11, 'kurnool', 'mp.kurnool@mplads-demo.local', 'ls_kurnool'),
(77, 'Rajasthan', 'Bhagirath Chaudhary', 'AJMER', 147000000, 'ajmer', 'mp.ajmer@mplads-demo.local', 'ls_ajmer'),
(78, 'Rajasthan', 'BHAJAN LAL JATAV', 'KARAULI-DHOLPUR(SC)', 147000000, 'karauli_dholpur', 'mp.karauli_dholpur@mplads-demo.local', 'ls_karauli_dholpur'),
(79, 'Madhya Pradesh', 'BHARAT SINGH KUSHWAH', 'GWALIOR', 151455276.04, 'gwalior', 'mp.gwalior@mplads-demo.local', 'ls_gwalior'),
(80, 'Gujarat', 'BHARATBHAI MANUBHAI SUTARIYA', 'AMRELI', 147000000, 'amreli', 'mp.amreli@mplads-demo.local', 'ls_amreli'),
(81, 'Gujarat', 'Bharatsinhji Shankarji Dabhi', 'PATAN', 147000000, 'patan', 'mp.patan@mplads-demo.local', 'ls_patan'),
(82, 'Madhya Pradesh', 'BHARTI PARDHI', 'BALAGHAT', 154398389.01, 'balaghat', 'mp.balaghat@mplads-demo.local', 'ls_balaghat'),
(83, 'Maharashtra', 'BHASKAR MURLIDHAR BHAGARE', 'DINDORI(ST)', 147000000, 'dindori', 'mp.dindori@mplads-demo.local', 'ls_dindori'),
(84, 'Maharashtra', 'BHAUSAHEB RAJARAM WAKCHAURE', 'SHIRDI(SC)', 147000000, 'shirdi', 'mp.shirdi@mplads-demo.local', 'ls_shirdi'),
(85, 'Chhattisgarh', 'BHOJRAJ NAG', 'KANKER(ST)', 164672734.11, 'kanker', 'mp.kanker@mplads-demo.local', 'ls_kanker'),
(86, 'Uttar Pradesh', 'Bhola Singh', 'BULANDSHAHR(SC)', 147000000, 'bulandshahr', 'mp.bulandshahr@mplads-demo.local', 'ls_bulandshahr'),
(87, 'Maharashtra', 'BHUMARE SANDIPANRAO ASARAM', 'AURANGABAD_MH', 147000000, 'aurangabad_mh', 'mp.aurangabad_mh@mplads-demo.local', 'ls_aurangabad_mh'),
(88, 'Andhra Pradesh', 'Bhupathiraju Srinivasa varma', 'NARASAPURAM', 147000000, 'narasapuram', 'mp.narasapuram@mplads-demo.local', 'ls_narasapuram'),
(89, 'Rajasthan', 'BHUPENDER YADAV', 'ALWAR', 147000000, 'alwar', 'mp.alwar@mplads-demo.local', 'ls_alwar'),
(90, 'Odisha', 'BIBHU PRASAD TARAI', 'JAGATSINGHPUR(SC)', 147000000, 'jagatsinghpur', 'mp.jagatsinghpur@mplads-demo.local', 'ls_jagatsinghpur'),
(91, 'Jharkhand', 'Bidyut Baran Mahato', 'JAMSHEDPUR', 147000000, 'jamshedpur', 'mp.jamshedpur@mplads-demo.local', 'ls_jamshedpur'),
(92, 'Assam', 'BIJULI KALITA MEDHI', 'GUWAHATI', 147000000, 'guwahati', 'mp.guwahati@mplads-demo.local', 'ls_guwahati'),
(93, 'Tripura', 'BIPLAB KUMAR DEB', 'TRIPURA WEST', 147000000, 'tripura_west', 'mp.tripura_west@mplads-demo.local', 'ls_tripura_west'),
(94, 'Andaman And Nicobar Islands', 'BISHNU PADA RAY', 'ANDAMAN AND NICOBAR ISLANDS', 147000000, 'andaman_and_nicobar_islands', 'mp.andaman_and_nicobar_islands@mplads-demo.local', 'ls_andaman_and_nicobar_islands'),
(95, 'Rajasthan', 'BRIJENDRA SINGH OLA', 'JHUNJHUNU', 147000000, 'jhunjhunu', 'mp.jhunjhunu@mplads-demo.local', 'ls_jhunjhunu'),
(96, 'Chhattisgarh', 'BRIJMOHAN AGRAWAL', 'RAIPUR', 153766451.11, 'raipur', 'mp.raipur@mplads-demo.local', 'ls_raipur'),
(97, 'Madhya Pradesh', 'BUNTY VIVEK SAHU', 'CHHINDWARA', 147000000, 'chhindwara', 'mp.chhindwara@mplads-demo.local', 'ls_chhindwara'),
(98, 'Gujarat', 'C R Patil', 'NAVSARI', 158532494.36, 'navsari', 'mp.navsari@mplads-demo.local', 'ls_navsari'),
(99, 'Andhra Pradesh', 'C.M.RAMESH', 'ANAKAPALLE', 202531656.11, 'anakapalle', 'mp.anakapalle@mplads-demo.local', 'ls_anakapalle'),
(100, 'Karnataka', 'CAPTAIN BRIJESH CHOWTA', 'DAKSHINA KANNADA', 147000000, 'dakshina_kannada', 'mp.dakshina_kannada@mplads-demo.local', 'ls_dakshina_kannada')
ON CONFLICT (sr_no) DO UPDATE SET
  state = EXCLUDED.state,
  mp_name = EXCLUDED.mp_name,
  constituency = EXCLUDED.constituency,
  allocated_amount = EXCLUDED.allocated_amount,
  slug = EXCLUDED.slug,
  email = EXCLUDED.email,
  mp_id = EXCLUDED.mp_id;
