
-- 1. Create temporary table for 543 Lok Sabha MPs
CREATE TEMP TABLE tmp_ls_mps (
  sr_no INT,
  state TEXT,
  mp_name TEXT,
  constituency TEXT,
  slug TEXT,
  email TEXT,
  mp_id TEXT
);

INSERT INTO tmp_ls_mps (sr_no, state, mp_name, constituency, slug, email, mp_id)
VALUES
(1, 'Maharashtra', 'AASHTIKAR PATIL NAGESH BAPURAO', 'HINGOLI', 'hingoli', 'mp.hingoli@mplads-demo.local', 'ls_hingoli'),
(2, 'Jammu And Kashmir', 'ABDUL RASHID SHEIKH', 'BARAMULLAH', 'baramullah', 'mp.baramullah@mplads-demo.local', 'ls_baramullah'),
(3, 'Bihar', 'ABHAY KUMAR SINHA', 'AURANGABAD_BR', 'aurangabad_br', 'mp.aurangabad_br@mplads-demo.local', 'ls_aurangabad_br'),
(4, 'West Bengal', 'ABHIJIT GANGOPADHYAY', 'TAMLUK', 'tamluk', 'mp.tamluk@mplads-demo.local', 'ls_tamluk'),
(5, 'West Bengal', 'Abu Taher Khan', 'MURSHIDABAD', 'murshidabad', 'mp.murshidabad@mplads-demo.local', 'ls_murshidabad'),
(6, 'West Bengal', 'ADHIKARI SOUMENDU', 'KANTHI', 'kanthi', 'mp.kanthi@mplads-demo.local', 'ls_kanthi'),
(7, 'Uttar Pradesh', 'ADITYA YADAV', 'BADAUN', 'badaun', 'mp.badaun@mplads-demo.local', 'ls_badaun'),
(8, 'Kerala', 'Adv Adoor Prakash', 'ATTINGAL', 'attingal', 'mp.attingal@mplads-demo.local', 'ls_attingal'),
(9, 'Kerala', 'Adv Dean Kuriakose', 'IDUKKI', 'idukki', 'mp.idukki@mplads-demo.local', 'ls_idukki'),
(10, 'Maharashtra', 'ADV GOWAAL KAGADA PADAVI', 'NANDURBAR(ST)', 'nandurbar', 'mp.nandurbar@mplads-demo.local', 'ls_nandurbar'),
(11, 'Kerala', 'ADV K FRANCIS GEORGE', 'KOTTAYAM', 'kottayam', 'mp.kottayam@mplads-demo.local', 'ls_kottayam'),
(12, 'Uttar Pradesh', 'AFZAL ANSARI', 'GHAZIPUR', 'ghazipur', 'mp.ghazipur@mplads-demo.local', 'ls_ghazipur'),
(13, 'Jammu And Kashmir', 'AGA SYED RUHULLAH MEHDI', 'SRINAGAR', 'srinagar', 'mp.srinagar@mplads-demo.local', 'ls_srinagar'),
(14, 'Uttarakhand', 'Ajay Bhatt', 'NAINITAL UDHAM SINGH NAG.', 'nainital_udham_singh_nag', 'mp.nainital_udham_singh_nag@mplads-demo.local', 'ls_nainital_udham_singh_nag'),
(15, 'Bihar', 'Ajay Kumar Mandal', 'BHAGALPUR', 'bhagalpur', 'mp.bhagalpur@mplads-demo.local', 'ls_bhagalpur'),
(16, 'Uttarakhand', 'Ajay Tamta', 'ALMORA(SC)', 'almora', 'mp.almora@mplads-demo.local', 'ls_almora'),
(17, 'Uttar Pradesh', 'AJENDRA SINGH LODHI', 'HAMIRPUR_UP', 'hamirpur_up', 'mp.hamirpur_up@mplads-demo.local', 'ls_hamirpur_up'),
(18, 'Uttar Pradesh', 'AKHILESH YADAV', 'KANNAUJ', 'kannauj', 'mp.kannauj@mplads-demo.local', 'ls_kannauj'),
(19, 'Uttar Pradesh', 'AKSHAYA YADAV', 'FIROZABAD', 'firozabad', 'mp.firozabad@mplads-demo.local', 'ls_firozabad'),
(20, 'Manipur', 'ALFRED KANNGAM S ARTHUR', 'OUTER MANIPUR(ST)', 'outer_manipur', 'mp.outer_manipur@mplads-demo.local', 'ls_outer_manipur'),
(21, 'Bihar', 'Alok Kumar Suman', 'GOPALGANJ (SC)', 'gopalganj', 'mp.gopalganj@mplads-demo.local', 'ls_gopalganj'),
(22, 'Madhya Pradesh', 'ALOK SHARMA', 'BHOPAL', 'bhopal', 'mp.bhopal@mplads-demo.local', 'ls_bhopal'),
(23, 'Maharashtra', 'AMAR SHARADRAO KALE', 'WARDHA', 'wardha', 'mp.wardha@mplads-demo.local', 'ls_wardha'),
(24, 'Assam', 'AMARSING TISSO', 'Diphu (ST)', 'diphu', 'mp.diphu@mplads-demo.local', 'ls_diphu'),
(25, 'Andhra Pradesh', 'AMBICA G LAKSHMINARAYANA VALMIKI', 'ANANTAPUR', 'anantapur', 'mp.anantapur@mplads-demo.local', 'ls_anantapur'),
(26, 'Maharashtra', 'Amol Ramsing Kolhe', 'SHIRUR', 'shirur', 'mp.shirur@mplads-demo.local', 'ls_shirur'),
(27, 'Rajasthan', 'AMRARAM', 'SIKAR', 'sikar', 'mp.sikar@mplads-demo.local', 'ls_sikar'),
(28, 'Punjab', 'AMRINDER SINGH RAJA WARRING', 'LUDHIANA', 'ludhiana', 'mp.ludhiana@mplads-demo.local', 'ls_ludhiana'),
(29, 'Uttar Pradesh', 'ANAND BHADAURIYA', 'DHAURAHRA', 'dhaurahra', 'mp.dhaurahra@mplads-demo.local', 'ls_dhaurahra'),
(30, 'Uttar Pradesh', 'ANAND KUMAR', 'BAHRAICH(SC)', 'bahraich', 'mp.bahraich@mplads-demo.local', 'ls_bahraich'),
(31, 'Odisha', 'ANANTA NAYAK', 'KEONJHAR(ST)', 'keonjhar', 'mp.keonjhar@mplads-demo.local', 'ls_keonjhar'),
(32, 'Tamil Nadu', 'Andimuthu Raja', 'NILGIRIS(SC)', 'nilgiris', 'mp.nilgiris@mplads-demo.local', 'ls_nilgiris'),
(33, 'Meghalaya', 'ANDREW J. SYNGKON', 'SHILLONG', 'shillong', 'mp.shillong@mplads-demo.local', 'ls_shillong'),
(34, 'Manipur', 'ANGOMCHA BIMOL AKOIJAM', 'INNER MANIPUR', 'inner_manipur', 'mp.inner_manipur@mplads-demo.local', 'ls_inner_manipur'),
(35, 'Uttarakhand', 'ANIL BALUNI', 'GARHWAL', 'garhwal', 'mp.garhwal@mplads-demo.local', 'ls_garhwal'),
(36, 'Maharashtra', 'ANIL YESHWANT DESAI', 'MUMBAI SOUTH CENTRAL', 'mumbai_south_central', 'mp.mumbai_south_central@mplads-demo.local', 'ls_mumbai_south_central'),
(37, 'Madhya Pradesh', 'ANITA NAGARSINGH CHOUHAN', 'RATLAM(ST)', 'ratlam', 'mp.ratlam@mplads-demo.local', 'ls_ratlam'),
(38, 'Odisha', 'ANITA SUBHADARSHINI', 'ASKA', 'aska', 'mp.aska@mplads-demo.local', 'ls_aska'),
(39, 'Jharkhand', 'Annpurna Devi', 'KODARMA', 'kodarma', 'mp.kodarma@mplads-demo.local', 'ls_kodarma'),
(40, 'Uttar Pradesh', 'ANOOP PRADHAN BALMIKI', 'HATHRAS (SC)', 'hathras', 'mp.hathras@mplads-demo.local', 'ls_hathras'),
(41, 'Kerala', 'Anto Antony', 'PATHANAMTHITTA', 'pathanamthitta', 'mp.pathanamthitta@mplads-demo.local', 'ls_pathanamthitta'),
(42, 'Maharashtra', 'ANUP SANJAY DHOTRE', 'AKOLA', 'akola', 'mp.akola@mplads-demo.local', 'ls_akola'),
(43, 'Uttar Pradesh', 'Anurag Sharma', 'JHANSI', 'jhansi', 'mp.jhansi@mplads-demo.local', 'ls_jhansi'),
(44, 'Himachal Pradesh', 'Anurag Singh Thakur', 'HAMIRPUR_HP', 'hamirpur_hp', 'mp.hamirpur_hp@mplads-demo.local', 'ls_hamirpur_hp'),
(45, 'Andhra Pradesh', 'Appalanaidu Kalisetti', 'VIZIANAGARAM', 'vizianagaram', 'mp.vizianagaram@mplads-demo.local', 'ls_vizianagaram'),
(46, 'Bihar', 'ARUN BHARTI', 'JAMUI(SC)', 'jamui', 'mp.jamui@mplads-demo.local', 'ls_jamui'),
(47, 'Uttar Pradesh', 'ARUN GOVIL', 'MEERUT', 'meerut', 'mp.meerut@mplads-demo.local', 'ls_meerut'),
(48, 'Tamil Nadu', 'ARUN NEHRU', 'PERAMBALUR', 'perambalur', 'mp.perambalur@mplads-demo.local', 'ls_perambalur'),
(49, 'Telangana', 'ARUNA. D. K', 'MAHABUBNAGAR', 'mahabubnagar', 'mp.mahabubnagar@mplads-demo.local', 'ls_mahabubnagar'),
(50, 'West Bengal', 'ARUP CHAKRABORTY', 'BANKURA', 'bankura', 'mp.bankura@mplads-demo.local', 'ls_bankura'),
(51, 'Telangana', 'Arvind Dharmapuri', 'NIZAMABAD', 'nizamabad', 'mp.nizamabad@mplads-demo.local', 'ls_nizamabad'),
(52, 'Maharashtra', 'Arvind Ganpat Sawant', 'MUMBAI SOUTH', 'mumbai_south', 'mp.mumbai_south@mplads-demo.local', 'ls_mumbai_south'),
(53, 'Telangana', 'Asaduddin Owaisi', 'HYDERABAD', 'hyderabad', 'mp.hyderabad@mplads-demo.local', 'ls_hyderabad'),
(54, 'Madhya Pradesh', 'ASHISH DUBEY', 'JABALPUR', 'jabalpur', 'mp.jabalpur@mplads-demo.local', 'ls_jabalpur'),
(55, 'Uttar Pradesh', 'Ashok Kumar Rawat', 'MISRIKH(SC)', 'misrikh', 'mp.misrikh@mplads-demo.local', 'ls_misrikh'),
(56, 'Bihar', 'Ashok Kumar Yadav', 'MADHUBANI', 'madhubani', 'mp.madhubani@mplads-demo.local', 'ls_madhubani'),
(57, 'West Bengal', 'Asit Kumar Mal', 'BOLPUR(SC)', 'bolpur', 'mp.bolpur@mplads-demo.local', 'ls_bolpur'),
(58, 'Uttar Pradesh', 'ATUL GARG', 'GHAZIABAD', 'ghaziabad', 'mp.ghaziabad@mplads-demo.local', 'ls_ghaziabad'),
(59, 'Odisha', 'AVIMANYU SETHI', 'BHADRAK(SC)', 'bhadrak', 'mp.bhadrak@mplads-demo.local', 'ls_bhadrak'),
(60, 'Uttar Pradesh', 'AWADHESH PRASAD', 'FAIZABAD', 'faizabad', 'mp.faizabad@mplads-demo.local', 'ls_faizabad'),
(61, 'West Bengal', 'AZAD KIRTI JHA', 'BARDHAMAN-DURGAPUR', 'bardhaman_durgapur', 'mp.bardhaman_durgapur@mplads-demo.local', 'ls_bardhaman_durgapur'),
(62, 'Andhra Pradesh', 'B K PARTHASARATHI', 'HINDUPUR', 'hindupur', 'mp.hindupur@mplads-demo.local', 'ls_hindupur'),
(63, 'Uttar Pradesh', 'BABU SINGH KUSHWAHA', 'JAUNPUR', 'jaunpur', 'mp.jaunpur@mplads-demo.local', 'ls_jaunpur'),
(64, 'Maharashtra', 'BACHHAV SHOBHA DINESH', 'DHULE', 'dhule', 'mp.dhule@mplads-demo.local', 'ls_dhule'),
(65, 'West Bengal', 'BAG MITALI', 'ARAMBAG(SC)', 'arambag', 'mp.arambag@mplads-demo.local', 'ls_arambag'),
(66, 'Odisha', 'BAIJAYANT PANDA', 'KENDRAPARA', 'kendrapara', 'mp.kendrapara@mplads-demo.local', 'ls_kendrapara'),
(67, 'Maharashtra', 'BAJRANG MANOHAR SONWANE', 'BEED', 'beed', 'mp.beed@mplads-demo.local', 'ls_beed'),
(68, 'Odisha', 'BALABHADRA MAJHI', 'NABARANGPUR(ST)', 'nabarangpur', 'mp.nabarangpur@mplads-demo.local', 'ls_nabarangpur'),
(69, 'Andhra Pradesh', 'Balashowry Vallabbhaneni', 'MACHILIPATNAM', 'machilipatnam', 'mp.machilipatnam@mplads-demo.local', 'ls_machilipatnam'),
(70, 'Telangana', 'BALRAM NAIK PORIKA', 'MAHABUBABAD', 'mahabubabad', 'mp.mahabubabad@mplads-demo.local', 'ls_mahabubabad'),
(71, 'Maharashtra', 'BALWANT BASWANT WANKHADE', 'AMRAVATI(SC)', 'amravati', 'mp.amravati@mplads-demo.local', 'ls_amravati'),
(72, 'Maharashtra', 'BALYA MAMA SURESH GOPINATH MHATRE', 'BHIWANDI', 'bhiwandi', 'mp.bhiwandi@mplads-demo.local', 'ls_bhiwandi'),
(73, 'Delhi', 'Bansuri Swaraj', 'NEW DELHI', 'new_delhi', 'mp.new_delhi@mplads-demo.local', 'ls_new_delhi'),
(74, 'West Bengal', 'BAPI HALDAR', 'MATHURAPUR(SC)', 'mathurapur', 'mp.mathurapur@mplads-demo.local', 'ls_mathurapur'),
(75, 'Karnataka', 'BASAVARAJ BOMMAI', 'HAVERI', 'haveri', 'mp.haveri@mplads-demo.local', 'ls_haveri'),
(76, 'Andhra Pradesh', 'BASTIPATI NAGARAJU PANCHALINGALA', 'KURNOOL', 'kurnool', 'mp.kurnool@mplads-demo.local', 'ls_kurnool'),
(77, 'Rajasthan', 'Bhagirath Chaudhary', 'AJMER', 'ajmer', 'mp.ajmer@mplads-demo.local', 'ls_ajmer'),
(78, 'Rajasthan', 'BHAJAN LAL JATAV', 'KARAULI-DHOLPUR(SC)', 'karauli_dholpur', 'mp.karauli_dholpur@mplads-demo.local', 'ls_karauli_dholpur'),
(79, 'Madhya Pradesh', 'BHARAT SINGH KUSHWAH', 'GWALIOR', 'gwalior', 'mp.gwalior@mplads-demo.local', 'ls_gwalior'),
(80, 'Gujarat', 'BHARATBHAI MANUBHAI SUTARIYA', 'AMRELI', 'amreli', 'mp.amreli@mplads-demo.local', 'ls_amreli'),
(81, 'Gujarat', 'Bharatsinhji Shankarji Dabhi', 'PATAN', 'patan', 'mp.patan@mplads-demo.local', 'ls_patan'),
(82, 'Madhya Pradesh', 'BHARTI PARDHI', 'BALAGHAT', 'balaghat', 'mp.balaghat@mplads-demo.local', 'ls_balaghat'),
(83, 'Maharashtra', 'BHASKAR MURLIDHAR BHAGARE', 'DINDORI(ST)', 'dindori', 'mp.dindori@mplads-demo.local', 'ls_dindori'),
(84, 'Maharashtra', 'BHAUSAHEB RAJARAM WAKCHAURE', 'SHIRDI(SC)', 'shirdi', 'mp.shirdi@mplads-demo.local', 'ls_shirdi'),
(85, 'Chhattisgarh', 'BHOJRAJ NAG', 'KANKER(ST)', 'kanker', 'mp.kanker@mplads-demo.local', 'ls_kanker'),
(86, 'Uttar Pradesh', 'Bhola Singh', 'BULANDSHAHR(SC)', 'bulandshahr', 'mp.bulandshahr@mplads-demo.local', 'ls_bulandshahr'),
(87, 'Maharashtra', 'BHUMARE SANDIPANRAO ASARAM', 'AURANGABAD_MH', 'aurangabad_mh', 'mp.aurangabad_mh@mplads-demo.local', 'ls_aurangabad_mh'),
(88, 'Andhra Pradesh', 'Bhupathiraju Srinivasa varma', 'NARASAPURAM', 'narasapuram', 'mp.narasapuram@mplads-demo.local', 'ls_narasapuram'),
(89, 'Rajasthan', 'BHUPENDER YADAV', 'ALWAR', 'alwar', 'mp.alwar@mplads-demo.local', 'ls_alwar'),
(90, 'Odisha', 'BIBHU PRASAD TARAI', 'JAGATSINGHPUR(SC)', 'jagatsinghpur', 'mp.jagatsinghpur@mplads-demo.local', 'ls_jagatsinghpur'),
(91, 'Jharkhand', 'Bidyut Baran Mahato', 'JAMSHEDPUR', 'jamshedpur', 'mp.jamshedpur@mplads-demo.local', 'ls_jamshedpur'),
(92, 'Assam', 'BIJULI KALITA MEDHI', 'GUWAHATI', 'guwahati', 'mp.guwahati@mplads-demo.local', 'ls_guwahati'),
(93, 'Tripura', 'BIPLAB KUMAR DEB', 'TRIPURA WEST', 'tripura_west', 'mp.tripura_west@mplads-demo.local', 'ls_tripura_west'),
(94, 'Andaman And Nicobar Islands', 'BISHNU PADA RAY', 'ANDAMAN AND NICOBAR ISLANDS', 'andaman_and_nicobar_islands', 'mp.andaman_and_nicobar_islands@mplads-demo.local', 'ls_andaman_and_nicobar_islands'),
(95, 'Rajasthan', 'BRIJENDRA SINGH OLA', 'JHUNJHUNU', 'jhunjhunu', 'mp.jhunjhunu@mplads-demo.local', 'ls_jhunjhunu'),
(96, 'Chhattisgarh', 'BRIJMOHAN AGRAWAL', 'RAIPUR', 'raipur', 'mp.raipur@mplads-demo.local', 'ls_raipur'),
(97, 'Madhya Pradesh', 'BUNTY VIVEK SAHU', 'CHHINDWARA', 'chhindwara', 'mp.chhindwara@mplads-demo.local', 'ls_chhindwara'),
(98, 'Gujarat', 'C R Patil', 'NAVSARI', 'navsari', 'mp.navsari@mplads-demo.local', 'ls_navsari'),
(99, 'Andhra Pradesh', 'C.M.RAMESH', 'ANAKAPALLE', 'anakapalle', 'mp.anakapalle@mplads-demo.local', 'ls_anakapalle'),
(100, 'Karnataka', 'CAPTAIN BRIJESH CHOWTA', 'DAKSHINA KANNADA', 'dakshina_kannada', 'mp.dakshina_kannada@mplads-demo.local', 'ls_dakshina_kannada'),
(101, 'Goa', 'CAPTAIN VIRIATO FERNANDES', 'SOUTH GOA', 'south_goa', 'mp.south_goa@mplads-demo.local', 'ls_south_goa'),
(102, 'Telangana', 'CHAMALA KIRAN KUMAR REDDY', 'BHONGIR', 'bhongir', 'mp.bhongir@mplads-demo.local', 'ls_bhongir'),
(103, 'Uttar Pradesh', 'CHANDAN CHAUHAN', 'BIJNOR', 'bijnor', 'mp.bijnor@mplads-demo.local', 'ls_bijnor'),
(104, 'Rajasthan', 'Chandra Prakash Joshi', 'CHITTORGARH', 'chittorgarh', 'mp.chittorgarh@mplads-demo.local', 'ls_chittorgarh'),
(105, 'Uttar Pradesh', 'CHANDRA SHEKHAR', 'NAGINA(SC)', 'nagina', 'mp.nagina@mplads-demo.local', 'ls_nagina'),
(106, 'Gujarat', 'CHANDUBHAI CHHAGANBHAI SHIHORA', 'SURENDRANAGAR', 'surendranagar', 'mp.surendranagar@mplads-demo.local', 'ls_surendranagar'),
(107, 'Punjab', 'CHARANJIT SINGH CHANNI', 'JALANDHAR(SC)', 'jalandhar', 'mp.jalandhar@mplads-demo.local', 'ls_jalandhar'),
(108, 'Maharashtra', 'CHAVAN VASANTRAO BALWANTRAO', 'NANDED', 'nanded', 'mp.nanded@mplads-demo.local', 'ls_nanded'),
(109, 'Uttar Pradesh', 'CHHATRA PAL SINGH GANGWAR', 'BAREILLY', 'bareilly', 'mp.bareilly@mplads-demo.local', 'ls_bareilly'),
(110, 'Maharashtra', 'CHHATRAPATI SHAHU SHAHAJI', 'KOLHAPUR', 'kolhapur', 'mp.kolhapur@mplads-demo.local', 'ls_kolhapur'),
(111, 'Uttar Pradesh', 'CHHOTELAL', 'ROBERTSGANJ(SC)', 'robertsganj', 'mp.robertsganj@mplads-demo.local', 'ls_robertsganj'),
(112, 'Chhattisgarh', 'CHINTAMANI MAHARAJ', 'SARGUJA(ST)', 'sarguja', 'mp.sarguja@mplads-demo.local', 'ls_sarguja'),
(113, 'Bihar', 'CHIRAG PASWAN', 'HAJIPUR(SC)', 'hajipur', 'mp.hajipur@mplads-demo.local', 'ls_hajipur'),
(114, 'Tamil Nadu', 'CN Annadurai', 'TIRUVANNAMALAI', 'tiruvannamalai', 'mp.tiruvannamalai@mplads-demo.local', 'ls_tiruvannamalai'),
(115, 'Tamil Nadu', 'D M Kathir Anand', 'VELLORE', 'vellore', 'mp.vellore@mplads-demo.local', 'ls_vellore'),
(116, 'Tamil Nadu', 'D Ravikumar', 'VILUPPURAM(SC)', 'viluppuram', 'mp.viluppuram@mplads-demo.local', 'ls_viluppuram'),
(117, 'Andhra Pradesh', 'Daggubati Purandeshwari', 'RAJAHMUNDRY', 'rajahmundry', 'mp.rajahmundry@mplads-demo.local', 'ls_rajahmundry'),
(118, 'Andhra Pradesh', 'DAGGUMALLA PRASADA RAO', 'CHITTOOR', 'chittoor', 'mp.chittoor@mplads-demo.local', 'ls_chittoor'),
(119, 'Rajasthan', 'DAMODAR AGARWAL', 'BHILWARA', 'bhilwara', 'mp.bhilwara@mplads-demo.local', 'ls_bhilwara'),
(120, 'Uttar Pradesh', 'DAROGA PRASAD SAROJ', 'LALGANJ (SC)', 'lalganj', 'mp.lalganj@mplads-demo.local', 'ls_lalganj'),
(121, 'Madhya Pradesh', 'DARSHAN SINGH CHOUDHARY', 'HOSHANGABAD', 'hoshangabad', 'mp.hoshangabad@mplads-demo.local', 'ls_hoshangabad'),
(122, 'Haryana', 'DEEPENDER SINGH HOODA', 'ROHTAK', 'rohtak', 'mp.rohtak@mplads-demo.local', 'ls_rohtak'),
(123, 'Uttar Pradesh', 'Devendra Alias Bhole Singh', 'AKBARPUR', 'akbarpur', 'mp.akbarpur@mplads-demo.local', 'ls_akbarpur'),
(124, 'Bihar', 'DEVESH CHANDRA THAKUR', 'SITAMARHI', 'sitamarhi', 'mp.sitamarhi@mplads-demo.local', 'ls_sitamarhi'),
(125, 'Uttar Pradesh', 'DEVESH SHAKYA', 'ETAH', 'etah', 'mp.etah@mplads-demo.local', 'ls_etah'),
(126, 'Gujarat', 'Devusinh Jesingbhai Chauhan', 'KHEDA', 'kheda', 'mp.kheda@mplads-demo.local', 'ls_kheda'),
(127, 'Maharashtra', 'Dhairyasheel Sambhajirao Mane', 'HATKANANGLE', 'hatkanangle', 'mp.hatkanangle@mplads-demo.local', 'ls_hatkanangle'),
(128, 'Maharashtra', 'DHANORKAR PRATIBHA SURESH ALIAS BALUBHAU', 'CHANDRAPUR', 'chandrapur', 'mp.chandrapur@mplads-demo.local', 'ls_chandrapur'),
(129, 'Odisha', 'DHARMENDRA PRADHAN', 'SAMBALPUR', 'sambalpur', 'mp.sambalpur@mplads-demo.local', 'ls_sambalpur'),
(130, 'Uttar Pradesh', 'DHARMENDRA YADAV', 'AZAMGARH', 'azamgarh', 'mp.azamgarh@mplads-demo.local', 'ls_azamgarh'),
(131, 'Gujarat', 'DHAVAL LAXMANBHAI PATEL', 'VALSAD(ST)', 'valsad', 'mp.valsad@mplads-demo.local', 'ls_valsad'),
(132, 'Bihar', 'Dileshwar Kamait', 'SUPAUL', 'supaul', 'mp.supaul@mplads-demo.local', 'ls_supaul'),
(133, 'Assam', 'Dilip Saikia', 'Darrang-Udalguri', 'darrang_udalguri', 'mp.darrang_udalguri@mplads-demo.local', 'ls_darrang_udalguri'),
(134, 'Bihar', 'Dinesh Chandra Yadav', 'MADHEPURA', 'madhepura', 'mp.madhepura@mplads-demo.local', 'ls_madhepura'),
(135, 'Gujarat', 'DINESHBHAI MAKWANA', 'AHMEDABAD WEST(SC)', 'ahmedabad_west', 'mp.ahmedabad_west@mplads-demo.local', 'ls_ahmedabad_west'),
(136, 'Andhra Pradesh', 'DR BYREDDY SHABARI', 'NANDYAL', 'nandyal', 'mp.nandyal@mplads-demo.local', 'ls_nandyal'),
(137, 'Karnataka', 'DR C N MANJUNATH', 'BANGALORE RURAL', 'bangalore_rural', 'mp.bangalore_rural@mplads-demo.local', 'ls_bangalore_rural'),
(138, 'Andhra Pradesh', 'Dr Chandra Sekhar Pemmasani', 'GUNTUR', 'guntur', 'mp.guntur@mplads-demo.local', 'ls_guntur'),
(139, 'Punjab', 'DR DHARAMVIRA GANDHI', 'PATIALA', 'patiala', 'mp.patiala@mplads-demo.local', 'ls_patiala'),
(140, 'West Bengal', 'Dr Jayanta Kumar Roy', 'JALPAIGURI(SC)', 'jalpaiguri', 'mp.jalpaiguri@mplads-demo.local', 'ls_jalpaiguri'),
(141, 'Maharashtra', 'DR KALGE SHIVAJI BANDAPPA', 'LATUR(SC)', 'latur', 'mp.latur@mplads-demo.local', 'ls_latur'),
(142, 'Bihar', 'Dr Mohammad Jawed', 'KISHANGANJ', 'kishanganj', 'mp.kishanganj@mplads-demo.local', 'ls_kishanganj'),
(143, 'Uttar Pradesh', 'DR RAJKUMAR SANGWAN', 'BAGHPAT', 'baghpat', 'mp.baghpat@mplads-demo.local', 'ls_baghpat'),
(144, 'Tamil Nadu', 'DR RANI SRI KUMAR', 'TENKASI(SC)', 'tenkasi', 'mp.tenkasi@mplads-demo.local', 'ls_tenkasi'),
(145, 'Kerala', 'Dr Shashi Tharoor', 'THIRUVANANTHAPURAM', 'thiruvananthapuram', 'mp.thiruvananthapuram@mplads-demo.local', 'ls_thiruvananthapuram'),
(146, 'West Bengal', 'Dr Sukanta Majumdar', 'BALURGHAT', 'balurghat', 'mp.balurghat@mplads-demo.local', 'ls_balurghat'),
(147, 'Gujarat', 'DR. HEMANG JOSHI', 'VADODARA', 'vadodara', 'mp.vadodara@mplads-demo.local', 'ls_vadodara'),
(148, 'Maharashtra', 'DR. HEMANT VISHNU SAVARA', 'PALGHAR(ST)', 'palghar', 'mp.palghar@mplads-demo.local', 'ls_palghar'),
(149, 'Maharashtra', 'DR. KIRSAN NAMDEO', 'GADCHIROLI-CHIMUR(ST)', 'gadchiroli_chimur', 'mp.gadchiroli_chimur@mplads-demo.local', 'ls_gadchiroli_chimur'),
(150, 'Madhya Pradesh', 'DR. LATA WANKHEDE', 'SAGAR', 'sagar', 'mp.sagar@mplads-demo.local', 'ls_sagar'),
(151, 'Kerala', 'DR. M.P ABDUSSAMAD SAMADANI', 'PONNANI', 'ponnani', 'mp.ponnani@mplads-demo.local', 'ls_ponnani'),
(152, 'Gujarat', 'DR. MANSUKH MANDAVIYA', 'PORBANDAR', 'porbandar', 'mp.porbandar@mplads-demo.local', 'ls_porbandar'),
(153, 'Karnataka', 'DR. PRABHA MALLIKARJUN', 'DAVANAGERE', 'davanagere', 'mp.davanagere@mplads-demo.local', 'ls_davanagere'),
(154, 'Odisha', 'DR. PRADEEP KUMAR PANIGRAHY', 'BERHAMPUR', 'berhampur', 'mp.berhampur@mplads-demo.local', 'ls_berhampur'),
(155, 'Maharashtra', 'DR. PRASHANT YADAORAO PADOLE', 'BHANDARA-GONDIYA', 'bhandara_gondiya', 'mp.bhandara_gondiya@mplads-demo.local', 'ls_bhandara_gondiya'),
(156, 'Punjab', 'DR. RAJ KUMAR CHABBEWAL', 'HOSHIARPUR(SC)', 'hoshiarpur', 'mp.hoshiarpur@mplads-demo.local', 'ls_hoshiarpur'),
(157, 'Madhya Pradesh', 'DR. RAJESH MISHRA', 'SIDHI', 'sidhi', 'mp.sidhi@mplads-demo.local', 'ls_sidhi'),
(158, 'Uttar Pradesh', 'DR. S P SINGH', 'PRATAPGARH', 'pratapgarh', 'mp.pratapgarh@mplads-demo.local', 'ls_pratapgarh'),
(159, 'West Bengal', 'DR. SHARMILA SARKAR', 'BARDHAMAN PURBA(SC)', 'bardhaman_purba', 'mp.bardhaman_purba@mplads-demo.local', 'ls_bardhaman_purba'),
(160, 'Karnataka', 'DR.K.SUDHAKAR', 'CHIKBALLAPUR', 'chikballapur', 'mp.chikballapur@mplads-demo.local', 'ls_chikballapur'),
(161, 'Telangana', 'DR.MALLU RAVI', 'NAGARKURNOOL(SC)', 'nagarkurnool', 'mp.nagarkurnool@mplads-demo.local', 'ls_nagarkurnool'),
(162, 'Jharkhand', 'DULU MAHATO', 'DHANBAD', 'dhanbad', 'mp.dhanbad@mplads-demo.local', 'ls_dhanbad'),
(163, 'Tamil Nadu', 'DURAI VAIKO', 'TIRUCHIRAPPALLI', 'tiruchirappalli', 'mp.tiruchirappalli@mplads-demo.local', 'ls_tiruchirappalli'),
(164, 'Madhya Pradesh', 'Durga Das Uikey', 'BETUL(ST)', 'betul', 'mp.betul@mplads-demo.local', 'ls_betul'),
(165, 'Rajasthan', 'Dushyant Singh', 'JHALAWAR-BARAN', 'jhalawar_baran', 'mp.jhalawar_baran@mplads-demo.local', 'ls_jhalawar_baran'),
(166, 'Karnataka', 'E. TUKARAM', 'BELLARY(ST)', 'bellary', 'mp.bellary@mplads-demo.local', 'ls_bellary'),
(167, 'Kerala', 'E.T. MOHAMMED BASHEER', 'MALAPPURAM', 'malappuram', 'mp.malappuram@mplads-demo.local', 'ls_malappuram'),
(168, 'Telangana', 'EATALA RAJENDER', 'MALKAJGIRI', 'malkajgiri', 'mp.malkajgiri@mplads-demo.local', 'ls_malkajgiri'),
(169, 'Tamil Nadu', 'ESWARASAMY K', 'POLLACHI', 'pollachi', 'mp.pollachi@mplads-demo.local', 'ls_pollachi'),
(170, 'Madhya Pradesh', 'Faggan Singh Kulaste', 'MANDLA(ST)', 'mandla', 'mp.mandla@mplads-demo.local', 'ls_mandla'),
(171, 'Karnataka', 'G. KUMAR NAIK', 'RAICHUR(ST)', 'raichur', 'mp.raichur@mplads-demo.local', 'ls_raichur'),
(172, 'Maharashtra', 'GAIKWAD VARSHA EKNATH', 'MUMBAI NORTH-CENTRAL', 'mumbai_north_central', 'mp.mumbai_north_central@mplads-demo.local', 'ls_mumbai_north_central'),
(173, 'Madhya Pradesh', 'Gajendra Singh Patel', 'KHARGONE(ST)', 'khargone', 'mp.khargone@mplads-demo.local', 'ls_khargone'),
(174, 'Rajasthan', 'Gajendra Singh Shekhawat', 'JODHPUR', 'jodhpur', 'mp.jodhpur@mplads-demo.local', 'ls_jodhpur'),
(175, 'Tamil Nadu', 'GANAPATHY RAJKUMAR P', 'COIMBATORE', 'coimbatore', 'mp.coimbatore@mplads-demo.local', 'ls_coimbatore'),
(176, 'Tamil Nadu', 'Ganesan Selvam', 'KANCHEEPURAM(SC)', 'kancheepuram', 'mp.kancheepuram@mplads-demo.local', 'ls_kancheepuram'),
(177, 'Madhya Pradesh', 'Ganesh Singh', 'SATNA', 'satna', 'mp.satna@mplads-demo.local', 'ls_satna'),
(178, 'Assam', 'GAURAV GOGOI', 'JORHAT', 'jorhat', 'mp.jorhat@mplads-demo.local', 'ls_jorhat'),
(179, 'Gujarat', 'GENIBEN NAGAJI THAKOR', 'BANASKANTHA', 'banaskantha', 'mp.banaskantha@mplads-demo.local', 'ls_banaskantha'),
(180, 'Bihar', 'Giridhari Yadav', 'BANKA', 'banka', 'mp.banka@mplads-demo.local', 'ls_banka'),
(181, 'Bihar', 'Giriraj Singh', 'BEGUSARAI', 'begusarai', 'mp.begusarai@mplads-demo.local', 'ls_begusarai'),
(182, 'Andhra Pradesh', 'GM Harish Balayogi', 'AMALAPURAM(SC)', 'amalapuram', 'mp.amalapuram@mplads-demo.local', 'ls_amalapuram'),
(183, 'Telangana', 'GODAM NAGESH', 'ADILABAD(ST)', 'adilabad', 'mp.adilabad@mplads-demo.local', 'ls_adilabad'),
(184, 'Tamil Nadu', 'GOPINATH K', 'KRISHNAGIRI', 'krishnagiri', 'mp.krishnagiri@mplads-demo.local', 'ls_krishnagiri'),
(185, 'Karnataka', 'GOVIND MAKTHAPPA KARJOL', 'CHITRADURGA(SC)', 'chitradurga', 'mp.chitradurga@mplads-demo.local', 'ls_chitradurga'),
(186, 'Andhra Pradesh', 'Gumma Thanuja Rani', 'ARAKU(ST)', 'araku', 'mp.araku@mplads-demo.local', 'ls_araku'),
(187, 'Punjab', 'GURMEET SINGH MEET HAYER', 'SANGRUR', 'sangrur', 'mp.sangrur@mplads-demo.local', 'ls_sangrur'),
(188, 'Madhya Pradesh', 'Gyaneshwar Patil', 'KHANDWA', 'khandwa', 'mp.khandwa@mplads-demo.local', 'ls_khandwa'),
(189, 'Karnataka', 'H.D. KUMARASWAMY', 'MANDYA', 'mandya', 'mp.mandya@mplads-demo.local', 'ls_mandya'),
(190, 'Uttar Pradesh', 'HARENDRA SINGH MALIK', 'MUZAFFARNAGAR', 'muzaffarnagar', 'mp.muzaffarnagar@mplads-demo.local', 'ls_muzaffarnagar'),
(191, 'Gujarat', 'HARIBHAI PATEL', 'MAHESANA', 'mahesana', 'mp.mahesana@mplads-demo.local', 'ls_mahesana'),
(192, 'Rajasthan', 'HARISH CHANDRA MEENA', 'TONK-SAWAI MADHOPUR', 'tonk_sawai_madhopur', 'mp.tonk_sawai_madhopur@mplads-demo.local', 'ls_tonk_sawai_madhopur'),
(193, 'Delhi', 'Harsh Malhotra', 'EAST DELHI', 'east_delhi', 'mp.east_delhi@mplads-demo.local', 'ls_east_delhi'),
(194, 'Gujarat', 'Hasmukh Bhai Soma Bhai Patel', 'AHMEDABAD EAST', 'ahmedabad_east', 'mp.ahmedabad_east@mplads-demo.local', 'ls_ahmedabad_east'),
(195, 'Uttar Pradesh', 'IMRAN MASOOD', 'SAHARANPUR', 'saharanpur', 'mp.saharanpur@mplads-demo.local', 'ls_saharanpur'),
(196, 'Sikkim', 'Indra Hang Subba', 'SIKKIM', 'sikkim', 'mp.sikkim@mplads-demo.local', 'ls_sikkim'),
(197, 'Uttar Pradesh', 'IQRA CHOUDHARY', 'KAIRANA', 'kairana', 'mp.kairana@mplads-demo.local', 'ls_kairana'),
(198, 'West Bengal', 'ISHA KHAN CHOUDHURY', 'MALDAHA DAKSHIN', 'maldaha_dakshin', 'mp.maldaha_dakshin@mplads-demo.local', 'ls_maldaha_dakshin'),
(199, 'West Bengal', 'JAGADISH CHANDRA BARMA BASUNIA', 'COOCHBEHAR(SC)', 'coochbehar', 'mp.coochbehar@mplads-demo.local', 'ls_coochbehar'),
(200, 'Karnataka', 'JAGADISH SHETTAR', 'BELGAUM', 'belgaum', 'mp.belgaum@mplads-demo.local', 'ls_belgaum'),
(201, 'West Bengal', 'Jagannath Sarkar', 'RANAGHAT(SC)', 'ranaghat', 'mp.ranaghat@mplads-demo.local', 'ls_ranaghat'),
(202, 'Uttar Pradesh', 'Jagdambika Pal', 'DOMARIYAGANJ', 'domariyaganj', 'mp.domariyaganj@mplads-demo.local', 'ls_domariyaganj'),
(203, 'Haryana', 'JAI PARKASH', 'HISAR', 'hisar', 'mp.hisar@mplads-demo.local', 'ls_hisar'),
(204, 'Uttar Pradesh', 'Jai Prakash', 'HARDOI (SC)', 'hardoi', 'mp.hardoi@mplads-demo.local', 'ls_hardoi'),
(205, 'Madhya Pradesh', 'Janardan Mishra', 'REWA', 'rewa', 'mp.rewa@mplads-demo.local', 'ls_rewa'),
(206, 'Gujarat', 'JASHUBHAI BHILUBHAI RATHVA', 'CHHOTA UDAIPUR(ST)', 'chhota_udaipur', 'mp.chhota_udaipur@mplads-demo.local', 'ls_chhota_udaipur'),
(207, 'Gujarat', 'Jaswantsinh Sumanbhai Bhabhor', 'DAHOD(ST)', 'dahod', 'mp.dahod@mplads-demo.local', 'ls_dahod'),
(208, 'Bihar', 'JITAN RAM MANJHI', 'GAYA (SC)', 'gaya', 'mp.gaya@mplads-demo.local', 'ls_gaya'),
(209, 'Uttar Pradesh', 'JITENDRA KUMAR DOHARE', 'ETAWAH(SC)', 'etawah', 'mp.etawah@mplads-demo.local', 'ls_etawah'),
(210, 'Jammu And Kashmir', 'Jitendra Singh', 'UDHAMPUR', 'udhampur', 'mp.udhampur@mplads-demo.local', 'ls_udhampur'),
(211, 'Uttar Pradesh', 'JITIN PRASADA', 'PILIBHIT', 'pilibhit', 'mp.pilibhit@mplads-demo.local', 'ls_pilibhit'),
(212, 'Jharkhand', 'JOBA MAJHI', 'SINGHBHUM(ST)', 'singhbhum', 'mp.singhbhum@mplads-demo.local', 'ls_singhbhum'),
(213, 'Assam', 'JOYANTA BASUMATARY', 'KOKRAJHAR (ST)', 'kokrajhar', 'mp.kokrajhar@mplads-demo.local', 'ls_kokrajhar'),
(214, 'West Bengal', 'JUNE MALIAH', 'MEDINIPUR', 'medinipur', 'mp.medinipur@mplads-demo.local', 'ls_medinipur'),
(215, 'Madhya Pradesh', 'JYOTIRADITYA M. SCINDIA', 'GUNA', 'guna', 'mp.guna@mplads-demo.local', 'ls_guna'),
(216, 'Chhattisgarh', 'Jyotsna Charandas Mahant', 'KORBA', 'korba', 'mp.korba@mplads-demo.local', 'ls_korba'),
(217, 'Tamil Nadu', 'K E PRAKASH', 'ERODE', 'erode', 'mp.erode@mplads-demo.local', 'ls_erode'),
(218, 'Kerala', 'K RADHAKRISHNAN', 'ALATHUR(SC)', 'alathur', 'mp.alathur@mplads-demo.local', 'ls_alathur'),
(219, 'Tamil Nadu', 'K Subbarayan', 'TIRUPPUR', 'tiruppur', 'mp.tiruppur@mplads-demo.local', 'ls_tiruppur'),
(220, 'Kerala', 'K. C VENUGOPAL', 'ALAPPUZHA', 'alappuzha', 'mp.alappuzha@mplads-demo.local', 'ls_alappuzha'),
(221, 'Karnataka', 'K. RAJASHEKAR BASAVARAJ HITNAL', 'KOPPAL', 'koppal', 'mp.koppal@mplads-demo.local', 'ls_koppal'),
(222, 'Telangana', 'KADIYAM KAVYA', 'WARANGEL(SC)', 'warangel', 'mp.warangel@mplads-demo.local', 'ls_warangel'),
(223, 'West Bengal', 'Kakoli Ghosh Dastidar', 'BARASAT', 'barasat', 'mp.barasat@mplads-demo.local', 'ls_barasat'),
(224, 'The Dadra And Nagar Haveli And Daman And Diu', 'Kalaben Mohanbhai Delkar', 'DADRA & NAGAR HAVELI (ST)', 'dadra_and_nagar_haveli', 'mp.dadra_and_nagar_haveli@mplads-demo.local', 'ls_dadra_and_nagar_haveli'),
(225, 'Tamil Nadu', 'Kalanidhi Veeraswamy', 'CHENNAI NORTH', 'chennai_north', 'mp.chennai_north@mplads-demo.local', 'ls_chennai_north'),
(226, 'Jharkhand', 'KALI CHARAN MUNDA', 'KHUNTI(ST)', 'khunti', 'mp.khunti@mplads-demo.local', 'ls_khunti'),
(227, 'Jharkhand', 'KALI CHARAN SINGH', 'CHATRA', 'chatra', 'mp.chatra@mplads-demo.local', 'ls_chatra'),
(228, 'West Bengal', 'KALIPADA SAREN', 'JHARGRAM(ST)', 'jhargram', 'mp.jhargram@mplads-demo.local', 'ls_jhargram'),
(229, 'West Bengal', 'Kalyan Banerjee', 'SREERAMPUR', 'sreerampur', 'mp.sreerampur@mplads-demo.local', 'ls_sreerampur'),
(230, 'Maharashtra', 'KALYAN VAIJINATHRAO KALE', 'JALNA', 'jalna', 'mp.jalna@mplads-demo.local', 'ls_jalna'),
(231, 'Assam', 'KAMAKHYA PRASAD TASA', 'Kaziranga', 'kaziranga', 'mp.kaziranga@mplads-demo.local', 'ls_kaziranga'),
(232, 'Delhi', 'Kamaljeet Sehrawat', 'WEST DELHI', 'west_delhi', 'mp.west_delhi@mplads-demo.local', 'ls_west_delhi'),
(233, 'Chhattisgarh', 'KAMLESH JANGDE', 'JANJGIR CHAMPA(SC)', 'janjgir_champa', 'mp.janjgir_champa@mplads-demo.local', 'ls_janjgir_champa'),
(234, 'Uttar Pradesh', 'Kamlesh Paswan', 'BANSGAON(SC)', 'bansgaon', 'mp.bansgaon@mplads-demo.local', 'ls_bansgaon'),
(235, 'Himachal Pradesh', 'Kangana Ranaut', 'MANDI', 'mandi', 'mp.mandi@mplads-demo.local', 'ls_mandi'),
(236, 'Tamil Nadu', 'Kani K Navas', 'RAMANATHAPURAM', 'ramanathapuram', 'mp.ramanathapuram@mplads-demo.local', 'ls_ramanathapuram'),
(237, 'Tamil Nadu', 'Kanimozhi Karunanidhi', 'THOOTHUKKUDI', 'thoothukkudi', 'mp.thoothukkudi@mplads-demo.local', 'ls_thoothukkudi'),
(238, 'Uttar Pradesh', 'KANWAR SINGH TANWAR', 'AMROHA', 'amroha', 'mp.amroha@mplads-demo.local', 'ls_amroha'),
(239, 'Uttar Pradesh', 'KARAN BHUSHAN SINGH', 'KAISERGANJ', 'kaiserganj', 'mp.kaiserganj@mplads-demo.local', 'ls_kaiserganj'),
(240, 'West Bengal', 'KARTICK CHANDRA PAUL', 'RAIGANJ', 'raiganj', 'mp.raiganj@mplads-demo.local', 'ls_raiganj'),
(241, 'Bihar', 'Kaushalendra Kumar', 'NALANDA', 'nalanda', 'mp.nalanda@mplads-demo.local', 'ls_nalanda'),
(242, 'West Bengal', 'Khagen Murmu', 'MALDAHA UTTAR', 'maldaha_uttar', 'mp.maldaha_uttar@mplads-demo.local', 'ls_maldaha_uttar'),
(243, 'West Bengal', 'Khalilur Rahaman', 'JANGIPUR', 'jangipur', 'mp.jangipur@mplads-demo.local', 'ls_jangipur'),
(244, 'Andhra Pradesh', 'Kinjarapu Ram Mohan Naidu', 'SRIKAKULAM', 'srikakulam', 'mp.srikakulam@mplads-demo.local', 'ls_srikakulam'),
(245, 'Arunachal Pradesh', 'Kiren Rijiju', 'ARUNACHAL WEST', 'arunachal_west', 'mp.arunachal_west@mplads-demo.local', 'ls_arunachal_west'),
(246, 'Uttar Pradesh', 'Kirti Vardhan Singh', 'GONDA', 'gonda', 'mp.gonda@mplads-demo.local', 'ls_gonda'),
(247, 'Telangana', 'Kishan Reddy Gangapuram', 'SECUNDERABAD', 'secunderabad', 'mp.secunderabad@mplads-demo.local', 'ls_secunderabad'),
(248, 'Uttar Pradesh', 'KISHORI LAL', 'AMETHI', 'amethi', 'mp.amethi@mplads-demo.local', 'ls_amethi'),
(249, 'Telangana', 'KONDA VISHWESHWAR REDDY', 'CHELVELLA', 'chelvella', 'mp.chelvella@mplads-demo.local', 'ls_chelvella'),
(250, 'Karnataka', 'KOTA SRINIVAS POOJARY', 'UDUPI CHIKMAGALUR', 'udupi_chikmagalur', 'mp.udupi_chikmagalur@mplads-demo.local', 'ls_udupi_chikmagalur'),
(251, 'Assam', 'Kripanath Mallah', 'KARIMGANJ (SC)', 'karimganj', 'mp.karimganj@mplads-demo.local', 'ls_karimganj'),
(252, 'Haryana', 'Krishan Pal Gurjar', 'FARIDABAD', 'faridabad', 'mp.faridabad@mplads-demo.local', 'ls_faridabad'),
(253, 'Uttar Pradesh', 'KRISHNA DEVI SHIVSHANKER PATEL', 'BANDA', 'banda', 'mp.banda@mplads-demo.local', 'ls_banda'),
(254, 'Andhra Pradesh', 'Krishna Prasad Tenneti', 'BAPATLA', 'bapatla', 'mp.bapatla@mplads-demo.local', 'ls_bapatla'),
(255, 'Tripura', 'KRITI DEVI DEBBARMAN', 'TRIPURA EAST(ST)', 'tripura_east', 'mp.tripura_east@mplads-demo.local', 'ls_tripura_east'),
(256, 'Rajasthan', 'KULDEEP INDORA', 'GANGANAGAR(SC)', 'ganganagar', 'mp.ganganagar@mplads-demo.local', 'ls_ganganagar'),
(257, 'Telangana', 'KUNDURU RAGHUVEER', 'NALGONDA', 'nalgonda', 'mp.nalgonda@mplads-demo.local', 'ls_nalgonda'),
(258, 'Uttar Pradesh', 'LALJI VERMA', 'AMBEDKAR NAGAR', 'ambedkar_nagar', 'mp.ambedkar_nagar@mplads-demo.local', 'ls_ambedkar_nagar'),
(259, 'Andhra Pradesh', 'Lavu Sri Krishna Devarayalu', 'NARASARAOPET', 'narasaraopet', 'mp.narasaraopet@mplads-demo.local', 'ls_narasaraopet'),
(260, 'Uttar Pradesh', 'LAXMIKANT PAPPU NISHAD', 'SANT KABIR NAGAR', 'sant_kabir_nagar', 'mp.sant_kabir_nagar@mplads-demo.local', 'ls_sant_kabir_nagar'),
(261, 'Bihar', 'LOVELY ANAND', 'SHEOHAR', 'sheohar', 'mp.sheohar@mplads-demo.local', 'ls_sheohar'),
(262, 'Rajasthan', 'LUMBARAM', 'JALORE', 'jalore', 'mp.jalore@mplads-demo.local', 'ls_jalore'),
(263, 'Karnataka', 'M. MALLESH BABU', 'KOLAR(SC)', 'kolar', 'mp.kolar@mplads-demo.local', 'ls_kolar'),
(264, 'Tamil Nadu', 'M.K. VISHNUPRASAD', 'CUDDALORE', 'cuddalore', 'mp.cuddalore@mplads-demo.local', 'ls_cuddalore'),
(265, 'Andhra Pradesh', 'Maddila Gurumoorthy', 'TIRUPATI(SC)', 'tirupati', 'mp.tirupati@mplads-demo.local', 'ls_tirupati'),
(266, 'Telangana', 'MADHAVANENI RAGHUNANDAN RAO', 'MEDAK', 'medak', 'mp.medak@mplads-demo.local', 'ls_medak'),
(267, 'Andhra Pradesh', 'Magunta Sreenivasulu Reddy', 'ONGOLE', 'ongole', 'mp.ongole@mplads-demo.local', 'ls_ongole'),
(268, 'Madhya Pradesh', 'Mahendra Singh Solanky', 'DEWAS(SC)', 'dewas', 'mp.dewas@mplads-demo.local', 'ls_dewas'),
(269, 'Chhattisgarh', 'MAHESH KASHYAP', 'BASTAR(ST)', 'bastar', 'mp.bastar@mplads-demo.local', 'ls_bastar'),
(270, 'Uttar Pradesh', 'Mahesh Sharma', 'GAUTAM BUDDHA NAGAR', 'gautam_buddha_nagar', 'mp.gautam_buddha_nagar@mplads-demo.local', 'ls_gautam_buddha_nagar'),
(271, 'Rajasthan', 'MAHIMA KUMARI MEWAR', 'RAJSAMAND', 'rajsamand', 'mp.rajsamand@mplads-demo.local', 'ls_rajsamand'),
(272, 'Uttarakhand', 'Mala Rajya Laxmi Shah', 'TEHRI GARHWAL', 'tehri_garhwal', 'mp.tehri_garhwal@mplads-demo.local', 'ls_tehri_garhwal'),
(273, 'West Bengal', 'Mala Roy', 'KOLKATA DAKSHIN', 'kolkata_dakshin', 'mp.kolkata_dakshin@mplads-demo.local', 'ls_kolkata_dakshin'),
(274, 'Tamil Nadu', 'MALAIYARASAN D', 'KALLAKURICHI', 'kallakurichi', 'mp.kallakurichi@mplads-demo.local', 'ls_kallakurichi'),
(275, 'Odisha', 'MALVIKA DEVI', 'KALAHANDI', 'kalahandi', 'mp.kalahandi@mplads-demo.local', 'ls_kalahandi'),
(276, 'Punjab', 'MALVINDER SINGH KANG', 'ANANDPUR SAHIB', 'anandpur_sahib', 'mp.anandpur_sahib@mplads-demo.local', 'ls_anandpur_sahib'),
(277, 'Tamil Nadu', 'MANI. A.', 'DHARAMAPURI', 'dharamapuri', 'mp.dharamapuri@mplads-demo.local', 'ls_dharamapuri'),
(278, 'Tamil Nadu', 'Manickam Tagore B', 'VIRUDHUNAGAR', 'virudhunagar', 'mp.virudhunagar@mplads-demo.local', 'ls_virudhunagar'),
(279, 'Jharkhand', 'MANISH JAISWAL', 'HAZARIBAGH', 'hazaribagh', 'mp.hazaribagh@mplads-demo.local', 'ls_hazaribagh'),
(280, 'Chandigarh', 'MANISH TEWARI', 'CHANDIGARH', 'chandigarh', 'mp.chandigarh@mplads-demo.local', 'ls_chandigarh'),
(281, 'Rajasthan', 'MANJU SHARMA', 'JAIPUR', 'jaipur', 'mp.jaipur@mplads-demo.local', 'ls_jaipur'),
(282, 'Rajasthan', 'MANNA LAL RAWAT', 'UDAIPUR(ST)', 'udaipur', 'mp.udaipur@mplads-demo.local', 'ls_udaipur'),
(283, 'Haryana', 'MANOHAR LAL', 'KARNAL', 'karnal', 'mp.karnal@mplads-demo.local', 'ls_karnal'),
(284, 'Bihar', 'MANOJ KUMAR', 'SASARAM(SC)', 'sasaram', 'mp.sasaram@mplads-demo.local', 'ls_sasaram'),
(285, 'West Bengal', 'MANOJ TIGGA', 'ALIPURDUARS(ST)', 'alipurduars', 'mp.alipurduars@mplads-demo.local', 'ls_alipurduars'),
(286, 'Delhi', 'Manoj Tiwari', 'NORTH EAST DELHI', 'north_east_delhi', 'mp.north_east_delhi@mplads-demo.local', 'ls_north_east_delhi'),
(287, 'Gujarat', 'Mansukhbhai Dhanjibhai Vasava', 'BHARUCH', 'bharuch', 'mp.bharuch@mplads-demo.local', 'ls_bharuch'),
(288, 'Jammu And Kashmir', 'MIAN ALTAF AHMAD', 'ANANTNAG', 'anantnag', 'mp.anantnag@mplads-demo.local', 'ls_anantnag'),
(289, 'Andhra Pradesh', 'Midhun Reddy', 'RAJAMPET', 'rajampet', 'mp.rajampet@mplads-demo.local', 'ls_rajampet'),
(290, 'Bihar', 'MISHA BHARTI', 'PATALIPUTRA', 'pataliputra', 'mp.pataliputra@mplads-demo.local', 'ls_pataliputra'),
(291, 'Gujarat', 'Mitesh Rameshbhai Bakabhai Patel', 'ANAND', 'anand', 'mp.anand@mplads-demo.local', 'ls_anand'),
(292, 'Ladakh', 'Mohamed Haneefa', 'LADAKH', 'ladakh', 'mp.ladakh@mplads-demo.local', 'ls_ladakh'),
(293, 'Uttar Pradesh', 'MOHIBBULLAH', 'RAMPUR', 'rampur', 'mp.rampur@mplads-demo.local', 'ls_rampur'),
(294, 'Maharashtra', 'MOHITE PATIL DHAIRYASHEEL RAJSINH', 'MADHA', 'madha', 'mp.madha@mplads-demo.local', 'ls_madha'),
(295, 'Bihar', 'Mr Gopal Jee Thakur', 'DARBHANGA', 'darbhanga', 'mp.darbhanga@mplads-demo.local', 'ls_darbhanga'),
(296, 'West Bengal', 'Ms Mahua Moitra', 'KRISHNANAGAR', 'krishnanagar', 'mp.krishnanagar@mplads-demo.local', 'ls_krishnanagar'),
(297, 'Lakshadweep', 'MUHAMMED HAMDULLAH SAYEED', 'LAKSHADWEEP(ST)', 'lakshadweep', 'mp.lakshadweep@mplads-demo.local', 'ls_lakshadweep'),
(298, 'Uttar Pradesh', 'Mukesh Rajput', 'FARRUKHABAD', 'farrukhabad', 'mp.farrukhabad@mplads-demo.local', 'ls_farrukhabad'),
(299, 'Gujarat', 'MUKESHKUMAR CHANDRAKAANT DALAL', 'SURAT', 'surat', 'mp.surat@mplads-demo.local', 'ls_surat'),
(300, 'Rajasthan', 'MURARI LAL MEENA', 'DAUSA(ST)', 'dausa', 'mp.dausa@mplads-demo.local', 'ls_dausa'),
(301, 'Tamil Nadu', 'MURASOLI S', 'THANJAVUR', 'thanjavur', 'mp.thanjavur@mplads-demo.local', 'ls_thanjavur'),
(302, 'Maharashtra', 'MURLIDHAR MOHOL', 'PUNE', 'pune', 'mp.pune@mplads-demo.local', 'ls_pune'),
(303, 'Odisha', 'NABA CHARAN MAJHI', 'MAYURBHANJ (ST)', 'mayurbhanj', 'mp.mayurbhanj@mplads-demo.local', 'ls_mayurbhanj'),
(304, 'Jharkhand', 'NALIN SOREN', 'DUMKA(ST)', 'dumka', 'mp.dumka@mplads-demo.local', 'ls_dumka'),
(305, 'Uttar Pradesh', 'NARAYAN DAS AHIRWAR', 'JALAUN(SC)', 'jalaun', 'mp.jalaun@mplads-demo.local', 'ls_jalaun'),
(306, 'Maharashtra', 'NARAYAN TATU RANE', 'RATNAGIRI-SINDHUDURG', 'ratnagiri_sindhudurg', 'mp.ratnagiri_sindhudurg@mplads-demo.local', 'ls_ratnagiri_sindhudurg'),
(307, 'Uttar Pradesh', 'NARESH CHANDRA UTTAM PATEL', 'FATEHPUR', 'fatehpur', 'mp.fatehpur@mplads-demo.local', 'ls_fatehpur'),
(308, 'Maharashtra', 'NARESH GANPAT MHASKE', 'THANE', 'thane', 'mp.thane@mplads-demo.local', 'ls_thane'),
(309, 'Haryana', 'NAVEEN JINDAL', 'KURUKSHETRA', 'kurukshetra', 'mp.kurukshetra@mplads-demo.local', 'ls_kurukshetra'),
(310, 'Uttar Pradesh', 'NEERAJ MAURYA', 'AONLA', 'aonla', 'mp.aonla@mplads-demo.local', 'ls_aonla'),
(311, 'Maharashtra', 'NILESH DNYANDEV LANKE', 'AHMEDNAGAR', 'ahmednagar', 'mp.ahmednagar@mplads-demo.local', 'ls_ahmednagar'),
(312, 'Gujarat', 'NIMUBEN JAYANTIBHAI BAMBHANIYA', 'BHAVNAGAR', 'bhavnagar', 'mp.bhavnagar@mplads-demo.local', 'ls_bhavnagar'),
(313, 'Jharkhand', 'Nishikant Dubey', 'GODDA', 'godda', 'mp.godda@mplads-demo.local', 'ls_godda'),
(314, 'Maharashtra', 'Nitin Jairam Gadkari', 'NAGPUR', 'nagpur', 'mp.nagpur@mplads-demo.local', 'ls_nagpur'),
(315, 'Bihar', 'Nityanand Rai', 'UJJARPUR', 'ujjarpur', 'mp.ujjarpur@mplads-demo.local', 'ls_ujjarpur'),
(316, 'Rajasthan', 'Om Birla', 'KOTA', 'kota', 'mp.kota@mplads-demo.local', 'ls_kota'),
(317, 'Maharashtra', 'Omprakash Bhupalsinh Alias Pawan Rajenimbalkar', 'OSMANABAD', 'osmanabad', 'mp.osmanabad@mplads-demo.local', 'ls_osmanabad'),
(318, 'Karnataka', 'P C Mohan', 'BANGALORE CENTRAL', 'bangalore_central', 'mp.bangalore_central@mplads-demo.local', 'ls_bangalore_central'),
(319, 'Uttar Pradesh', 'Pankaj Chowdhary', 'MAHARAJGANJ_UP', 'maharajganj_up', 'mp.maharajganj_up@mplads-demo.local', 'ls_maharajganj_up'),
(320, 'Assam', 'PARIMAL SUKLABAIDYA', 'SILCHAR', 'silchar', 'mp.silchar@mplads-demo.local', 'ls_silchar'),
(321, 'Gujarat', 'PARSHOTTAMBHAI RUPALA', 'RAJKOT', 'rajkot', 'mp.rajkot@mplads-demo.local', 'ls_rajkot'),
(322, 'West Bengal', 'PARTHA BHOWMICK', 'BARRACKPUR', 'barrackpur', 'mp.barrackpur@mplads-demo.local', 'ls_barrackpur'),
(323, 'Karnataka', 'Parvatagouda Chandanagouda Gaddigoudar', 'BAGALKOT', 'bagalkot', 'mp.bagalkot@mplads-demo.local', 'ls_bagalkot'),
(324, 'The Dadra And Nagar Haveli And Daman And Diu', 'PATEL UMESHBHAI BABUBHAI', 'DAMAN and DIU', 'daman_and_diu', 'mp.daman_and_diu@mplads-demo.local', 'ls_daman_and_diu'),
(325, 'West Bengal', 'PATHAN YUSUF', 'BAHARAMPUR', 'baharampur', 'mp.baharampur@mplads-demo.local', 'ls_baharampur'),
(326, 'Assam', 'PHANI BHUSAN CHOUDHURY', 'BARPETA', 'barpeta', 'mp.barpeta@mplads-demo.local', 'ls_barpeta'),
(327, 'Maharashtra', 'Piyush Vedprakash Goyal', 'MUMBAI NORTH', 'mumbai_north', 'mp.mumbai_north@mplads-demo.local', 'ls_mumbai_north'),
(328, 'Andhra Pradesh', 'PRABHAKAR REDDY VEMIREDDY', 'NELLORE(SC)', 'nellore', 'mp.nellore@mplads-demo.local', 'ls_nellore'),
(329, 'Gujarat', 'Prabhubhai Nagarbhai Vasava', 'BARDOLI(ST)', 'bardoli', 'mp.bardoli@mplads-demo.local', 'ls_bardoli'),
(330, 'Assam', 'Pradan Baruah', 'LAKHIMPUR', 'lakhimpur', 'mp.lakhimpur@mplads-demo.local', 'ls_lakhimpur'),
(331, 'Bihar', 'Pradeep Kumar Singh', 'ARARIA', 'araria', 'mp.araria@mplads-demo.local', 'ls_araria'),
(332, 'Odisha', 'PRADEEP PUROHIT', 'BARGARH', 'bargarh', 'mp.bargarh@mplads-demo.local', 'ls_bargarh'),
(333, 'Assam', 'Pradyut Bordoloi', 'NOWGONG', 'nowgong', 'mp.nowgong@mplads-demo.local', 'ls_nowgong'),
(334, 'Karnataka', 'Pralhad Venkatesh Joshi', 'DHARWAD', 'dharwad', 'mp.dharwad@mplads-demo.local', 'ls_dharwad'),
(335, 'Maharashtra', 'PRANITI SUSHILKUMAR SHINDE', 'SOLAPUR(SC)', 'solapur', 'mp.solapur@mplads-demo.local', 'ls_solapur'),
(336, 'West Bengal', 'Prasun Banerjee', 'HOWRAH', 'howrah', 'mp.howrah@mplads-demo.local', 'ls_howrah'),
(337, 'Odisha', 'Pratap Chandra Sarangi', 'BALASORE', 'balasore', 'mp.balasore@mplads-demo.local', 'ls_balasore'),
(338, 'Maharashtra', 'Prataprao Jadhav', 'BULDHANA', 'buldhana', 'mp.buldhana@mplads-demo.local', 'ls_buldhana'),
(339, 'West Bengal', 'Pratima Mondal', 'JOYNAGAR(SC)', 'joynagar', 'mp.joynagar@mplads-demo.local', 'ls_joynagar'),
(340, 'Delhi', 'Praveen Khandelwal', 'CHANDINI CHOWK', 'chandini_chowk', 'mp.chandini_chowk@mplads-demo.local', 'ls_chandini_chowk'),
(341, 'Uttar Pradesh', 'PRAVEEN PATEL', 'PHULPUR', 'phulpur', 'mp.phulpur@mplads-demo.local', 'ls_phulpur'),
(342, 'Uttar Pradesh', 'PRIYA SAROJ', 'MACHHLISHAHR(SC)', 'machhlishahr', 'mp.machhlishahr@mplads-demo.local', 'ls_machhlishahr'),
(343, 'Kerala', 'Priyanka Gandhi Vadra', 'WAYANAD', 'wayanad', 'mp.wayanad@mplads-demo.local', 'ls_wayanad'),
(344, 'Karnataka', 'PRIYANKA SATISH JARKIHOLI', 'CHIKKODI', 'chikkodi', 'mp.chikkodi@mplads-demo.local', 'ls_chikkodi'),
(345, 'West Bengal', 'Prof Sougata Ray', 'DUM DUM', 'dum_dum', 'mp.dum_dum@mplads-demo.local', 'ls_dum_dum'),
(346, 'Uttar Pradesh', 'Prof SP Singh Baghel', 'AGRA(SC)', 'agra', 'mp.agra@mplads-demo.local', 'ls_agra'),
(347, 'Uttar Pradesh', 'PUSHPENDRA SAROJ', 'KAUSHAMBI(SC)', 'kaushambi', 'mp.kaushambi@mplads-demo.local', 'ls_kaushambi'),
(348, 'Andhra Pradesh', 'Putta Mahesh Kumar', 'ELURU', 'eluru', 'mp.eluru@mplads-demo.local', 'ls_eluru'),
(349, 'Uttar Pradesh', 'R.K. CHAUDHARY', 'MOHANLALGANJ(SC)', 'mohanlalganj', 'mp.mohanlalganj@mplads-demo.local', 'ls_mohanlalganj'),
(350, 'Odisha', 'RABINDRA NARAYAN BEHERA', 'JAJPUR(SC)', 'jajpur', 'mp.jajpur@mplads-demo.local', 'ls_jajpur'),
(351, 'West Bengal', 'RACHNA BANERJEE', 'HOOGHLY', 'hooghly', 'mp.hooghly@mplads-demo.local', 'ls_hooghly'),
(352, 'Bihar', 'Radha Mohan Singh', 'PURVI CHAMPARAN', 'purvi_champaran', 'mp.purvi_champaran@mplads-demo.local', 'ls_purvi_champaran'),
(353, 'Karnataka', 'RADHAKRISHNA', 'GULBARGA(SC)', 'gulbarga', 'mp.gulbarga@mplads-demo.local', 'ls_gulbarga'),
(354, 'Chhattisgarh', 'RADHE SHYAM RATHIYA', 'RAIGARH(ST)', 'raigarh', 'mp.raigarh@mplads-demo.local', 'ls_raigarh'),
(355, 'Uttar Pradesh', 'RAHUL GANDHI', 'RAE BARELI', 'rae_bareli', 'mp.rae_bareli@mplads-demo.local', 'ls_rae_bareli'),
(356, 'Rajasthan', 'Rahul Kaswan', 'CHURU', 'churu', 'mp.churu@mplads-demo.local', 'ls_churu'),
(357, 'Madhya Pradesh', 'RAHUL SINGH LODHI', 'DAMOH', 'damoh', 'mp.damoh@mplads-demo.local', 'ls_damoh'),
(358, 'Bihar', 'RAJ BHUSHAN CHOUDHARY', 'MUZAFFARPUR', 'muzaffarpur', 'mp.muzaffarpur@mplads-demo.local', 'ls_muzaffarpur'),
(359, 'Rajasthan', 'RAJ KUMAR ROAT', 'BANSWARA(ST)', 'banswara', 'mp.banswara@mplads-demo.local', 'ls_banswara'),
(360, 'Bihar', 'RAJA RAM SINGH', 'KARAKAT', 'karakat', 'mp.karakat@mplads-demo.local', 'ls_karakat'),
(361, 'Maharashtra', 'RAJABHAU', 'NASHIK', 'nashik', 'mp.nashik@mplads-demo.local', 'ls_nashik'),
(362, 'Himachal Pradesh', 'RAJEEV BHARDWAJ', 'KANGRA', 'kangra', 'mp.kangra@mplads-demo.local', 'ls_kangra'),
(363, 'Uttar Pradesh', 'RAJEEV RAI', 'GHOSI', 'ghosi', 'mp.ghosi@mplads-demo.local', 'ls_ghosi'),
(364, 'Bihar', 'RAJESH RANJAN ALIAS PAPPU YADAV', 'PURNEA', 'purnea', 'mp.purnea@mplads-demo.local', 'ls_purnea'),
(365, 'Bihar', 'RAJESH VERMA', 'KHAGARIA', 'khagaria', 'mp.khagaria@mplads-demo.local', 'ls_khagaria'),
(366, 'Gujarat', 'Rajeshbhai Naranbhai Chudasama', 'JUNAGADH', 'junagadh', 'mp.junagadh@mplads-demo.local', 'ls_junagadh'),
(367, 'Bihar', 'Rajiv Pratap Rudy', 'SARAN', 'saran', 'mp.saran@mplads-demo.local', 'ls_saran'),
(368, 'Bihar', 'Rajiv Ranjan (Lalan) Singh', 'MUNGER', 'munger', 'mp.munger@mplads-demo.local', 'ls_munger'),
(369, 'Uttar Pradesh', 'Rajkumar Chahar', 'FATEHPUR SIKRI', 'fatehpur_sikri', 'mp.fatehpur_sikri@mplads-demo.local', 'ls_fatehpur_sikri'),
(370, 'Uttar Pradesh', 'Rajnath Singh', 'LUCKNOW', 'lucknow', 'mp.lucknow@mplads-demo.local', 'ls_lucknow'),
(371, 'Gujarat', 'RAJPALSINH MAHENDRASINH JADAV', 'PANCHMAHAL', 'panchmahal', 'mp.panchmahal@mplads-demo.local', 'ls_panchmahal'),
(372, 'West Bengal', 'Raju Bista', 'DARJEELING', 'darjeeling', 'mp.darjeeling@mplads-demo.local', 'ls_darjeeling'),
(373, 'Uttar Pradesh', 'RAKESH RATHOR', 'SITAPUR', 'sitapur', 'mp.sitapur@mplads-demo.local', 'ls_sitapur'),
(374, 'Assam', 'RAKIBUL HUSSAIN', 'DHUBRI', 'dhubri', 'mp.dhubri@mplads-demo.local', 'ls_dhubri'),
(375, 'Uttar Pradesh', 'RAM PRASAD CHAUDHARY', 'BASTI', 'basti', 'mp.basti@mplads-demo.local', 'ls_basti'),
(376, 'Uttar Pradesh', 'Ram Shiromani', 'SHRAWASTI', 'shrawasti', 'mp.shrawasti@mplads-demo.local', 'ls_shrawasti'),
(377, 'Telangana', 'RAMASAHAYAM RAGHURAM REDDY', 'KHAMMAM', 'khammam', 'mp.khammam@mplads-demo.local', 'ls_khammam'),
(378, 'Uttar Pradesh', 'RAMASHANKAR RAJBHAR', 'SALEMPUR', 'salempur', 'mp.salempur@mplads-demo.local', 'ls_salempur'),
(379, 'Uttar Pradesh', 'RAMBHUAL NISHAD', 'SULTANPUR', 'sultanpur', 'mp.sultanpur@mplads-demo.local', 'ls_sultanpur'),
(380, 'Uttar Pradesh', 'RAMESH AWASTHI', 'KANPUR', 'kanpur', 'mp.kanpur@mplads-demo.local', 'ls_kanpur'),
(381, 'Karnataka', 'Ramesh Chandappa Jigajinagi', 'BIJAPUR(SC)', 'bijapur', 'mp.bijapur@mplads-demo.local', 'ls_bijapur'),
(382, 'Bihar', 'Ramprit Mandal', 'JHANJHARPUR', 'jhanjharpur', 'mp.jhanjharpur@mplads-demo.local', 'ls_jhanjharpur'),
(383, 'Delhi', 'Ramvir Singh Bidhuri', 'SOUTH DELHI', 'south_delhi', 'mp.south_delhi@mplads-demo.local', 'ls_south_delhi'),
(384, 'Assam', 'RANJIT DUTTA', 'Sonitpur', 'sonitpur', 'mp.sonitpur@mplads-demo.local', 'ls_sonitpur'),
(385, 'Haryana', 'Rao Inderjit Singh', 'GURGAON', 'gurgaon', 'mp.gurgaon@mplads-demo.local', 'ls_gurgaon'),
(386, 'Rajasthan', 'Rao Rajendra Singh', 'JAIPUR RURAL', 'jaipur_rural', 'mp.jaipur_rural@mplads-demo.local', 'ls_jaipur_rural'),
(387, 'Bihar', 'Ravi Shankar Prasad', 'PATNA SAHIB', 'patna_sahib', 'mp.patna_sahib@mplads-demo.local', 'ls_patna_sahib'),
(388, 'Maharashtra', 'RAVINDRA DATTARAM WAIKAR', 'MUMBAI NORTH WEST', 'mumbai_north_west', 'mp.mumbai_north_west@mplads-demo.local', 'ls_mumbai_north_west'),
(389, 'Uttar Pradesh', 'Ravindra Shyamnarayan Alias Ravi Kishan Shukla', 'GORAKHPUR', 'gorakhpur', 'mp.gorakhpur@mplads-demo.local', 'ls_gorakhpur'),
(390, 'Maharashtra', 'Ravindra Vasantrao Chavan', 'NANDED', 'nanded_maharashtra', 'mp.nanded_maharashtra@mplads-demo.local', 'ls_nanded_maharashtra'),
(391, 'Mizoram', 'RICHARD VANLALHMANGAIHA', 'MIZORAM (ST)', 'mizoram', 'mp.mizoram@mplads-demo.local', 'ls_mizoram'),
(392, 'Tamil Nadu', 'ROBERT BRUCE C', 'TIRUNELVELI', 'tirunelveli', 'mp.tirunelveli@mplads-demo.local', 'ls_tirunelveli'),
(393, 'Madhya Pradesh', 'Rodmal Nagar', 'RAJGARH', 'rajgarh', 'mp.rajgarh@mplads-demo.local', 'ls_rajgarh'),
(394, 'Chhattisgarh', 'ROOP KUMARI CHOUDHARY', 'MAHASAMUND', 'mahasamund', 'mp.mahasamund@mplads-demo.local', 'ls_mahasamund'),
(395, 'Uttar Pradesh', 'RUCHI VIRA', 'MORADABAD', 'moradabad', 'mp.moradabad@mplads-demo.local', 'ls_moradabad'),
(396, 'Odisha', 'RUDRA NARAYAN PANY', 'DHENKANAL', 'dhenkanal', 'mp.dhenkanal@mplads-demo.local', 'ls_dhenkanal'),
(397, 'Nagaland', 'S SUPONGMEREN JAMIR', 'NAGALAND', 'nagaland', 'mp.nagaland@mplads-demo.local', 'ls_nagaland'),
(398, 'Tamil Nadu', 'S Venkatesan', 'MADURAI', 'madurai', 'mp.madurai@mplads-demo.local', 'ls_madurai'),
(399, 'Tamil Nadu', 'S. Jagathrakshakan', 'ARAKKONAM', 'arakkonam', 'mp.arakkonam@mplads-demo.local', 'ls_arakkonam'),
(400, 'Tamil Nadu', 'SACHITHANANTHAM R', 'DINDIGUL', 'dindigul', 'mp.dindigul@mplads-demo.local', 'ls_dindigul'),
(401, 'Karnataka', 'SAGAR ESHWAR KHANDRE', 'BIDAR', 'bidar', 'mp.bidar@mplads-demo.local', 'ls_bidar'),
(402, 'Meghalaya', 'SALENG A SANGMA', 'TURA', 'tura', 'mp.tura@mplads-demo.local', 'ls_tura'),
(403, 'Odisha', 'SAMBIT PATRA', 'PURI', 'puri', 'mp.puri@mplads-demo.local', 'ls_puri'),
(404, 'Uttar Pradesh', 'SANATAN PANDEY', 'BALLIA', 'ballia', 'mp.ballia@mplads-demo.local', 'ls_ballia'),
(405, 'Maharashtra', 'SANJAY DINA PATIL', 'MUMBAI NORTH EAST', 'mumbai_north_east', 'mp.mumbai_north_east@mplads-demo.local', 'ls_mumbai_north_east'),
(406, 'Maharashtra', 'Sanjay Haribhau Jadhav', 'PARBHANI', 'parbhani', 'mp.parbhani@mplads-demo.local', 'ls_parbhani'),
(407, 'Bihar', 'Sanjay Jaiswal', 'PASCHIM CHAMPARAN', 'paschim_champaran', 'mp.paschim_champaran@mplads-demo.local', 'ls_paschim_champaran'),
(408, 'Telangana', 'Sanjay Kumar Bandi', 'KARIMNAGAR', 'karimnagar', 'mp.karimnagar@mplads-demo.local', 'ls_karimnagar'),
(409, 'Jharkhand', 'Sanjay Seth', 'RANCHI', 'ranchi', 'mp.ranchi@mplads-demo.local', 'ls_ranchi'),
(410, 'Maharashtra', 'Sanjay Uttamrao Deshmukh', 'YAVATMAL-WASHIM', 'yavatmal_washim', 'mp.yavatmal_washim@mplads-demo.local', 'ls_yavatmal_washim'),
(411, 'Rajasthan', 'SANJNA JATAV', 'BHARATPUR(SC)', 'bharatpur', 'mp.bharatpur@mplads-demo.local', 'ls_bharatpur'),
(412, 'Chhattisgarh', 'Santosh Pandey', 'RAJNANDGAON', 'rajnandgaon', 'mp.rajnandgaon@mplads-demo.local', 'ls_rajnandgaon'),
(413, 'Odisha', 'Saptagiri Sankar Ulaka', 'KORAPUT(ST)', 'koraput', 'mp.koraput@mplads-demo.local', 'ls_koraput'),
(414, 'Punjab', 'SARABJEET SINGH KHALSA', 'FARIDKOT(SC)', 'faridkot', 'mp.faridkot@mplads-demo.local', 'ls_faridkot'),
(415, 'Tamil Nadu', 'Sasikanth Senthil', 'TIRUVALLUR(SC)', 'tiruvallur', 'mp.tiruvallur@mplads-demo.local', 'ls_tiruvallur'),
(416, 'Haryana', 'SATPAL BRAHAMCHARI', 'SONEPAT', 'sonepat', 'mp.sonepat@mplads-demo.local', 'ls_sonepat'),
(417, 'West Bengal', 'Saumitra khan', 'BISHNUPUR(SC)', 'bishnupur', 'mp.bishnupur@mplads-demo.local', 'ls_bishnupur'),
(418, 'Madhya Pradesh', 'SAVITRI THAKUR', 'DHAR(ST)', 'dhar', 'mp.dhar@mplads-demo.local', 'ls_dhar'),
(419, 'West Bengal', 'SAYANI GHOSH', 'JADAVPUR', 'jadavpur', 'mp.jadavpur@mplads-demo.local', 'ls_jadavpur'),
(420, 'Haryana', 'SELJA', 'SIRSA(SC)', 'sirsa', 'mp.sirsa@mplads-demo.local', 'ls_sirsa'),
(421, 'Tamil Nadu', 'SELVAGANAPATHI T M', 'SALEM', 'salem', 'mp.salem@mplads-demo.local', 'ls_salem'),
(422, 'Tamil Nadu', 'SELVARAJ V', 'NAGAPATTINAM(SC)', 'nagapattinam', 'mp.nagapattinam@mplads-demo.local', 'ls_nagapattinam'),
(423, 'Kerala', 'SHAFI PARAMBIL', 'VADAKARA', 'vadakara', 'mp.vadakara@mplads-demo.local', 'ls_vadakara'),
(424, 'Bihar', 'SHAMBHAVI', 'SAMASTIPUR(SC)', 'samastipur', 'mp.samastipur@mplads-demo.local', 'ls_samastipur'),
(425, 'Madhya Pradesh', 'Shankar Lalwani', 'INDORE', 'indore', 'mp.indore@mplads-demo.local', 'ls_indore'),
(426, 'Uttar Pradesh', 'SHASHANK MANI', 'DEORIA', 'deoria', 'mp.deoria@mplads-demo.local', 'ls_deoria'),
(427, 'West Bengal', 'Shatrughan Sinha', 'ASANSOL', 'asansol', 'mp.asansol@mplads-demo.local', 'ls_asansol'),
(428, 'Punjab', 'SHER SINGH GHUBAYA', 'FIROZPUR', 'firozpur', 'mp.firozpur@mplads-demo.local', 'ls_firozpur'),
(429, 'Madhya Pradesh', 'SHIVMANGAL SINGH TOMAR', 'MORENA', 'morena', 'mp.morena@mplads-demo.local', 'ls_morena'),
(430, 'Madhya Pradesh', 'SHIVRAJ SINGH CHOUHAN', 'VIDISHA', 'vidisha', 'mp.vidisha@mplads-demo.local', 'ls_vidisha'),
(431, 'Karnataka', 'SHOBHA KARANDLAJE', 'BANGALORE NORTH', 'bangalore_north', 'mp.bangalore_north@mplads-demo.local', 'ls_bangalore_north'),
(432, 'Gujarat', 'SHOBHANABEN MAHENDRASINH BARAIYA', 'SABARKANTHA', 'sabarkantha', 'mp.sabarkantha@mplads-demo.local', 'ls_sabarkantha'),
(433, 'Karnataka', 'SHREYAS. M. PATEL', 'HASSAN', 'hassan', 'mp.hassan@mplads-demo.local', 'ls_hassan'),
(434, 'Haryana', 'Shri  Dharambir Singh', 'BHIWANI MAHENDRAGARH', 'bhiwani_mahendragarh', 'mp.bhiwani_mahendragarh@mplads-demo.local', 'ls_bhiwani_mahendragarh'),
(435, 'West Bengal', 'Shri Abhishek Banerjee', 'DIAMOND HARBOUR', 'diamond_harbour', 'mp.diamond_harbour@mplads-demo.local', 'ls_diamond_harbour'),
(436, 'Punjab', 'Shri Amar Singh', 'FATEHGARH SAHIB(SC)', 'fatehgarh_sahib', 'mp.fatehgarh_sahib@mplads-demo.local', 'ls_fatehgarh_sahib'),
(437, 'Gujarat', 'Shri Amit Shah', 'GANDHINAGAR', 'gandhinagar', 'mp.gandhinagar@mplads-demo.local', 'ls_gandhinagar'),
(438, 'Madhya Pradesh', 'Shri Anil Firojiya', 'UJJAIN(SC)', 'ujjain', 'mp.ujjain@mplads-demo.local', 'ls_ujjain'),
(439, 'Rajasthan', 'Shri Arjun Ram Meghwal', 'BIKANER(SC)', 'bikaner', 'mp.bikaner@mplads-demo.local', 'ls_bikaner'),
(440, 'Uttar Pradesh', 'Shri Arun Kumar Sagar', 'SHAHJAHANPUR(SC)', 'shahjahanpur', 'mp.shahjahanpur@mplads-demo.local', 'ls_shahjahanpur'),
(441, 'Karnataka', 'Shri B Y Raghavendra', 'SHIMOGA', 'shimoga', 'mp.shimoga@mplads-demo.local', 'ls_shimoga'),
(442, 'Kerala', 'Shri Benny Behanan', 'CHALAKUDY', 'chalakudy', 'mp.chalakudy@mplads-demo.local', 'ls_chalakudy'),
(443, 'Odisha', 'Shri Bhartruhari Mahtab', 'CUTTACK', 'cuttack', 'mp.cuttack@mplads-demo.local', 'ls_cuttack'),
(444, 'Jharkhand', 'Shri Chandra Prakash Choudhary', 'GIRIDIH', 'giridih', 'mp.giridih@mplads-demo.local', 'ls_giridih'),
(445, 'West Bengal', 'Shri Deepak (Dev) Adhikari', 'GHATAL', 'ghatal', 'mp.ghatal@mplads-demo.local', 'ls_ghatal'),
(446, 'Punjab', 'Shri Gurjeet Singh Aujla', 'AMRITSAR', 'amritsar', 'mp.amritsar@mplads-demo.local', 'ls_amritsar'),
(447, 'Rajasthan', 'Shri Hanuman Beniwal', 'NAGAUR', 'nagaur', 'mp.nagaur@mplads-demo.local', 'ls_nagaur'),
(448, 'Kerala', 'Shri Hibi Eden', 'ERNAKULAM', 'ernakulam', 'mp.ernakulam@mplads-demo.local', 'ls_ernakulam'),
(449, 'Bihar', 'Shri Janardan Singh Sigriwal', 'MAHARAJGANJ_BR', 'maharajganj_br', 'mp.maharajganj_br@mplads-demo.local', 'ls_maharajganj_br'),
(450, 'Odisha', 'Shri Jual Oram', 'SUNDARGARH (ST)', 'sundargarh', 'mp.sundargarh@mplads-demo.local', 'ls_sundargarh'),
(451, 'Jammu And Kashmir', 'Shri Jugal Kishore Sharma', 'JAMMU', 'jammu', 'mp.jammu@mplads-demo.local', 'ls_jammu'),
(452, 'West Bengal', 'Shri Jyotirmay Singh Mahato', 'PURULIA', 'purulia', 'mp.purulia@mplads-demo.local', 'ls_purulia'),
(453, 'Tamil Nadu', 'Shri Karti P Chidambaram', 'SIVAGANGA', 'sivaganga', 'mp.sivaganga@mplads-demo.local', 'ls_sivaganga'),
(454, 'Kerala', 'Shri Kumbakudi Sudhakaran', 'KANNUR', 'kannur', 'mp.kannur@mplads-demo.local', 'ls_kannur'),
(455, 'Karnataka', 'Shri LS Tejasvi Surya', 'BANGALORE SOUTH', 'bangalore_south', 'mp.bangalore_south@mplads-demo.local', 'ls_bangalore_south'),
(456, 'Kerala', 'Shri M K Raghavan', 'KOZHIKODE', 'kozhikode', 'mp.kozhikode@mplads-demo.local', 'ls_kozhikode'),
(457, 'Uttar Pradesh', 'Shri Narendra Modi', 'VARANASI', 'varanasi', 'mp.varanasi@mplads-demo.local', 'ls_varanasi'),
(458, 'Kerala', 'Shri NK Premachandran', 'KOLLAM', 'kollam', 'mp.kollam@mplads-demo.local', 'ls_kollam'),
(459, 'Rajasthan', 'Shri PP Chaudhary', 'PALI', 'pali', 'mp.pali@mplads-demo.local', 'ls_pali'),
(460, 'Kerala', 'Shri Rajmohan Unnithan', 'KASARAGOD', 'kasaragod', 'mp.kasaragod@mplads-demo.local', 'ls_kasaragod'),
(461, 'Assam', 'Shri Sarbananda Sonowal (18LS)', 'DIBRUGARH', 'dibrugarh', 'mp.dibrugarh@mplads-demo.local', 'ls_dibrugarh'),
(462, 'Uttar Pradesh', 'Shri Satish Kumar Gautam', 'ALIGARH', 'aligarh', 'mp.aligarh@mplads-demo.local', 'ls_aligarh'),
(463, 'West Bengal', 'Shri Shantanu Thakur', 'BANGAON(SC)', 'bangaon', 'mp.bangaon@mplads-demo.local', 'ls_bangaon'),
(464, 'Madhya Pradesh', 'Shri Sudheer Gupta', 'MANDSOUR', 'mandsour', 'mp.mandsour@mplads-demo.local', 'ls_mandsour'),
(465, 'Kerala', 'Shri Suresh Kodikunnil', 'MAVELIKKARA(SC)', 'mavelikkara', 'mp.mavelikkara@mplads-demo.local', 'ls_mavelikkara'),
(466, 'Arunachal Pradesh', 'Shri Tapir Gao', 'ARUNACHAL EAST', 'arunachal_east', 'mp.arunachal_east@mplads-demo.local', 'ls_arunachal_east'),
(467, 'Tamil Nadu', 'Shri vijayakumar Vasanth', 'KANNIYAKUMARI', 'kanniyakumari', 'mp.kanniyakumari@mplads-demo.local', 'ls_kanniyakumari'),
(468, 'Maharashtra', 'Shrikant Eknath Shinde', 'KALYAN', 'kalyan', 'mp.kalyan@mplads-demo.local', 'ls_kalyan'),
(469, 'Maharashtra', 'SHRIMANT CHH UDAYANRAJE PRATAPSINHAMAHARAJ BHONSLE', 'SATARA', 'satara', 'mp.satara@mplads-demo.local', 'ls_satara'),
(470, 'Goa', 'Shripad Yesso Naik', 'NORTH GOA', 'north_goa', 'mp.north_goa@mplads-demo.local', 'ls_north_goa'),
(471, 'Maharashtra', 'Shrirang Appa Barne', 'MAVAL', 'maval', 'mp.maval@mplads-demo.local', 'ls_maval'),
(472, 'Maharashtra', 'Shyamkumar', 'RAMTEK(SC)', 'ramtek', 'mp.ramtek@mplads-demo.local', 'ls_ramtek'),
(473, 'Andhra Pradesh', 'Sivanath Kesineni', 'VIJAYAWADA', 'vijayawada', 'mp.vijayawada@mplads-demo.local', 'ls_vijayawada'),
(474, 'West Bengal', 'SK NURUL ISLAM', 'BASIRHAT', 'basirhat', 'mp.basirhat@mplads-demo.local', 'ls_basirhat'),
(475, 'Maharashtra', 'SMITA UDAY WAGH', 'JALGAON', 'jalgaon', 'mp.jalgaon@mplads-demo.local', 'ls_jalgaon'),
(476, 'Uttar Pradesh', 'Smt Anupriya Patel', 'MIRZAPUR', 'mirzapur', 'mp.mirzapur@mplads-demo.local', 'ls_mirzapur'),
(477, 'Odisha', 'Smt Aparajita Sarangi', 'BHUBANESWAR', 'bhubaneswar', 'mp.bhubaneswar@mplads-demo.local', 'ls_bhubaneswar'),
(478, 'Uttar Pradesh', 'Smt Dimple Yadav', 'MAINPURI', 'mainpuri', 'mp.mainpuri@mplads-demo.local', 'ls_mainpuri'),
(479, 'Punjab', 'Smt Harsimrat Kaur Badal', 'BHATINDA', 'bhatinda', 'mp.bhatinda@mplads-demo.local', 'ls_bhatinda'),
(480, 'Uttar Pradesh', 'Smt Hema Malini', 'MATHURA', 'mathura', 'mp.mathura@mplads-demo.local', 'ls_mathura'),
(481, 'Madhya Pradesh', 'Smt Himadri Singh', 'SHAHDOL (ST)', 'shahdol', 'mp.shahdol@mplads-demo.local', 'ls_shahdol'),
(482, 'Gujarat', 'Smt Poonamben Hematbhai Maadam', 'JAMNAGAR', 'jamnagar', 'mp.jamnagar@mplads-demo.local', 'ls_jamnagar'),
(483, 'Maharashtra', 'Smt Raksha Nikhil Khadse', 'RAVER', 'raver', 'mp.raver@mplads-demo.local', 'ls_raver'),
(484, 'Tamil Nadu', 'Smt S Jothimani', 'KARUR', 'karur', 'mp.karur@mplads-demo.local', 'ls_karur'),
(485, 'West Bengal', 'Smt Sajda Ahmed', 'ULUBERIA', 'uluberia', 'mp.uluberia@mplads-demo.local', 'ls_uluberia'),
(486, 'Madhya Pradesh', 'Smt Sandhya Ray', 'BHIND(SC)', 'bhind', 'mp.bhind@mplads-demo.local', 'ls_bhind'),
(487, 'Odisha', 'Smt Sangeeta Kumari Singh Deo', 'BOLANGIR', 'bolangir', 'mp.bolangir@mplads-demo.local', 'ls_bolangir'),
(488, 'West Bengal', 'Smt Satabdi Roy (Banerjee)', 'BIRBHUM', 'birbhum', 'mp.birbhum@mplads-demo.local', 'ls_birbhum'),
(489, 'Maharashtra', 'Smt Supriya Sadanand Sule', 'BARAMATI', 'baramati', 'mp.baramati@mplads-demo.local', 'ls_baramati'),
(490, 'Bihar', 'Smt Veena Devi', 'VAISHALI', 'vaishali', 'mp.vaishali@mplads-demo.local', 'ls_vaishali'),
(491, 'Andhra Pradesh', 'Sribharat MathuKumli', 'VISAKHAPATNAM', 'visakhapatnam', 'mp.visakhapatnam@mplads-demo.local', 'ls_visakhapatnam'),
(492, 'Bihar', 'SUDAMA PRASAD', 'ARRAH', 'arrah', 'mp.arrah@mplads-demo.local', 'ls_arrah'),
(493, 'Tamil Nadu', 'SUDHA R', 'MAYILADUTHURAI', 'mayiladuthurai', 'mp.mayiladuthurai@mplads-demo.local', 'ls_mayiladuthurai'),
(494, 'Bihar', 'SUDHAKAR SINGH', 'BUXAR', 'buxar', 'mp.buxar@mplads-demo.local', 'ls_buxar'),
(495, 'West Bengal', 'Sudip Bandyopadhyay', 'KOLKATA UTTAR', 'kolkata_uttar', 'mp.kolkata_uttar@mplads-demo.local', 'ls_kolkata_uttar'),
(496, 'Odisha', 'SUKANTA KUMAR PANIGRAHI', 'KANDHAMAL', 'kandhamal', 'mp.kandhamal@mplads-demo.local', 'ls_kandhamal'),
(497, 'Jharkhand', 'SUKHDEO BHAGAT', 'LOHARDAGA(ST)', 'lohardaga', 'mp.lohardaga@mplads-demo.local', 'ls_lohardaga'),
(498, 'Punjab', 'SUKHJINDER SINGH RANDHAWA', 'GURDASPUR', 'gurdaspur', 'mp.gurdaspur@mplads-demo.local', 'ls_gurdaspur'),
(499, 'Karnataka', 'SUNIL BOSE', 'CHAMARAJANAGAR(SC)', 'chamarajanagar', 'mp.chamarajanagar@mplads-demo.local', 'ls_chamarajanagar'),
(500, 'Maharashtra', 'Sunil Dattatray Tatkare', 'RAIGAD', 'raigad', 'mp.raigad@mplads-demo.local', 'ls_raigad'),
(501, 'Bihar', 'Sunil Kumar', 'VALMIKI NAGAR', 'valmiki_nagar', 'mp.valmiki_nagar@mplads-demo.local', 'ls_valmiki_nagar'),
(502, 'Bihar', 'SURENDRA PRASAD YADAV', 'JAHANABAD', 'jahanabad', 'mp.jahanabad@mplads-demo.local', 'ls_jahanabad'),
(503, 'Kerala', 'SURESH GOPI', 'THRISSUR', 'thrissur', 'mp.thrissur@mplads-demo.local', 'ls_thrissur'),
(504, 'Himachal Pradesh', 'Suresh Kumar Kashyap', 'SHIMLA (SC)', 'shimla', 'mp.shimla@mplads-demo.local', 'ls_shimla'),
(505, 'Telangana', 'SURESH KUMAR SHETKAR', 'ZAHIRABAD', 'zahirabad', 'mp.zahirabad@mplads-demo.local', 'ls_zahirabad'),
(506, 'Uttar Pradesh', 'Swami Sachchidanandhari Sakshi ji Maharaj', 'UNNAO', 'unnao', 'mp.unnao@mplads-demo.local', 'ls_unnao'),
(507, 'Tamil Nadu', 'T Sumathy (A) Thamizhachi Thangapandian', 'CHENNAI SOUTH', 'chennai_south', 'mp.chennai_south@mplads-demo.local', 'ls_chennai_south'),
(508, 'Andhra Pradesh', 'TANGELLA UDAY SRINIVAS', 'KAKINADA', 'kakinada', 'mp.kakinada@mplads-demo.local', 'ls_kakinada'),
(509, 'Uttar Pradesh', 'TANUJ PUNIA', 'BARABANKI(SC)', 'barabanki', 'mp.barabanki@mplads-demo.local', 'ls_barabanki'),
(510, 'Bihar', 'TARIQ ANWAR', 'KATIHAR', 'katihar', 'mp.katihar@mplads-demo.local', 'ls_katihar'),
(511, 'Tamil Nadu', 'Thalikkottai Rajuthevar Baalu', 'SRIPERUMBUDUR', 'sriperumbudur', 'mp.sriperumbudur@mplads-demo.local', 'ls_sriperumbudur'),
(512, 'Tamil Nadu', 'THANGA TAMILSELVAN', 'THENI', 'theni', 'mp.theni@mplads-demo.local', 'ls_theni'),
(513, 'Tamil Nadu', 'THARANIVENTHAN M S', 'ARANI', 'arani', 'mp.arani@mplads-demo.local', 'ls_arani'),
(514, 'Tamil Nadu', 'Thiru Dayanidhi Maran', 'CHENNAI CENTRAL', 'chennai_central', 'mp.chennai_central@mplads-demo.local', 'ls_chennai_central'),
(515, 'Tamil Nadu', 'Thirumaa Valavan Thol', 'CHIDAMBARAM(SC)', 'chidambaram', 'mp.chidambaram@mplads-demo.local', 'ls_chidambaram'),
(516, 'Chhattisgarh', 'TOKHAN SAHU', 'BILASPUR', 'bilaspur', 'mp.bilaspur@mplads-demo.local', 'ls_bilaspur'),
(517, 'Uttarakhand', 'TRIVENDRA SINGH RAWAT', 'HARDWAR', 'hardwar', 'mp.hardwar@mplads-demo.local', 'ls_hardwar'),
(518, 'Uttar Pradesh', 'UJJWAL RAMAN SINGH', 'ALLAHABAD', 'allahabad', 'mp.allahabad@mplads-demo.local', 'ls_allahabad'),
(519, 'Rajasthan', 'UMMEDA RAM BENIWAL', 'BARMER', 'barmer', 'mp.barmer@mplads-demo.local', 'ls_barmer'),
(520, 'Uttar Pradesh', 'UTKARSH VERMA MADHUR', 'KHERI', 'kheri', 'mp.kheri@mplads-demo.local', 'ls_kheri'),
(521, 'Tamil Nadu', 'V S Matheswaran', 'NAMAKKAL', 'namakkal', 'mp.namakkal@mplads-demo.local', 'ls_namakkal'),
(522, 'Karnataka', 'V. SOMANNA', 'TUMKUR', 'tumkur', 'mp.tumkur@mplads-demo.local', 'ls_tumkur'),
(523, 'Puducherry', 'Vaithilingam Ve', 'Puducherry', 'puducherry', 'mp.puducherry@mplads-demo.local', 'ls_puducherry'),
(524, 'Telangana', 'VAMSI KRISHNA GADDAM', 'PEDDAPALLE', 'peddapalle', 'mp.peddapalle@mplads-demo.local', 'ls_peddapalle'),
(525, 'Haryana', 'VARUN CHAUDHRY', 'AMBALA (SC)', 'ambala', 'mp.ambala@mplads-demo.local', 'ls_ambala'),
(526, 'Kerala', 'Vellalath Kochukrishnan Nair Sreekandan', 'PALAKKAD', 'palakkad', 'mp.palakkad@mplads-demo.local', 'ls_palakkad'),
(527, 'Chhattisgarh', 'Vijay Baghel', 'DURG', 'durg', 'mp.durg@mplads-demo.local', 'ls_durg'),
(528, 'Uttar Pradesh', 'Vijay Kumar Dubey', 'KUSHI NAGAR', 'kushi_nagar', 'mp.kushi_nagar@mplads-demo.local', 'ls_kushi_nagar'),
(529, 'Jharkhand', 'Vijay Kumar Hansdak', 'RAJMAHAL(ST)', 'rajmahal', 'mp.rajmahal@mplads-demo.local', 'ls_rajmahal'),
(530, 'Bihar', 'VIJAYLAKSHMI DEVI', 'SIWAN', 'siwan', 'mp.siwan@mplads-demo.local', 'ls_siwan'),
(531, 'Gujarat', 'Vinod Chavda', 'KACHCHH(SC)', 'kachchh', 'mp.kachchh@mplads-demo.local', 'ls_kachchh'),
(532, 'Uttar Pradesh', 'VINOD KUMAR BIND', 'BHADOHI', 'bhadohi', 'mp.bhadohi@mplads-demo.local', 'ls_bhadohi'),
(533, 'Madhya Pradesh', 'Virendra Kumar', 'TIKAMGARH(SC)', 'tikamgarh', 'mp.tikamgarh@mplads-demo.local', 'ls_tikamgarh'),
(534, 'Uttar Pradesh', 'VIRENDRA SINGH', 'CHANDAULI', 'chandauli', 'mp.chandauli@mplads-demo.local', 'ls_chandauli'),
(535, 'Maharashtra', 'VISHAL', 'SANGLI', 'sangli', 'mp.sangli@mplads-demo.local', 'ls_sangli'),
(536, 'Jharkhand', 'Vishnu Dayal Ram', 'PALAMU(SC)', 'palamu', 'mp.palamu@mplads-demo.local', 'ls_palamu'),
(537, 'Madhya Pradesh', 'Vishnu Dutt Sharma', 'KHAJURAHO', 'khajuraho', 'mp.khajuraho@mplads-demo.local', 'ls_khajuraho'),
(538, 'Karnataka', 'VISHWESHWAR HEGDE KAGERI', 'UTTARA KANNADA', 'uttara_kannada', 'mp.uttara_kannada@mplads-demo.local', 'ls_uttara_kannada'),
(539, 'Bihar', 'VIVEK THAKUR', 'NAWADA', 'nawada', 'mp.nawada@mplads-demo.local', 'ls_nawada'),
(540, 'Andhra Pradesh', 'Y S Avinash Reddy', 'KADAPA', 'kadapa', 'mp.kadapa@mplads-demo.local', 'ls_kadapa'),
(541, 'Karnataka', 'YADUVEER KRISHNADATTA CHAMARAJA WADIYAR', 'MYSORE', 'mysore', 'mp.mysore@mplads-demo.local', 'ls_mysore'),
(542, 'Delhi', 'Yogendra Chandoliya', 'NORTH WEST DELHI(SC)', 'north_west_delhi', 'mp.north_west_delhi@mplads-demo.local', 'ls_north_west_delhi'),
(543, 'Uttar Pradesh', 'ZIA UR REHMAN', 'SAMBHAL', 'sambhal', 'mp.sambhal@mplads-demo.local', 'ls_sambhal');

-- 2. Update existing profiles email, mp_id, and ensure blank photo for unverified
UPDATE public.profiles p
SET 
  email = m.email,
  mp_id = m.mp_id,
  constituency = COALESCE(p.constituency, m.constituency),
  updated_at = now()
FROM tmp_ls_mps m
WHERE p.role = 'MP' 
  AND p.house = 'Lok Sabha'
  AND (
    LOWER(TRIM(p.mp_name)) = LOWER(TRIM(m.mp_name))
    OR LOWER(TRIM(p.constituency)) = LOWER(TRIM(m.constituency))
  );

-- Also update auth.users email for existing profiles
UPDATE auth.users u
SET 
  email = p.email,
  encrypted_password = '$2a$10$Jg1/I6hNmOcRdPl2zcxJVehx9M/RB3F9ZddlcSINE76YQQmkm77QK',
  updated_at = now()
FROM public.profiles p
WHERE p.auth_user_id = u.id
  AND p.role = 'MP'
  AND p.house = 'Lok Sabha'
  AND p.email LIKE 'mp.%@mplads-demo.local';

-- 3. Insert missing MPs into auth.users and public.profiles
DO $$
DECLARE
  r RECORD;
  new_auth_id UUID;
  new_prof_id UUID;
BEGIN
  FOR r IN 
    SELECT m.* 
    FROM tmp_ls_mps m
    LEFT JOIN public.profiles p 
      ON p.role = 'MP' 
      AND p.house = 'Lok Sabha'
      AND (
        LOWER(TRIM(p.mp_name)) = LOWER(TRIM(m.mp_name))
        OR LOWER(TRIM(p.constituency)) = LOWER(TRIM(m.constituency))
      )
    WHERE p.id IS NULL
  LOOP
    new_auth_id := gen_random_uuid();
    new_prof_id := gen_random_uuid();

    -- Insert auth.user
    INSERT INTO auth.users (
      id,
      instance_id,
      aud,
      role,
      email,
      encrypted_password,
      email_confirmed_at,
      raw_app_meta_data,
      raw_user_meta_data,
      created_at,
      updated_at
    ) VALUES (
      new_auth_id,
      '00000000-0000-0000-0000-000000000000',
      'authenticated',
      'authenticated',
      r.email,
      '$2a$10$Jg1/I6hNmOcRdPl2zcxJVehx9M/RB3F9ZddlcSINE76YQQmkm77QK',
      now(),
      '{"provider":"email","providers":["email"]}',
      json_build_object('role', 'MP', 'house', 'Lok Sabha', 'constituency', r.constituency, 'name', r.mp_name),
      now(),
      now()
    );

    -- Insert profile with photo_url = NULL (blank)
    INSERT INTO public.profiles (
      id,
      auth_user_id,
      full_name,
      role,
      house,
      state,
      constituency,
      mp_name,
      mp_id,
      email,
      photo_url,
      is_active,
      created_at,
      updated_at
    ) VALUES (
      new_prof_id,
      new_auth_id,
      'Hon''ble MP ' || r.mp_name,
      'MP',
      'Lok Sabha',
      r.state,
      r.constituency,
      r.mp_name,
      r.mp_id,
      r.email,
      NULL,
      true,
      now(),
      now()
    );

    RAISE NOTICE 'Created new MP: % (%)', r.mp_name, r.constituency;
  END LOOP;
END $$;

DROP TABLE tmp_ls_mps;
